Repository quadratichq/quadratic, pull requests merged in 2024-04, with the labels that each got.

#1249 snippets filter update
  quadratic-client/src/ui/menus/CodeEditor/snippets.ts
Labels: cla-signed

#1253 Fixes bug when rerunning code cells when there's only one code cell
  quadratic-core/src/controller/operations/code_cell.rs
Labels: cla-signed

#1257 replace Blank with None
  quadratic-kernels/python-wasm/quadratic_py/utils.py
  quadratic-kernels/python-wasm/tests/test.py
Labels: cla-signed

#1271 Log errors in multiplayer and the client for pubsub errors
  package-lock.json
  quadratic-client/package.json
  quadratic-client/src/index.tsx
  quadratic-client/src/multiplayer/multiplayer.ts
  quadratic-client/src/multiplayer/multiplayerTypes.ts
  quadratic-multiplayer/src/error.rs
  quadratic-multiplayer/src/message/handle.rs
  quadratic-multiplayer/src/message/response.rs
  quadratic-multiplayer/src/server.rs
Labels: cla-signed

#1248 fix: layout bugs on mobile
  quadratic-client/src/ui/components/PermissionOverlay.tsx
  quadratic-client/src/ui/menus/TopBar/TopBar.tsx
Labels: cla-signed

#1267 feat: configurable panel for console + ai assistant
  package-lock.json
  quadratic-client/package.json
  quadratic-client/src/shadcn/ui/tabs.tsx
  quadratic-client/src/ui/menus/CodeEditor/AiAssistant.css
  quadratic-client/src/ui/menus/CodeEditor/AiAssistant.tsx
  quadratic-client/src/ui/menus/CodeEditor/CodeEditor.tsx
  quadratic-client/src/ui/menus/CodeEditor/CodeEditorHeader.tsx
  quadratic-client/src/ui/menus/CodeEditor/Console.tsx
  quadratic-client/src/ui/menus/CodeEditor/ResizeControl.css
  quadratic-client/src/ui/menus/CodeEditor/ResizeControl.tsx
Labels: cla-signed

#1284 fix: text selection on code editor resize (safari)
  quadratic-client/src/ui/menus/CodeEditor/ResizeControl.css
Labels: cla-signed

#1266 Relative formula references
  quadratic-client/src/gridGL/pixiApp/highlightedCells.ts
  quadratic-client/src/helpers/formulaNotation.ts
  quadratic-client/src/ui/menus/CodeEditor/CodeEditor.tsx
  quadratic-client/src/ui/menus/CodeEditor/useEditorCellHighlights.ts
  quadratic-core/src/controller/operations/autocomplete.rs
  quadratic-core/src/controller/operations/clipboard.rs
  quadratic-core/src/controller/operations/code_cell.rs
  quadratic-core/src/controller/user_actions/auto_complete.rs
  quadratic-core/src/controller/user_actions/clipboard.rs
  quadratic-core/src/formulas/cell_ref.rs
  quadratic-core/src/formulas/lexer.rs
  quadratic-core/src/formulas/mod.rs
  quadratic-core/src/formulas/parser/mod.rs
  quadratic-core/src/formulas/parser/rules/atoms.rs
  quadratic-core/src/formulas/parser/rules/expression.rs
  quadratic-core/src/grid/sheet/code.rs
  quadratic-core/src/span.rs
  quadratic-core/src/test_util.rs
  quadratic-core/src/util.rs
  quadratic-core/src/wasm_bindings/controller/clipboard.rs
Labels: cla-signed

#1288 Logical in file formats and empty dataframes
  quadratic-client/src/web-workers/pythonWebWorker/pythonTypes.ts
  quadratic-client/src/web-workers/pythonWebWorker/worker/python.ts
  quadratic-core/src/grid/file/current.rs
  quadratic-kernels/python-wasm/quadratic_py/process_output.py
  quadratic-kernels/python-wasm/quadratic_py/utils.py
  quadratic-kernels/python-wasm/tests/process_output_test.py
  quadratic-kernels/python-wasm/tests/test.py
Labels: cla-signed

#1298 Fix clear color in cell fills
  quadratic-client/src/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/web-workers/quadraticCore/worker/coreClient.ts
Labels: cla-signed

#1297 fix: team name no wrap
  quadratic-client/src/app/ui/menus/TopBar/TopBarFileMenu.tsx
Labels: cla-signed

#1303 Amplify fix
  quadratic-client/package.json
  quadratic-client/vite.config.js
Labels: cla-signed

#1302 Scale round floating point numbers for display
  quadratic-core/src/grid/sheet.rs
Labels: cla-signed

#1305 remove amplify cache
  amplify.yml
Labels: cla-signed

#1309 Fix logical output for code cells
  .vscode/settings.json
  quadratic-core/src/controller/send_render.rs
  quadratic-core/src/grid/sheet/rendering.rs
  quadratic-core/src/wasm_bindings/js.rs
Labels: cla-signed

#1311 Remove license autogeneration in RustClient
  quadratic-rust-client/Cargo.toml
Labels: cla-signed

#1310 Fix code running spinner is not sheet dependent
  quadratic-client/src/app/gridGL/HTMLGrid/codeRunning/CodeRunning.tsx
  quadratic-rust-client/Cargo.toml
Labels: cla-signed

#1276 fix: HMR
  quadratic-client/src/app/gridGL/HTMLGrid/htmlCells/HtmlCells.tsx
Labels: cla-signed, status: ready to merge

#1307 fix: don't hide code editor
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditor.tsx
Labels: cla-signed, status: ready to merge

#1308 fix: code cell header label split
  package-lock.json
  quadratic-client/package-lock.json
  quadratic-client/package.json
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorHeader.tsx
Labels: cla-signed, status: ready to merge

#1235 Issue 972 csv import - fix2
  quadratic-core/src/controller/operations/import.rs
  quadratic-core/src/controller/user_actions/import.rs
  quadratic-rust-shared/data/csv/encoding_issue.csv
  quadratic-rust-shared/data/csv/simple.csv
  quadratic-rust-shared/data/csv/simple_space_separator.csv
  quadratic-rust-shared/data/csv/title_row.csv
  quadratic-rust-shared/data/csv/title_row_empty_first.csv
Labels: cla-signed

#1320 Bugfix mix relative and abslute cell highlighting
  package-lock.json
  quadratic-client/package-lock.json
  quadratic-client/src/app/gridGL/pixiApp/highlightedCells.ts
  quadratic-rust-client/src/jsexpr.rs
Labels: cla-signed, status: ready to merge

#1322 fix: show sheet name in code editor header
  quadratic-client/src/app/gridGL/pixiApp/pixiApp.css
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorHeader.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/SnippetsPopover.tsx
Labels: cla-signed, status: ready to merge

#1329 Show import errors to users
  quadratic-client/src/app/ui/components/FileUploadWrapper.tsx
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
Labels: cla-signed, status: ready for review
