Repository quadratichq/quadratic, pull requests merged in 2024-09, with the labels that each got.

#1799 fix: numbers not getting rendered after resizing other columns
  quadratic-client/src/app/helpers/float.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsLabels.ts
Labels: cla-signed, status: ready to merge

#1820 fix: remove discord link
  quadratic-client/src/app/ui/menus/FeedbackMenu/FeedbackMenu.tsx
  quadratic-client/src/shared/constants/urls.ts
Labels: cla-signed, status: ready for user test

#1814 fix: dashboard stuck in loading state on pressing back from app
  package-lock.json
  quadratic-client/package.json
  quadratic-client/src/app/ui/hooks/useFileImport.tsx
  quadratic-client/src/auth.ts
  quadratic-client/src/dashboard/components/FileDragDrop.tsx
  quadratic-client/src/dashboard/components/FilesList.tsx
  quadratic-client/src/dashboard/components/NewFileDialog.tsx
  quadratic-client/src/router.tsx
  quadratic-client/src/routes/_dashboard.tsx
  quadratic-client/src/routes/api.files.$uuid.sharing.ts
  quadratic-client/src/routes/api.files.$uuid.ts
  quadratic-client/src/routes/teams.$teamUuid.files.create.tsx
  quadratic-client/src/routes/teams.$teamUuid.tsx
  quadratic-client/src/shared/components/Avatar.tsx
  quadratic-core/src/controller/execution/execute_operation/execute_validation.rs
Labels: cla-signed, status: requested changes

#1790 fix: pressing arrow left next to = adds ref for left cell
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorKeyboard.ts
Labels: status: open question, cla-signed, status: ready for user test

#1835 fix: second file creation will result in indefinite loading
  quadratic-client/src/app/ui/hooks/useFileImport.tsx
  quadratic-client/src/dashboard/components/FilesList.tsx
  quadratic-client/src/dashboard/components/FilesListItem.tsx
  quadratic-client/src/dashboard/components/ImportProgressList.tsx
  quadratic-client/src/dashboard/components/NewFileDialog.tsx
  quadratic-client/src/dashboard/components/OnboardingBanner.tsx
  quadratic-client/src/routes/_dashboard.tsx
  quadratic-client/src/routes/api.files.$uuid.sharing.ts
  quadratic-client/src/routes/api.files.$uuid.ts
  quadratic-client/src/routes/teams.$teamUuid.files.create.tsx
  quadratic-client/src/routes/teams.$teamUuid.tsx
Labels: cla-signed, status: ready for code review, status: ready for user test

#1844 fix: switching sheets creates visual bug and gets stuck in sheet
  quadratic-client/src/app/grid/controller/Sheets.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
Labels: cla-signed, status: ready to merge

#1846 fix: use replace for create file route
  quadratic-client/src/routes/teams.$teamUuid.files.create.tsx
Labels: cla-signed

#1845 chore: actions refactor
  .vscode/settings.json
  quadratic-client/src/app/actions/actionSpec.ts
  quadratic-client/src/app/actions/actions.ts
  quadratic-client/src/app/actions/defaultActionsSpec.ts
  quadratic-client/src/app/actions/view.tsx
  quadratic-client/src/app/actions/viewActionsSpec.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorKeyboard.ts
  quadratic-client/src/app/gridGL/QuadraticGrid.tsx
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardCell.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardClipboard.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardCode.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardPosition.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardSearch.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardSelect.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardUndoRedo.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardViewport.ts
  quadratic-client/src/app/helpers/keyboardShortcuts.test.ts
  quadratic-client/src/app/helpers/keyboardShortcuts.ts
  quadratic-client/src/app/helpers/keyboardShortcutsDisplay.test.ts
  quadratic-client/src/app/helpers/keyboardShortcutsDisplay.ts
  quadratic-client/src/app/keyboard/actions.ts
  quadratic-client/src/app/keyboard/defaults.ts
  quadratic-client/src/app/keyboard/index.ts
  quadratic-client/src/app/keyboard/keys.ts
  quadratic-client/src/app/keyboard/schema.ts
  quadratic-client/src/app/keyboard/shortcut.ts
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditor.tsx
  quadratic-client/src/app/ui/menus/Toolbar/ZoomMenu.tsx
  quadratic-client/src/shared/components/icons.css
Labels: cla-signed

#1852 fix: handle empty avatar picture url
  quadratic-client/src/shared/utils/auth0UserImageSrc.ts
Labels: cla-signed, status: ready for code review, status: ready for user test

#1805 Create bump.sh to bump all js and rust versions at once
  .clabot
  .github/workflows/ci.yml
  .github/workflows/production-bump-version.yml
  Cargo.lock
  Cargo.toml
  VERSION
  bump.sh
  package.json
  quadratic-api/package.json
  quadratic-client/package.json
  quadratic-connection/Cargo.toml
  quadratic-connection/package.json
  quadratic-core/Cargo.toml
  quadratic-core/package.json
  quadratic-files/Cargo.toml
  quadratic-files/package.json
  quadratic-kernels/python-wasm/package.json
  quadratic-multiplayer/Cargo.toml
  quadratic-multiplayer/package.json
  quadratic-rust-client/Cargo.toml
  quadratic-rust-client/package.json
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: status: ready for code review, status: ready for user test

#1851 fix: edit cell bug after pointer move
  quadratic-client/src/app/gridGL/interaction/pointer/PointerDown.ts
Labels: cla-signed, status: ready for user test

#1858 fix: download file breaks ability to interact with the sheet
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-core/src/wasm_bindings/controller/mod.rs
Labels: cla-signed, status: ready for user test

#1856 fix bug with checkbox + list not properly switching
  quadratic-client/src/app/gridGL/HTMLGrid/validations/HtmlValidationCheckbox.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/validations/HtmlValidationList.tsx
Labels: status: ready for user test

#1859 Use upstream ts-rs instead of HactarCE/ts-rs
  Cargo.lock
  quadratic-core/Cargo.lock
  quadratic-core/Cargo.toml
Labels: cla-signed, type: dev, status: ready for user test

#1862 Revert "Use upstream ts-rs"
  Cargo.lock
  quadratic-core/Cargo.toml
Labels: cla-signed

#1659 make live viewport+neighbour rect available to core during transaction
  quadratic-client/src/app/gridGL/cells/CellsSheets.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
  quadratic-client/src/app/gridGL/pixiApp/Update.ts
  quadratic-client/src/app/quadratic-core-types/index.d.ts
  quadratic-client/src/app/web-workers/quadraticCore/coreRenderMessages.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreRender.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/rustCallbacks.ts
  quadratic-client/src/app/web-workers/renderWebWorker/renderClientMessages.ts
  quadratic-client/src/app/web-workers/renderWebWorker/renderWebWorker.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsLabels.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHash.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/renderClient.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/renderCore.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/renderText.ts
  quadratic-core/src/bin/export_types.rs
  quadratic-core/src/controller/active_transactions/pending_transaction.rs
  quadratic-core/src/controller/execution/control_transaction.rs
  quadratic-core/src/controller/execution/execute_operation/execute_formats.rs
  quadratic-core/src/controller/execution/execute_operation/execute_sheets.rs
  quadratic-core/src/controller/execution/execute_operation/execute_values.rs
  quadratic-core/src/controller/execution/run_code/mod.rs
  quadratic-core/src/controller/mod.rs
  quadratic-core/src/controller/operations/import.rs
  quadratic-core/src/controller/send_render.rs
  quadratic-core/src/controller/thumbnail.rs
  quadratic-core/src/controller/viewport.rs
  quadratic-core/src/grid/ids.rs
  quadratic-core/src/grid/js_types.rs
  quadratic-core/src/grid/mod.rs
  quadratic-core/src/grid/sheet.rs
  quadratic-core/src/grid/sheet/formats/format_all.rs
  quadratic-core/src/grid/sheet/formats/format_columns.rs
  quadratic-core/src/grid/sheet/formats/format_rects.rs
  quadratic-core/src/grid/sheet/formats/format_rows.rs
  quadratic-core/src/grid/sheet/formats/mod.rs
  quadratic-core/src/grid/sheet/rendering.rs
  quadratic-core/src/grid/sheet/send_render.rs
  quadratic-core/src/lib.rs
  quadratic-core/src/position.rs
  quadratic-core/src/viewport.rs
  quadratic-core/src/wasm_bindings/controller/mod.rs
  quadratic-core/src/wasm_bindings/js.rs
Labels: cla-signed, status: ready for user test

#1855 feat: add claude-3.5-sonnet to ai assistant in code editor
  .vscode/settings.json
  package-lock.json
  package.json
  quadratic-api/.env.example
  quadratic-api/package.json
  quadratic-api/src/app.ts
  quadratic-api/src/env-vars.ts
  quadratic-api/src/routes/ai/anthropic.ts
  quadratic-api/src/routes/ai/openai.ts
  quadratic-api/src/routes/ai_chat.ts
  quadratic-client/package.json
  quadratic-client/src/app/ui/hooks/useAI.tsx
  quadratic-client/src/app/ui/icons/index.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/AICodeBlockParser.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/AiAssistant.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditor.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorContext.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/Console.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/panels/CodeEditorPanelBottom.tsx
  quadratic-client/src/shared/constants/routes.ts
  quadratic-client/src/shared/shadcn/ui/textarea.tsx
  quadratic-client/src/shared/shadcn/ui/tooltip.tsx
  quadratic-shared/package.json
  quadratic-shared/tsconfig.json
  quadratic-shared/typesAndSchemasAI.ts
Labels: cla-signed, status: ready for code review

#1781 Adds autocomplete for dates, times, and date times.
  quadratic-core/.vscode/settings.json
  quadratic-core/src/grid/series.rs
  quadratic-core/src/grid/series/date_series.rs
  quadratic-core/src/grid/series/date_time_series.rs
  quadratic-core/src/grid/series/mod.rs
  quadratic-core/src/grid/series/number_series.rs
  quadratic-core/src/grid/series/string_series.rs
  quadratic-core/src/grid/series/time_series.rs
Labels: cla-signed, status: ready for code review

#1865 fix: rendering bugs due to viewport_core pr
  quadratic-client/src/app/web-workers/renderWebWorker/worker/renderCore.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/renderText.ts
  quadratic-core/src/controller/execution/execute_operation/execute_formats.rs
Labels: cla-signed

#1872 fixing date time issues
  quadratic-client/src/app/gridGL/HTMLGrid/annotations/CalendarPicker.tsx
  quadratic-client/src/app/ui/components/DateFormat.tsx
  quadratic-rust-client/src/date_time/date_time.rs
  quadratic-rust-client/src/date_time/mod.rs
Labels: cla-signed, status: ready to merge

#1888 Fix hovering top-bar menu triggers canvas events
  quadratic-client/src/app/gridGL/interaction/pointer/Pointer.ts
  quadratic-client/src/app/ui/menus/TopBar/TopBarFileMenu/EditMenubarMenu.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBarFileMenu/FileMenubarMenu.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBarFileMenu/FormatMenubarMenu.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBarFileMenu/HelpMenubarMenu.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBarFileMenu/InsertMenubarMenu.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBarFileMenu/ViewMenubarMenu.tsx
Labels: cla-signed, status: ready for code review, status: ready for user test

#1900 debug: change console output message for javascriptConvertOutputType
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascriptOutput.ts
Labels: cla-signed

#1882 fix: cannot go from multi-cell selection to single-cell selection
  quadratic-client/src/app/gridGL/interaction/pointer/PointerDown.ts
Labels: cla-signed, status: ready to merge

#1904 fix: update code cell on undo / redo
  quadratic-core/src/controller/active_transactions/pending_transaction.rs
  quadratic-core/src/controller/execution/run_code/mod.rs
Labels: cla-signed, status: ready for code review, status: ready for user test

#1871 Implement `Duration` type and arithmetic ops for dates/times/datetimes/durations in formulas
  Cargo.lock
  quadratic-client/src/app/gridGL/interaction/pointer/doubleClickCell.ts
  quadratic-client/src/app/quadratic-core-types/index.d.ts
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-core/src/controller/operations/cell_value.rs
  quadratic-core/src/controller/user_actions/validations.rs
  quadratic-core/src/error_run.rs
  quadratic-core/src/formulas/functions/mod.rs
  quadratic-core/src/formulas/functions/operators.rs
  quadratic-core/src/formulas/functions/statistics.rs
  quadratic-core/src/formulas/functions/util.rs
  quadratic-core/src/formulas/mod.rs
  quadratic-core/src/formulas/util.rs
  quadratic-core/src/grid/file/v1_5/run_error.rs
  quadratic-core/src/grid/sheet/rendering.rs
  quadratic-core/src/values/cellvalue.rs
  quadratic-core/src/values/convert.rs
  quadratic-core/src/values/date_time.rs
  quadratic-core/src/values/from_js.rs
  quadratic-core/src/values/time.rs
  quadratic-files/Cargo.toml
  quadratic-kernels/python-wasm/quadratic_py/utils.py
  quadratic-kernels/python-wasm/tests/process_output_test.py
  quadratic-kernels/python-wasm/tests/test.py
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.toml
Labels: type: enhancement, cla-signed, status: ready for user test

#1908 Remove print statement
  quadratic-kernels/python-wasm/quadratic_py/utils.py
Labels: cla-signed

#1911 fix: border menu
  quadratic-client/src/app/ui/components/BorderMenu.tsx
  quadratic-client/src/shared/components/Icons.tsx
Labels: cla-signed

#1901 chore: cleanup clones for upgrade/import/export file for v1.7
  quadratic-core/src/grid/column.rs
  quadratic-core/src/grid/file/serialize/borders.rs
  quadratic-core/src/grid/file/serialize/cell_value.rs
  quadratic-core/src/grid/file/serialize/code_cell.rs
  quadratic-core/src/grid/file/serialize/column.rs
  quadratic-core/src/grid/file/serialize/format.rs
  quadratic-core/src/grid/file/serialize/selection.rs
  quadratic-core/src/grid/file/serialize/sheets.rs
  quadratic-core/src/grid/file/serialize/validations.rs
  quadratic-core/src/grid/file/serialize/values.rs
  quadratic-core/src/grid/file/sheet_schema.rs
  quadratic-core/src/grid/file/v1_4/file.rs
  quadratic-core/src/grid/file/v1_5/file.rs
  quadratic-core/src/grid/file/v1_5/schema.rs
  quadratic-core/src/grid/file/v1_6/file.rs
  quadratic-core/src/grid/resize.rs
  quadratic-core/src/sheet_offsets/mod.rs
  quadratic-core/src/sheet_offsets/offsets.rs
Labels: cla-signed, status: ready for user test

#1893 fix: reduce the time to connection when a computer returns from sleep
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayer.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayerClientMessages.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/worker/multiplayerClient.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/worker/multiplayerServer.ts
Labels: cla-signed, status: ready for user test

#1889 Rust cleanup: `cargo fmt`; fix clippy lints, and 2024 edition migrations
  Cargo.lock
  quadratic-core/src/grid/file/v1_4/file.rs
  quadratic-multiplayer/src/message/handle.rs
  quadratic-rust-client/src/date_time/date_time_convert.rs
  quadratic-rust-client/src/date_time/mod.rs
  quadratic-rust-shared/src/error.rs
  quadratic-rust-shared/src/pubsub/redis.rs
  quadratic-rust-shared/src/pubsub/redis_streams.rs
  quadratic-rust-shared/src/sql/mod.rs
  quadratic-rust-shared/src/sql/mssql_connection.rs
Labels: cla-signed, type: dev, status: ready to merge

#1919 fix: chart(python) resizing off by a lot of pixels
  quadratic-client/src/app/gridGL/HTMLGrid/htmlCells/HtmlCell.ts
Labels: cla-signed, status: ready to merge

#1925 fix: change default ai model
  Cargo.toml
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-api/src/routes/ai/anthropic.ts
  quadratic-client/package.json
  quadratic-client/src/app/ui/menus/CodeEditor/AiAssistant.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorContext.tsx
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-client/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: cla-signed, status: ready for user test

#1927 chore: rename MsSQL to MS SQL Server
  Cargo.lock
  package-lock.json
  quadratic-client/src/app/helpers/codeCellLanguage.ts
  quadratic-client/src/dashboard/components/OnboardingBanner.tsx
  quadratic-client/src/shared/components/connections/connectionsByType.ts
  quadratic-rust-shared/src/sql/mssql_connection.rs
Labels: cla-signed, status: ready to merge

#1883 fix: decimal precision with percentages
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/convertNumber.test.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/convertNumber.ts
  quadratic-core/src/grid/sheet.rs
Labels: cla-signed, status: ready for code review, status: ready for user test

#1866 Add snowflake connection
  .github/workflows/ci.yml
  .gitignore
  Cargo.lock
  docker-compose.yml
  package-lock.json
  quadratic-api/prisma/migrations/20240910201944_add_snowflake_enum/migration.sql
  quadratic-api/prisma/schema.prisma
  quadratic-api/src/tests/testDataGenerator.ts
  quadratic-client/src/app/helpers/codeCellLanguage.ts
  quadratic-client/src/app/quadratic-core-types/index.d.ts
  quadratic-client/src/app/theme/colors.ts
  quadratic-client/src/app/ui/components/CodeSnippet.tsx
  quadratic-client/src/app/ui/components/LanguageIcon.tsx
  quadratic-client/src/app/ui/icons/index.tsx
  quadratic-client/src/dashboard/components/OnboardingBanner.tsx
  quadratic-client/src/shared/api/connectionClient.ts
  quadratic-client/src/shared/components/connections/ConnectionFormSnowflake.tsx
  quadratic-client/src/shared/components/connections/ConnectionSchemaBrowser.tsx
  quadratic-client/src/shared/components/connections/Connections.tsx
  quadratic-client/src/shared/components/connections/connectionsByType.ts
  quadratic-client/src/shared/components/connections/logo-snowflake.svg
  quadratic-connection/Cargo.toml
  quadratic-connection/package.json
  quadratic-connection/src/connection.rs
  quadratic-connection/src/server.rs
  quadratic-connection/src/sql/mod.rs
  quadratic-connection/src/sql/mssql.rs
  quadratic-connection/src/sql/mysql.rs
  quadratic-connection/src/sql/postgres.rs
  quadratic-connection/src/sql/snowflake.rs
  quadratic-connection/src/test_util.rs
  quadratic-core/src/grid/code_run.rs
  quadratic-core/src/grid/file/serialize/cell_value.rs
  quadratic-core/src/grid/file/v1_6/schema.rs
  quadratic-rust-shared/.gitignore
  quadratic-rust-shared/Cargo.toml
  quadratic-rust-shared/build.rs
  quadratic-rust-shared/data/parquet/all_native_data_types-snowflake.parquet
  quadratic-rust-shared/fixtures/snowflake-connection-schema.yml
  quadratic-rust-shared/fixtures/snowflake-connection.yml
  quadratic-rust-shared/src/error.rs
  quadratic-rust-shared/src/fixtures_path.rs
  quadratic-rust-shared/src/lib.rs
  quadratic-rust-shared/src/parquet/mod.rs
  quadratic-rust-shared/src/parquet/utils.rs
  quadratic-rust-shared/src/quadratic_api.rs
  quadratic-rust-shared/src/sql/mod.rs
  quadratic-rust-shared/src/sql/mssql_connection.rs
  quadratic-rust-shared/src/sql/mysql_connection.rs
  quadratic-rust-shared/src/sql/postgres_connection.rs
  quadratic-rust-shared/src/sql/snowflake_connection.rs
  quadratic-rust-shared/src/test/mod.rs
  quadratic-rust-shared/src/test/request.rs
  quadratic-rust-shared/src/utils/array.rs
  quadratic-rust-shared/src/utils/mod.rs
  quadratic-shared/package.json
  quadratic-shared/typesAndSchemasConnections.ts
Labels: cla-signed, status: ready to merge

#1926 fix: treat ctrl+click as right click only in Mac
  quadratic-client/src/app/gridGL/interaction/pointer/PointerDown.ts
Labels: cla-signed
