Repository quadratichq/quadratic, pull requests merged in 2024-07, with the labels that each got.

#1492 Update development.md for docker
  CONTRIBUTING.md
  DEVELOPMENT.md
  quadratic-api/.env.example
  quadratic-connection/.env.example
Labels: cla-signed

#1493 Static ip endpoint
  quadratic-connection/.env.docker
  quadratic-connection/.env.example
  quadratic-connection/.env.test
  quadratic-connection/src/auth.rs
  quadratic-connection/src/config.rs
  quadratic-connection/src/server.rs
  quadratic-connection/src/test_util.rs
  quadratic-rust-shared/src/sql/postgres_connection.rs
Labels: cla-signed, status: ready for review

#1507 fix: borders are off by 1
  quadratic-client/src/app/web-workers/quadraticCore/worker/rustConversions.ts
Labels: cla-signed, status: ready to merge

#1500 Fix bug with leaving edit cell with up or down arrow
  README.md
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorKeyboard.ts
Labels: cla-signed, status: ready to merge

#1512 fix: kernel button in bottom bar doesn't behave like other buttons
  quadratic-client/src/app/ui/menus/BottomBar/KernelMenu.tsx
Labels: cla-signed

#1513 fix: update on viewport resize
  quadratic-client/src/app/gridGL/pixiApp/Update.ts
Labels: cla-signed, status: ready for review

#1518 Sql syntax highlighting
  package-lock.json
  quadratic-client/src/app/atoms/useConnectionState.ts
  quadratic-client/src/app/atoms/useJavascriptState.ts
  quadratic-client/src/app/events/events.ts
  quadratic-client/src/app/gridGL/HTMLGrid/codeRunning/CodeRunning.tsx
  quadratic-client/src/app/helpers/codeCellLanguage.ts
  quadratic-client/src/app/ui/menus/BottomBar/KernelMenu.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditor.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorBody.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorHeader.tsx
  quadratic-client/src/app/web-workers/CodeRun.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/javascriptClientMessages.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascript.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascriptClient.ts
  quadratic-client/src/app/web-workers/languageTypes.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayer.ts
  quadratic-client/src/app/web-workers/pythonWebWorker/pythonClientMessages.ts
  quadratic-client/src/app/web-workers/pythonWebWorker/worker/python.ts
  quadratic-client/src/app/web-workers/pythonWebWorker/worker/pythonClient.ts
  quadratic-client/src/app/web-workers/quadraticCore/coreClientMessages.ts
  quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreConnection.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/rustCallbacks.ts
  quadratic-connection/src/server.rs
Labels: cla-signed

#1483 Limit bytes per query
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditor.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/ReturnTypeInspector.tsx
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreConnection.ts
  quadratic-connection/.env.docker
  quadratic-connection/.env.example
  quadratic-connection/.env.test
  quadratic-connection/src/config.rs
  quadratic-connection/src/error.rs
  quadratic-connection/src/header.rs
  quadratic-connection/src/sql/mod.rs
  quadratic-connection/src/sql/mysql.rs
  quadratic-connection/src/sql/postgres.rs
  quadratic-connection/src/state/settings.rs
  quadratic-connection/src/test_util.rs
  quadratic-core/src/controller/execution/control_transaction.rs
  quadratic-rust-shared/src/quadratic_api.rs
  quadratic-rust-shared/src/sql/mod.rs
  quadratic-rust-shared/src/sql/mysql_connection.rs
  quadratic-rust-shared/src/sql/postgres_connection.rs
Labels: cla-signed, status: ready for review

#1521 Code hint shouldn't show on when content in cell
  quadratic-client/src/app/gridGL/HTMLGrid/CodeHint.tsx
Labels: cla-signed, status: ready for review

#1522 Fix bug with double clicking in cell within CodeRun
  quadratic-client/src/app/gridGL/interaction/pointer/doubleClickCell.ts
Labels: cla-signed, status: ready for review

#1509 Improve mouse interaction with move cells
  quadratic-client/src/app/gridGL/UI/Cursor.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerCellMoving.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiAppSettings.ts
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditor.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorBody.tsx
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascriptCompile.ts
Labels: cla-signed, status: ready for review

#1441 feat: import formulas when importing xlsx file
  quadratic-client/src/app/gridGL/cells/CellsArray.ts
  quadratic-client/src/app/quadratic-core-types/index.d.ts
  quadratic-core/src/controller/execution/execute_operation/execute_code.rs
  quadratic-core/src/controller/execution/run_code/get_cells.rs
  quadratic-core/src/controller/execution/run_code/mod.rs
  quadratic-core/src/controller/execution/run_code/run_formula.rs
  quadratic-core/src/controller/operations/import.rs
  quadratic-core/src/controller/user_actions/import.rs
  quadratic-core/src/error_run.rs
  quadratic-core/src/formulas/ast.rs
  quadratic-core/src/formulas/functions/excel.rs
  quadratic-core/src/formulas/functions/mod.rs
  quadratic-core/src/formulas/lexer.rs
  quadratic-core/src/grid/file/v1_5/run_error.rs
  quadratic-core/src/span.rs
  quadratic-rust-shared/data/excel/all_excel_functions.xlsx
Labels: cla-signed, status: ready for review

#1514 Snippets fixes and insert cell references uniformly
  quadratic-client/src/app/ui/menus/CodeEditor/insertCellRef.ts
  quadratic-client/src/app/ui/menus/CodeEditor/snippetsJavascript.ts
Labels: cla-signed, status: ready for review

#1533 Fixes missing lines during initial render
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHash.ts
Labels: cla-signed, status: ready for review

#1517 Delete works properly with column/row selections
  quadratic-core/src/controller/operations/cell_value.rs
  quadratic-core/src/grid/sheet/rendering.rs
  quadratic-core/src/grid/sheet/selection.rs
  quadratic-core/src/position.rs
  quadratic-core/src/selection.rs
Labels: cla-signed, status: ready for review

#1534 Fix offline ResizeRow/Column and transaction ordering
  quadratic-client/src/app/web-workers/quadraticCore/worker/offline.ts
  quadratic-core/src/controller/active_transactions/unsaved_transactions.rs
  quadratic-core/src/controller/execution/execute_operation/execute_offsets.rs
  quadratic-core/src/controller/operations/operation.rs
  quadratic-core/src/wasm_bindings/controller/transactions.rs
Labels: cla-signed, status: ready for review

#1432 Encrypt/decrypt typeDetails in API and store encrypted in the DB
  .github/workflows/ci.yml
  docker/localstack/scripts/init.sh
  quadratic-api/.env.docker
  quadratic-api/.env.example
  quadratic-api/.env.test
  quadratic-api/.prettierignore
  quadratic-api/package.json
  quadratic-api/prisma/migrations/20240617201911_store_type_details_as_bytea/migration.sql
  quadratic-api/prisma/schema.prisma
  quadratic-api/src/data/universityDomains.ts
  quadratic-api/src/env-vars.ts
  quadratic-api/src/routes/v0/connections.$uuid.GET.test.ts
  quadratic-api/src/routes/v0/connections.$uuid.GET.ts
  quadratic-api/src/routes/v0/connections.$uuid.PUT.ts
  quadratic-api/src/routes/v0/internal.user.$auth0Id.connections.$uuid.GET.ts
  quadratic-api/src/routes/v0/teams.$uuid.connections.POST.ts
  quadratic-api/src/tests/testDataGenerator.ts
  quadratic-api/src/utils/crypto.test.ts
  quadratic-api/src/utils/crypto.ts
Labels: cla-signed, status: requested changes

#1538 Update .clabot
  .clabot
Labels: cla-signed

#1508 Fix floating Context Menu positioning
  quadratic-client/src/app/ui/menus/ContextMenu/FloatingContextMenu.tsx
Labels: cla-signed, status: ready to merge

#1498 Next connections infra2
  infra/connection/connection.ts
  infra/connection/connection_old.ts
Labels: cla-signed

#1543 Remove query stats from console and place in return type
  quadratic-client/src/app/ui/menus/CodeEditor/ReturnTypeInspector.tsx
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreConnection.ts
  quadratic-core/src/controller/execution/control_transaction.rs
  quadratic-core/src/wasm_bindings/controller/code.rs
Labels: cla-signed

#1506 Next connections ai
  quadratic-client/src/app/atoms/editorSchemaStateAtom.ts
  quadratic-client/src/app/helpers/codeCellLanguage.ts
  quadratic-client/src/app/ui/components/CodeSnippet.tsx
  quadratic-client/src/app/ui/components/SchemaViewer.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/AICodeBlockParser.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/AiAssistant.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditor.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/useSchemaData.ts
Labels: cla-signed

#1554 Next connections infra prod 2
  infra/connection/connection.ts
  infra/connection/connection_network.ts
  infra/shared/securityGroups.ts
Labels: cla-signed

#1557 don't have browser ask to save password
  quadratic-client/src/shared/components/connections/ConnectionFormMysql.tsx
  quadratic-client/src/shared/components/connections/ConnectionFormPostgres.tsx
  quadratic-client/src/shared/components/connections/ConnectionInputPassword.tsx
Labels: cla-signed

#1563 make connection_production a dep for infra
  .github/workflows/production-deploy.yml
Labels: cla-signed

#1564 deploy infra when connection service is updated
  .github/workflows/production-deploy.yml
  quadratic-api/scripts/migrate-2.ts
  quadratic-client/src/routes/teams.$teamUuid.index.tsx
Labels: cla-signed

#1568 Remove allowed-headers restrictions in the connection service to allow custom headers in the proxy
  quadratic-connection/src/server.rs
Labels: cla-signed, status: ready to merge

#1574 fix: fit-numbers branch
  docker/localstack/scripts/init-aws.sh
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts
  quadratic-client/src/dashboard/components/CustomRadixIcons.tsx
  quadratic-core/src/controller/active_transactions/unsaved_transactions.rs
  quadratic-core/src/controller/execution/control_transaction.rs
  quadratic-core/src/controller/execution/execute_operation/execute_offsets.rs
  quadratic-core/src/controller/execution/spills.rs
  quadratic-core/src/controller/operations/cell_value.rs
  quadratic-core/src/controller/user_actions/formatting.rs
  quadratic-core/src/grid/js_types.rs
  quadratic-core/src/grid/resize.rs
  quadratic-core/src/grid/sheet/bounds.rs
  quadratic-core/src/grid/sheet/rendering.rs
  quadratic-core/src/grid/sheet/row_resize.rs
  quadratic-core/src/grid/sheet/selection.rs
  quadratic-core/src/selection.rs
  quadratic-core/src/values/cellvalue.rs
  quadratic-core/src/wasm_bindings/js.rs
  quadratic-rust-shared/src/sql/mysql_connection.rs
Labels: cla-signed

#1548 Fix offline and multiplayer
  quadratic-client/src/app/debugFlags.ts
  quadratic-client/src/app/events/events.ts
  quadratic-client/src/app/ui/menus/BottomBar/SyncState.tsx
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayer.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayerClientMessages.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/worker/multiplayerClient.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/worker/multiplayerServer.ts
  quadratic-client/src/app/web-workers/quadraticCore/coreClientMessages.ts
  quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/offline.test.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/offline.ts
  quadratic-client/src/shared/components/GlobalSnackbarProvider.tsx
  quadratic-client/src/shared/constants/urls.ts
  quadratic-client/src/shared/utils/timeAgo.ts
  quadratic-core/.vscode/settings.json
  quadratic-core/src/controller/active_transactions/pending_transaction.rs
  quadratic-core/src/controller/execution/control_transaction.rs
  quadratic-core/src/controller/execution/mod.rs
  quadratic-core/src/controller/execution/receive_multiplayer.rs
Labels: cla-signed, status: ready to merge

#1529 fix: dispose undo-redo event listener
  quadratic-client/src/app/events/useUndo.ts
Labels: cla-signed, status: ready to merge

#1531 fix(client): redo not working with ctrl + shift + z
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardUndoRedo.ts
Labels: cla-signed, status: ready to merge

#1580 Append characters to the end of the text to avoid false positives
  quadratic-api/src/utils/crypto.test.ts
Labels: cla-signed

#1581 feat: add formatting state to floating context menu
  quadratic-client/src/app/ui/icons/index.tsx
  quadratic-client/src/app/ui/menus/ContextMenu/FloatingContextMenu.tsx
Labels: cla-signed

#1450 feat: make getCells synchronous
  docker/localstack/scripts/init-aws.sh
  quadratic-client/src/app/ui/menus/CodeEditor/QuadraticDocs.ts
  quadratic-client/src/app/ui/menus/CodeEditor/insertCellRef.ts
  quadratic-client/src/app/ui/menus/CodeEditor/snippetsJavascript.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascript.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascriptOutput.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascriptRunnerMessages.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/generateJavascriptForRunner.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/generatedJavascriptForEditor.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/javascriptLibrary.ts
  quadratic-client/src/app/web-workers/pythonWebWorker/pythonCoreMessages.ts
  quadratic-client/src/app/web-workers/pythonWebWorker/worker/python.ts
  quadratic-client/src/app/web-workers/pythonWebWorker/worker/pythonCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreJavascript.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/corePython.ts
  quadratic-client/src/dashboard/components/CustomRadixIcons.tsx
  quadratic-client/vite.config.js
  quadratic-kernels/python-wasm/quadratic_py/quadratic_api/quadratic.py
  quadratic-kernels/python-wasm/quadratic_py/utils.py
  quadratic-kernels/python-wasm/tests/test.py
  quadratic-rust-shared/src/sql/mysql_connection.rs
Labels: cla-signed, status: ready for user test review

#1510 fix: formula clicking to reference a cell
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorFormula.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorMonaco.ts
Labels: cla-signed, status: ready for user test review

#1516 fix: normal cell text input gets syntax highlighting
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorMonaco.ts
Labels: cla-signed, status: ready for code review, status: ready for user test review

#1569 fix: better form labels
  quadratic-client/src/shared/components/connections/ConnectionFormMysql.tsx
  quadratic-client/src/shared/components/connections/ConnectionFormPostgres.tsx
Labels: cla-signed, status: ready for code review

#1571 fix go to cell in command palette
  quadratic-client/src/app/ui/menus/CommandPalette/commands/Edit.tsx
Labels: cla-signed, status: ready for code review, status: ready for user test review

#1540 Add `MATCH` function
  quadratic-core/src/controller/execution/run_code/run_formula.rs
  quadratic-core/src/formulas/ast.rs
  quadratic-core/src/formulas/functions/logic.rs
  quadratic-core/src/formulas/functions/lookup.rs
  quadratic-core/src/formulas/functions/mathematics.rs
  quadratic-core/src/formulas/functions/statistics.rs
  quadratic-core/src/formulas/parser/mod.rs
  quadratic-core/src/formulas/tests.rs
  quadratic-core/src/values/array.rs
Labels: cla-signed, status: ready to merge

#1582 Test make cells async
  amplify.yml
  docker/localstack/scripts/init-aws.sh
  quadratic-client/src/app/ui/menus/CodeEditor/QuadraticDocs.ts
  quadratic-client/src/app/ui/menus/CodeEditor/insertCellRef.ts
  quadratic-client/src/app/ui/menus/CodeEditor/snippetsJavascript.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascript.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascriptOutput.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascriptRunnerMessages.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/generateJavascriptForRunner.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/generatedJavascriptForEditor.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/javascriptLibrary.ts
  quadratic-client/src/app/web-workers/pythonWebWorker/pythonCoreMessages.ts
  quadratic-client/src/app/web-workers/pythonWebWorker/worker/python.ts
  quadratic-client/src/app/web-workers/pythonWebWorker/worker/pythonCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreJavascript.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/corePython.ts
  quadratic-client/src/dashboard/components/CustomRadixIcons.tsx
  quadratic-client/vite.config.js
  quadratic-kernels/python-wasm/quadratic_py/quadratic_api/quadratic.py
  quadratic-kernels/python-wasm/quadratic_py/utils.py
  quadratic-kernels/python-wasm/tests/test.py
  quadratic-rust-shared/src/sql/mysql_connection.rs
  vercel.json
Labels: cla-signed

#1598 Accept multiple parquet file extensions
  quadratic-client/src/app/helpers/files.ts
  quadratic-rust-shared/data/parquet/all_supported_types.parq
  quadratic-rust-shared/data/parquet/all_supported_types.pqt
Labels: cla-signed, status: code review, status: user test

#1572 fix connections deploy on code change
  infra/connection/connection.ts
  quadratic-connection/src/server.rs
Labels: cla-signed, status: requested changes

#1586 Fixes bug when returning an empty JS multi-dimensional array
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascriptOutput.test.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascriptOutput.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascriptResults.ts
Labels: cla-signed, status: code review, status: user test

#1589 Fixes console scroll for vertical orientation
  quadratic-client/src/app/ui/menus/CodeEditor/panels/CodeEditorPanelBottom.tsx
Labels: cla-signed, status: code review, status: user test

#1590 Fix clear formatting removes borders if selection contains rects
  quadratic-core/src/controller/execution/execute_operation/execute_borders.rs
  quadratic-core/src/controller/operations/formats.rs
  quadratic-core/src/controller/user_actions/borders.rs
  quadratic-core/src/grid/sheet/bounds.rs
Labels: status: code review, status: user test

#1542 Fix empty expressions parsing in weird places in formulas
  quadratic-core/src/formulas/parser/mod.rs
  quadratic-core/src/formulas/parser/rules/atoms.rs
  quadratic-core/src/formulas/parser/rules/combinators.rs
  quadratic-core/src/formulas/parser/rules/expression.rs
Labels: cla-signed, status: user test

#1553 Improvements to ensureVisible when moving/selecting cells
  quadratic-client/src/app/grid/sheet/SheetCursor.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorKeyboard.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardPosition.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerDown.ts
  quadratic-client/src/app/gridGL/interaction/viewportHelper.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
Labels: cla-signed, status: user test

#1603 fix kernel running indicator
  quadratic-client/src/app/ui/menus/BottomBar/BottomBar.tsx
  quadratic-client/src/app/ui/menus/BottomBar/KernelMenu.tsx
Labels: cla-signed, status: user test

#1587 Fixes a bunch of problems with hmr
  quadratic-client/src/app/grid/controller/Sheets.ts
  quadratic-client/src/app/grid/sheet/Sheet.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
  quadratic-client/src/app/gridGL/interaction/pointer/Pointer.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiAppSettings.ts
  quadratic-client/src/app/ui/QuadraticApp.tsx
  quadratic-client/src/app/ui/QuadraticUI.tsx
  quadratic-client/src/app/ui/components/FileProvider.tsx
  quadratic-client/src/app/ui/menus/BottomBar/BottomBar.tsx
  quadratic-client/src/app/ui/menus/BottomBar/index.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorBody.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorHeader.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/panels/CodeEditorPanel.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/panels/CodeEditorPanelSide.tsx
  quadratic-client/src/app/ui/menus/CommandPalette/CommandPalette.tsx
  quadratic-client/src/app/ui/menus/CommandPalette/commands/File.tsx
  quadratic-client/src/app/ui/menus/ConnectionsMenu/ConnectionsMenu.tsx
  quadratic-client/src/app/ui/menus/TopBar/SubMenus/DataMenu.tsx
  quadratic-client/src/app/ui/menus/TopBar/SubMenus/FormatMenu/useGetBorderMenu.tsx
  quadratic-client/src/app/ui/menus/TopBar/SubMenus/QuadraticMenu.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBarFileMenu.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBarFileMenuDropdown.tsx
  quadratic-client/src/app/ui/menus/TopBar/index.tsx
  quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
  quadratic-client/src/routes/file.$uuid.tsx
  quadratic-client/src/shared/hooks/useFileRouteLoaderData.tsx
Labels: cla-signed, status: ready to merge

#1494 Open code editor added to data menu
  quadratic-client/src/app/grid/actions/openCodeEditor.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardCell.ts
  quadratic-client/src/app/ui/menus/TopBar/SubMenus/DataMenu.tsx
Labels: cla-signed, status: user test

#1601 feat: add basic markdown rendering in AI chat
  package-lock.json
  quadratic-client/package.json
  quadratic-client/src/app/ui/components/Markdown.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/AICodeBlockParser.tsx
Labels: type: open question, cla-signed, status: ready for user test

#1511 fix: expanded formula editor code suggestions not working
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorBody.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/useEditorCellHighlights.ts
Labels: cla-signed, status: ready to merge, status: ready for user test

#1566 chore: update schema after sql launch
  quadratic-api/prisma/migrations/20240718194955_solidify_team_schema/migration.sql
  quadratic-api/prisma/schema.prisma
  quadratic-api/src/middleware/getConnection.test.ts
  quadratic-api/src/middleware/getFile.test.ts
  quadratic-api/src/middleware/getTeam.test.ts
  quadratic-api/src/middleware/user.test.ts
  quadratic-api/src/routes/v0/connections.$uuid.DELETE.test.ts
  quadratic-api/src/routes/v0/connections.$uuid.GET.test.ts
  quadratic-api/src/routes/v0/connections.$uuid.PUT.test.ts
  quadratic-api/src/routes/v0/education.POST.test.ts
  quadratic-api/src/routes/v0/files.$uuid.GET.ts
  quadratic-api/src/routes/v0/files.$uuid.PATCH.test.ts
  quadratic-api/src/routes/v0/files.$uuid.invites.$inviteId.DELETE.test.ts
  quadratic-api/src/routes/v0/files.$uuid.invites.POST.test.ts
  quadratic-api/src/routes/v0/files.$uuid.sharing.GET.test.ts
  quadratic-api/src/routes/v0/files.$uuid.sharing.PATCH.test.ts
  quadratic-api/src/routes/v0/files.$uuid.users.$userId.DELETE.test.ts
  quadratic-api/src/routes/v0/files.$uuid.users.$userId.PATCH.test.ts
  quadratic-api/src/routes/v0/files.GET.test.ts
  quadratic-api/src/routes/v0/files.POST.test.ts
  quadratic-api/src/routes/v0/files.POST.ts
  quadratic-api/src/routes/v0/files.test.ts
  quadratic-api/src/routes/v0/teams.$uuid.GET.test.ts
  quadratic-api/src/routes/v0/teams.$uuid.PATCH.test.ts
  quadratic-api/src/routes/v0/teams.$uuid.connections.GET.test.ts
  quadratic-api/src/routes/v0/teams.$uuid.connections.POST.test.ts
  quadratic-api/src/routes/v0/teams.$uuid.invites.$inviteId.DELETE.test.ts
  quadratic-api/src/routes/v0/teams.$uuid.invites.POST.test.ts
  quadratic-api/src/routes/v0/teams.$uuid.users.$userId.DELETE.test.ts
  quadratic-api/src/routes/v0/teams.$uuid.users.$userId.PATCH.test.ts
  quadratic-api/src/routes/v0/teams.GET.test.ts
  quadratic-api/src/routes/v0/teams.GET.ts
  quadratic-api/src/stripe/stripe.ts
  quadratic-api/src/tests/testDataGenerator.ts
  quadratic-shared/typesAndSchemas.ts
Labels: cla-signed, status: ready to merge

#1605 fix api deploy
  quadratic-api/package.json
  quadratic-api/scripts/templates/migrate-1.ts
  quadratic-api/scripts/templates/migrate-2.ts
  quadratic-api/tsconfig.json
  quadratic-api/tsconfig.production.json
Labels: cla-signed

#1606 Fix Heroku Build
  Procfile
  quadratic-api/package.json
  quadratic-api/scripts/placeholder.ts
  quadratic-api/src/routes/v0/files.$uuid.GET.ts
  quadratic-api/src/routes/v0/files.POST.ts
Labels: cla-signed

#1600 fix: focus grid after closing GoTo menu and CellType menu
  quadratic-client/src/app/atoms/editorInteractionStateAtom.ts
  quadratic-client/src/app/ui/QuadraticUI.tsx
  quadratic-client/src/app/ui/components/Search.tsx
  quadratic-client/src/app/ui/menus/BottomBar/BottomBar.tsx
  quadratic-client/src/app/ui/menus/CellTypeMenu/CellTypeMenu.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditor.tsx
  quadratic-client/src/app/ui/menus/CommandPalette/CommandPalette.tsx
  quadratic-client/src/app/ui/menus/ConnectionsMenu/ConnectionsMenu.tsx
  quadratic-client/src/app/ui/menus/GoTo/GoTo.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBarZoomMenu.tsx
Labels: cla-signed, status: ready for code review

#1402 Build client in docker
  client.Dockerfile
  quadratic-client/Dockerfile
  quadratic-client/package.json
  quadratic-client/vite.config.js
  quadratic-core/src/grid/sheet/formats/format_cell.rs
  quadratic-core/src/grid/sheet/selection.rs
  quadratic-kernels/python-wasm/package.sh
  quadratic-rust-client/Cargo.toml
Labels: cla-signed, status: ready to merge, status: ready for user test

#1609 Fix string length calculation for unicode strings
  quadratic-client/src/app/web-workers/quadraticCore/worker/corePython.ts
Labels: cla-signed

#1604 Compatibility msg for browser compatibility and hardware acceleration
  quadratic-client/src/dashboard/components/BrowserCompatibilityLayoutRoute.tsx
  quadratic-client/src/shared/constants/urls.ts
Labels: cla-signed

#1618 fix: cmd + shift + arrow bugs
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardPosition.ts
  quadratic-core/src/grid/sheet/bounds.rs
Labels: cla-signed, status: ready for code review

#1612 feat: add keyboard shortcuts
  quadratic-client/src/app/grid/controller/Sheets.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorKeyboard.ts
  quadratic-client/src/app/gridGL/QuadraticGrid.tsx
  quadratic-client/src/app/gridGL/helpers/selectCells.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardCell.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardClipboard.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardCode.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardPosition.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardSearch.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardSelect.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardUndoRedo.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardViewport.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/useKeyboard.ts
  quadratic-client/src/app/gridGL/pixiApp/copyAsPNG.ts
  quadratic-client/src/app/helpers/keyboardShortcuts.test.ts
  quadratic-client/src/app/helpers/keyboardShortcuts.ts
  quadratic-client/src/app/keyboard/actions.ts
  quadratic-client/src/app/keyboard/defaults.ts
  quadratic-client/src/app/keyboard/index.ts
  quadratic-client/src/app/keyboard/keys.ts
  quadratic-client/src/app/keyboard/schema.ts
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditor.tsx
Labels: cla-signed, status: requested changes

#1537 Add ceiling, floor, `INT`, and `MOD` formula functions
  quadratic-core/proptest-regressions/formulas/functions/mathematics.txt
  quadratic-core/src/formulas/functions/lookup.rs
  quadratic-core/src/formulas/functions/macros.rs
  quadratic-core/src/formulas/functions/mathematics.rs
  quadratic-core/src/formulas/functions/statistics.rs
Labels: cla-signed, status: ready for user test

#1530 Remove gridlines overflow
  quadratic-client/src/app/grid/sheet/GridOverflowLines.test.ts
  quadratic-client/src/app/grid/sheet/GridOverflowLines.ts
  quadratic-client/src/app/grid/sheet/Sheet.ts
  quadratic-client/src/app/grid/sheet/SheetCursor.test.ts.wip
  quadratic-client/src/app/grid/sheet/bounds.test.ts
  quadratic-client/src/app/gridGL/UI/GridLines.ts
  quadratic-client/src/app/gridGL/cells/CellsSheets.ts
  quadratic-client/src/app/gridGL/cells/cellsLabel/CellsLabels.ts
  quadratic-client/src/app/web-workers/renderWebWorker/renderClientMessages.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHash.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/renderClient.ts
Labels: cla-signed, status: ready for user test

#1627 jump to axis on Cmd + (Shift)? + Arrow keys
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardPosition.ts
  quadratic-client/src/app/web-workers/quadraticCore/coreClientMessages.ts
  quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-core/src/grid/sheet/bounds.rs
  quadratic-core/src/wasm_bindings/controller/bounds.rs
Labels: cla-signed, status: ready for code review
