Repository quadratichq/quadratic, pull requests merged in 2024-06, with the labels that each got.

#1401 fix(python): wrap async functions in `(await <function-call>)`, replace `c((x,y), ...)` `cell((x,y), ...)` with `cells((x,y), ...)`
  quadratic-kernels/python-wasm/quadratic_py/utils.py
  quadratic-kernels/python-wasm/tests/test.py
Labels: cla-signed

#1403 fix: vertical offset of chart resizing right
  quadratic-client/src/app/gridGL/HTMLGrid/htmlCells/HtmlCell.ts
Labels: cla-signed, status: ready to merge

#1391 truncate test fix
  quadratic-files/src/truncate.rs
Labels: cla-signed, status: ready to merge

#1407 Fixes rendering for overly long text entries
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHash.ts
Labels: cla-signed, status: ready to merge

#1394 feat: PgUp, PgDown, Home, End, Cmd+Home, Cmd+End support
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardPosition.ts
  quadratic-client/src/app/gridGL/interaction/viewportHelper.ts
Labels: cla-signed, status: ready for review

#1416 collapsible side panel
  package-lock.json
  quadratic-client/package.json
  quadratic-client/src/app/helpers/codeCellLanguage.ts
  quadratic-client/src/app/ui/QuadraticUI.tsx
  quadratic-client/src/app/ui/connections/SchemaViewer.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/AiAssistant.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditor.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorContext.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorPanel.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorPanelBottom.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorPanelSide.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorPanels.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorPlaceholder.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/Console.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/ResizeControl.css
  quadratic-client/src/app/ui/menus/CodeEditor/ResizeControl.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/SnippetsPopover.tsx
  quadratic-client/src/shared/shadcn/ui/collapsible.tsx
Labels: cla-signed

#1422 use gpt-4o
  quadratic-api/src/routes/ai_chat.ts
  quadratic-client/src/app/ui/menus/CodeEditor/AiAssistant.tsx
Labels: cla-signed

#1424 Connection databases created and seeded for tests
  .github/workflows/ci.yml
  .gitignore
  .vscode/settings.json
  Cargo.lock
  docker-compose.yml
  docker/mysql-connection/scripts/setup.sql
  docker/mysql/.gitignore
  docker/mysql/init/init.sql
  docker/postgres-connection/scripts/setup.sql
  quadratic-connection/Cargo.toml
  quadratic-connection/package.json
  quadratic-connection/src/proxy.rs
  quadratic-connection/src/server.rs
  quadratic-connection/src/sql/mod.rs
  quadratic-connection/src/sql/mysql.rs
  quadratic-connection/src/sql/postgres.rs
  quadratic-connection/src/test_util.rs
  quadratic-rust-shared/src/sql/mod.rs
  quadratic-rust-shared/src/sql/mysql_connection.rs
  quadratic-rust-shared/src/sql/postgres_connection.rs
Labels: cla-signed

#1393 Dockerfile and scripts for building a quadratic-api docker image
  package-lock.json
  quadratic-api/Dockerfile
  quadratic-api/package.json
  quadratic-api/tsconfig.production.json
Labels: cla-signed

#1434 replace \n from code to ensure we don't wrap
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHash.ts
Labels: cla-signed, status: ready for review

#1400 fix(doc): update contributing.md
  .env.example
  .nvmrc
  CONTRIBUTING.md
  dev/cli.js
  dev/cli.ts
  dev/control.js
  dev/control.ts
  dev/help.js
  dev/help.ts
  dev/input.js
  dev/input.ts
  package.json
  quadratic-api/.env.example
  quadratic-api/.env_example
  quadratic-api/src/aws/s3.ts
  quadratic-client/.env.example
  quadratic-client/.env_example
  quadratic-files/.env.example
  quadratic-files/src/state/settings.rs
  quadratic-multiplayer/.env.example
Labels: cla-signed, status: ready for review

#1443 show file extension in import error message for unsupported type
  quadratic-client/src/app/helpers/files.ts
  quadratic-client/src/dashboard/components/CreateFileButton.tsx
Labels: cla-signed, status: ready to merge

#1475 simple unsaved indicator in CodeEditor + disable select text around app
  quadratic-client/src/app/ui/menus/CodeEditor/AICodeBlockParser.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/AiAssistant.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditor.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorHeader.tsx
  quadratic-client/src/app/ui/menus/SheetBar/SheetBar.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBar.tsx
Labels: cla-signed, status: ready to merge

#1479 fix bug with cmd+clicking the first cell in a boxed selection
  quadratic-client/src/app/gridGL/interaction/pointer/PointerDown.ts
Labels: cla-signed, status: ready to merge

#1452 refactor: pull out mui go-to menu
  quadratic-client/src/app/ui/menus/GoTo/GoTo.tsx
  quadratic-client/src/shared/shadcn/ui/command.tsx
Labels: cla-signed, status: ready for review

#1456 fix: preventDefault and stopPropagation should be called before await
  quadratic-client/src/app/grid/actions/clipboard/clipboard.ts
  quadratic-client/src/app/gridGL/HTMLGrid/htmlCells/HtmlCell.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorKeyboard.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardCell.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardClipboard.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardCode.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardSearch.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardSelect.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardUndoRedo.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardViewport.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/useKeyboard.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerDown.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerHeading.ts
  quadratic-client/src/app/ui/menus/CodeEditor/AiAssistant.tsx
  quadratic-client/src/app/ui/menus/ContextMenu/FloatingContextMenu.tsx
  quadratic-client/src/app/ui/menus/SheetBar/SheetBar.tsx
Labels: cla-signed, status: ready to merge

#1485 Update AI in JS Branch
  quadratic-client/src/app/ui/menus/CodeEditor/AiAssistant.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditor.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/Console.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/QuadraticDocs.ts
Labels: cla-signed

#1480 fix bug with numeric decimals
  quadratic-core/src/controller/operations/formatting.rs
  quadratic-core/src/controller/user_actions/formats.rs
  quadratic-core/src/grid/sheet.rs
  quadratic-core/src/grid/sheet/formats/format_cell.rs
  quadratic-core/src/grid/sheet/rendering.rs
Labels: cla-signed, status: ready for review

#1482 Allow text editing when code editor is open w/changes
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
  quadratic-client/src/app/ui/menus/CodeEditor/SaveChangesAlert.tsx
Labels: cla-signed, status: ready for review

#1491 Readme nits
  README.md
Labels: cla-signed

#1490 Update README.md
  README.md
Labels: cla-signed

#1449 Connections panels
  quadratic-api/.env.example
  quadratic-client/.env.example
  quadratic-client/src/app/ui/components/TooltipHint.tsx
  quadratic-client/src/app/ui/connections/SchemaViewer.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/AiAssistant.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditor.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorContext.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorPanel.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorPanelSide.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/panels/CodeEditorPanel.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/panels/CodeEditorPanelBottom.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/panels/CodeEditorPanelSide.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/panels/CodeEditorPanelsResize.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/panels/PanelBox.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/panels/ResizeControl.css
  quadratic-client/src/app/ui/menus/CodeEditor/panels/ResizeControl.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/panels/adjustPercentages.test.ts
  quadratic-client/src/app/ui/menus/CodeEditor/panels/adjustPercentages.ts
  quadratic-client/src/app/ui/menus/CodeEditor/panels/useCodeEditorPanelData.ts
  quadratic-client/src/shared/hooks/useLocalStorage.ts
  quadratic-client/tailwind.config.ts
Labels: cla-signed, type: dev
