Repository quadratichq/quadratic, pull requests merged in 2024-11, with the labels that each got.

#2012 ensure 1902-01 doesn't parse to date
  quadratic-core/src/date_time.rs
Labels: cla-signed, status: ready for code review, status: ready for user test

#1979 feat: filter files by creator
  quadratic-client/src/dashboard/components/FilesList.tsx
  quadratic-client/src/dashboard/components/FilesListItem.tsx
  quadratic-client/src/dashboard/components/FilesListItemCore.tsx
  quadratic-client/src/dashboard/components/FilesListViewControls.tsx
  quadratic-client/src/routes/teams.$teamUuid.index.tsx
Labels: cla-signed, status: ready for code review, status: ready for user test

#1990 Search dialog triggers when manually changing sheets
  quadratic-client/src/app/ui/components/Search.tsx
Labels: status: ready for user test, QA

#1985 fix: dirty_hashes for change_spill
  quadratic-core/src/controller/execution/spills.rs
Labels: cla-signed, status: ready for code review, status: ready for user test

#1986 devops: use aws s3 transfer acceleration
  quadratic-api/src/storage/s3.ts
Labels: cla-signed, status: ready for code review, status: ready for user test

#2034 design tweaks for fix buttons
  quadratic-client/src/app/gridGL/HTMLGrid/hoverCell/HoverCell.tsx
  quadratic-client/src/app/ui/components/FixSpillError.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditor.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/Console.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/ReturnTypeInspector.tsx
Labels: cla-signed

#2035 chore: update vite
  package-lock.json
  quadratic-client/package.json
Labels: cla-signed, status: ready to merge

#2036 fix: error triangle doesn't disappear immediately when cell contents are deleted
  quadratic-client/src/app/gridGL/cells/CellsArray.ts
Labels: cla-signed, status: ready to merge

#2037 fix: hyperlinks show up in text with a colon
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts
Labels: cla-signed, status: ready for code review

#2025 fix: goto button in edit menu and mouse hover on all menus
  quadratic-client/src/app/ui/menus/TopBar/TopBarMenus/EditMenubarMenu.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBarMenus/MenubarItemAction.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBarMenus/TopBarMenus.tsx
  quadratic-client/src/shared/shadcn/ui/menubar.tsx
Labels: cla-signed, status: ready to merge

#2038 fix: grid lines don't render for cut off text when they should
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHash.ts
Labels: cla-signed, status: ready to merge

#2041 fix: data validations don't remained centered in correct column
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHash.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHashSpecial.ts
Labels: cla-signed, status: ready to merge

#2053 fix: app slowdown
  quadratic-client/src/app/events/events.ts
  quadratic-client/src/app/gridGL/HTMLGrid/SuggestionDropdown.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/annotations/Annotations.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/codeRunning/CodeRunning.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/validations/HtmlValidationList.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/validations/useHtmlValidations.ts
  quadratic-client/src/app/gridGL/UI/UICellImages.ts
  quadratic-client/src/app/gridGL/UI/UIValidations.ts
  quadratic-client/src/app/gridGL/UI/cellHighlights/CellHighlights.ts
  quadratic-client/src/app/gridGL/cells/CellsFills.ts
  quadratic-client/src/app/gridGL/cells/CellsSearch.ts
  quadratic-client/src/app/gridGL/cells/CellsSheet.ts
  quadratic-client/src/app/gridGL/cells/CellsSheets.ts
  quadratic-client/src/app/gridGL/cells/cellsImages/CellsImages.ts
  quadratic-client/src/app/gridGL/cells/cellsLabel/CellsLabels.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiAppSettings.ts
  quadratic-client/src/app/ui/components/CursorSelectionDisplay.tsx
  quadratic-client/src/app/ui/icons/index.tsx
  quadratic-client/src/app/ui/menus/BottomBar/KernelMenu.tsx
  quadratic-client/src/app/ui/menus/BottomBar/SelectionSummary.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorHeader.tsx
  quadratic-client/src/app/ui/menus/SheetBar/SheetBar.tsx
  quadratic-client/src/app/ui/menus/Toolbar/CursorPosition.tsx
  quadratic-client/src/app/ui/menus/Validations/Validation/ValidationHeader.tsx
  quadratic-client/src/app/ui/menus/Validations/Validations/ValidationEntry.tsx
  quadratic-client/src/app/ui/menus/Validations/Validations/Validations.tsx
  quadratic-client/src/app/ui/menus/Validations/Validations/ValidationsHeader.tsx
  quadratic-client/src/app/web-workers/pythonWebWorker/worker/python.test.ts
  quadratic-client/src/shared/shadcn/ui/tooltip.tsx
Labels: cla-signed, status: ready to merge

#2048 fix: tab key sometimes inserts 2 spaces
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorMonaco.ts
Labels: status: open question, cla-signed, status: ready for user test

#2046 fix: dark mode issues
  quadratic-client/src/app/gridGL/QuadraticGrid.tsx
  quadratic-client/src/app/ui/components/TopBarLoading.tsx
  quadratic-client/src/app/ui/loading/QuadraticLoading.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBarFileNameAndLocationMenu.tsx
  quadratic-client/src/index.css
  quadratic-client/src/shared/hooks/useThemeAppearanceMode.tsx
  quadratic-client/src/shared/shadcn/styles.css
Labels: cla-signed, status: ready for code review, status: ready for user test

#2055 fix: unfollowing from the grid doesn't work
  quadratic-client/src/app/ui/components/Following.tsx
Labels: cla-signed, status: ready for code review, status: ready for user test

#2059 fix: all v1_4 code cell are imported as formula
  quadratic-core/src/grid/file/v1_4/file.rs
Labels: cla-signed, status: ready for code review, status: ready for user test

#2063 fix: jumping in the sheet when clicking into cells
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorKeyboard.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorMonaco.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
Labels: cla-signed

#2069 feat: add mixpanel events for AI
  quadratic-client/src/app/ai/components/SelectAIModelMenu.tsx
  quadratic-client/src/app/ui/components/AIUserMessageForm.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystExamplePrompts.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystUserMessageForm.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/AIAssistant/AIAssistantUserMessageForm.tsx
Labels: cla-signed

#2065 Change code editor shortcut language from "Return to sheet" to "Output to sheet" and add missing space in AI security "Learn more dialogue"
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorEmptyState.tsx
Labels: cla-signed, status: ready to merge

#2058 perf: use plotly cdn for python charts
  quadratic-kernels/python-wasm/quadratic_py/plotly_patch.py
  quadratic-kernels/python-wasm/quadratic_py/process_output.py
Labels: cla-signed, status: ready to merge

#2047 fix: disable few default keybindings in inline monaco editor
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorKeyboard.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorMonaco.ts
Labels: cla-signed, status: ready to merge

#2004 feat: new file dialog replacement
  quadratic-client/src/app/actions.ts
  quadratic-client/src/app/actions/viewActionsSpec.ts
  quadratic-client/src/app/atoms/editorInteractionStateAtom.ts
  quadratic-client/src/app/helpers/codeCellLanguage.ts
  quadratic-client/src/app/ui/QuadraticUI.tsx
  quadratic-client/src/app/ui/components/LanguageIcon.tsx
  quadratic-client/src/app/ui/hooks/useFileImport.tsx
  quadratic-client/src/app/ui/icons/index.tsx
  quadratic-client/src/app/ui/menus/CommandPalette/commands/File.tsx
  quadratic-client/src/app/ui/menus/Toolbar/Toolbar.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBarMenus/FileMenubarMenu.tsx
  quadratic-client/src/dashboard/atoms/newFileDialogAtom.ts
  quadratic-client/src/dashboard/components/DashboardSidebar.tsx
  quadratic-client/src/dashboard/components/FileDragDrop.tsx
  quadratic-client/src/dashboard/components/FilesList.tsx
  quadratic-client/src/dashboard/components/FilesListEmptyState.tsx
  quadratic-client/src/dashboard/components/NewFileButton.tsx
  quadratic-client/src/dashboard/components/NewFileDialog.tsx
  quadratic-client/src/dashboard/hooks/useConnectionSchemaBrowserTableQueryAction.tsx
  quadratic-client/src/routes/_dashboard.tsx
  quadratic-client/src/routes/teams.$teamUuid.files.private.tsx
  quadratic-client/src/shared/components/connections/ConnectionSchemaBrowser.tsx
Labels: cla-signed, status: ready to merge

#2085 feat: update code editor header to include panel positioning control
  quadratic-client/src/app/ui/components/ResizeControl.css
  quadratic-client/src/app/ui/menus/CodeEditor/AIAssistant/CodeSnippet.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditor.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorHeader.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/panels/CodeEditorPanel.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/panels/CodeEditorPanelsResize.tsx
  quadratic-client/src/shared/components/Icons.tsx
Labels: cla-signed, status: ready to merge, status: ready for code review, status: ready for user test

#2089 fix: back button when creating a new file
  quadratic-client/src/dashboard/components/DashboardSidebar.tsx
  quadratic-client/src/dashboard/components/FilesListEmptyState.tsx
  quadratic-client/src/dashboard/components/NewFileButton.tsx
Labels: cla-signed

#2083 feat: request proxying for JS & fix auth header override for both JS and Python requests
  quadratic-client/src/app/web-workers/javascriptWebWorker/javascriptClientMessages.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/javascriptWebWorker.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/getJavascriptFetchOverride.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/getJavascriptXHROverride.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascript.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascriptCompile.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascriptClient.ts
  quadratic-client/src/app/web-workers/pythonWebWorker/worker/python.ts
  quadratic-client/src/app/web-workers/pythonWebWorker/worker/pythonClient.ts
  quadratic-connection/src/proxy.rs
  quadratic-connection/src/server.rs
Labels: cla-signed, status: ready to merge, status: ready for code review

#2057 Fix bugs with custom dates
  quadratic-client/src/app/ui/components/DateFormat.tsx
  quadratic-client/src/app/ui/menus/Validations/Validation/ValidationUI/ValidationInput.tsx
  quadratic-core/src/date_time.rs
  quadratic-rust-client/src/lib.rs
Labels: cla-signed, status: ready to merge, status: ready for code review

#1972 fix: inline editor arrow key interactions (edit & enter states)
  quadratic-client/src/app/actions/actions.ts
  quadratic-client/src/app/actions/editActionsSpec.ts
  quadratic-client/src/app/atoms/inlineEditorAtom.ts
  quadratic-client/src/app/events/events.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/InlineEditor.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorFormula.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorKeyboard.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorMonaco.ts
  quadratic-client/src/app/gridGL/UI/Cursor.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardCell.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerDown.ts
  quadratic-client/src/app/gridGL/interaction/pointer/doubleClickCell.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiAppSettings.ts
  quadratic-client/src/app/keyboard/defaults.ts
  quadratic-client/src/app/ui/menus/BottomBar/BottomBar.tsx
  quadratic-client/src/shared/components/Icons.tsx
Labels: cla-signed, status: ready to merge, status: ready for user test

#2090 fix: ai tweaks
  .vscode/settings.json
  quadratic-api/src/routes/ai/anthropic.ts
  quadratic-api/src/routes/ai/bedrock.ts
  quadratic-api/src/routes/ai/openai.ts
  quadratic-client/src/app/ai/hooks/useAIRequestToAPI.tsx
  quadratic-client/src/app/ai/hooks/useCodeCellContextMessages.tsx
  quadratic-client/src/app/ai/hooks/useQuadraticContextMessages.tsx
  quadratic-client/src/app/ai/hooks/useToolUseMessages.tsx
  quadratic-client/src/app/ai/hooks/useVisibleContextMessages.tsx
  quadratic-client/src/app/ai/tools/aiToolsSpec.ts
  quadratic-client/src/app/atoms/aiAnalystAtom.ts
  quadratic-client/src/app/keyboard/defaults.ts
  quadratic-client/src/app/ui/QuadraticSidebar.tsx
  quadratic-client/src/app/ui/components/AIUserMessageForm.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalyst.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystExamplePrompts.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystHeader.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystUserMessageForm.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/AIAssistant/AIAssistant.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/panels/CodeEditorPanelBottom.tsx
Labels: cla-signed

#2093 fix: code cell outlines
  quadratic-core/src/controller/active_transactions/pending_transaction.rs
  quadratic-core/src/controller/execution/receive_multiplayer.rs
Labels: status: ready for code review

#2101 fix: new users sent to empty file
  quadratic-client/src/routes/_dashboard.tsx
Labels: cla-signed

#2095 QA Nov 22
  Cargo.toml
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-client/package.json
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/getJavascriptFetchOverride.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascriptOutput.ts
  quadratic-client/src/routes/_dashboard.tsx
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-client/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: cla-signed
