Repository quadratichq/quadratic, pull requests merged in 2024-12, with the labels that each got.

#2116 Update AI docs
  quadratic-client/src/app/ai/docs/JavascriptDocs.ts
  quadratic-client/src/app/ai/docs/PythonDocs.ts
  quadratic-client/src/app/ai/docs/QuadraticDocs.ts
Labels: cla-signed

#2120 Clear borders and formatting monstrosity
  quadratic-core/src/clear_option.rs
  quadratic-core/src/controller/execution/execute_operation/execute_formats_old.rs
  quadratic-core/src/controller/operations/borders_a1.rs
  quadratic-core/src/controller/user_actions/formats.rs
  quadratic-core/src/grid/formats/mod.rs
  quadratic-core/src/grid/formats/sheet_format_updates.rs
  quadratic-core/src/grid/sheet/borders_a1/borders_col_row.rs
  quadratic-core/src/grid/sheet/borders_a1/borders_query.rs
  quadratic-core/src/grid/sheet/borders_a1/borders_set.rs
  quadratic-core/src/grid/sheet/borders_a1/mod.rs
  quadratic-core/src/grid/sheet/formats.rs
  quadratic-core/src/grid/sheet/send_render.rs
  quadratic-core/src/grid/sheet_formatting/mod.rs
  quadratic-core/src/grid/sheet_formatting/sheet_formatting_clipboard.rs
  quadratic-core/src/grid/sheet_formatting/sheet_formatting_col_row.rs
  quadratic-core/src/grid/sheet_formatting/sheet_formatting_update.rs
  quadratic-core/src/lib.rs
Labels: cla-signed, prototype

#2129 change gtm tag
  Cargo.toml
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-client/index.html
  quadratic-client/package.json
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-client/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: cla-signed

#2131 Main
  Cargo.toml
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-client/index.html
  quadratic-client/package.json
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-client/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: cla-signed

#2137 JS properly receives 1D or 2D arrays from q.cells
  quadratic-client/src/app/quadratic-core-types/index.d.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/javascriptCoreMessages.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascript.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascriptAPI.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/generateJavascriptForRunner.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/generatedJavascriptForEditor.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/javascriptLibrary.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascriptCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreJavascript.ts
  quadratic-core/src/controller/execution/run_code/get_cells.rs
Labels: cla-signed

#2136 Account identifier clarity
  quadratic-client/src/shared/components/connections/ConnectionFormSnowflake.tsx
Labels: cla-signed

#2134 Marching ants on copy target
  quadratic-client/src/app/grid/actions/clipboard/clipboard.ts
  quadratic-client/src/app/grid/sheet/Sheet.ts
  quadratic-client/src/app/grid/sheet/SheetCursor.ts
  quadratic-client/src/app/gridGL/UI/UICopy.ts
  quadratic-client/src/app/gridGL/UI/cellHighlights/cellHighlightsDraw.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardViewport.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
  quadratic-client/src/app/gridGL/pixiApp/Update.ts
Labels: cla-signed, status: ready for user test

#2132 Add View Option: "Show AI on startup" (default = true)
  quadratic-client/src/app/atoms/aiAnalystAtom.ts
  quadratic-client/src/app/atoms/gridSettingsAtom.ts
  quadratic-client/src/app/ui/menus/TopBar/TopBarMenus/ViewMenubarMenu.tsx
Labels: cla-signed, status: ready to merge

#2121 feat: new file with prompt
  quadratic-api/src/middleware/user.ts
  quadratic-api/src/routes/v0/users.acknowledge.GET.ts
  quadratic-api/src/types/Request.ts
  quadratic-client/src/app/actions.ts
  quadratic-client/src/app/atoms/aiAnalystAtom.ts
  quadratic-client/src/app/atoms/codeEditorAtom.ts
  quadratic-client/src/app/debugFlags.ts
  quadratic-client/src/app/events/events.ts
  quadratic-client/src/app/gridGL/HTMLGrid/EmptyGridMessage.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/HTMLGridContainer.tsx
  quadratic-client/src/app/gridGL/PixiAppEffects.tsx
  quadratic-client/src/app/gridGL/pixiApp/PixiAppSettings.ts
  quadratic-client/src/app/gridGL/pixiApp/urlParams/UrlParamsUser.ts
  quadratic-client/src/app/gridGL/pixiApp/urlParams/urlParams.ts
  quadratic-client/src/app/ui/hooks/useFileImport.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/hooks/useSubmitAIAnalystPrompt.tsx
  quadratic-client/src/dashboard/components/DashboardSidebar.tsx
  quadratic-client/src/dashboard/components/FilesListEmptyState.tsx
  quadratic-client/src/dashboard/components/NewFileButton.tsx
  quadratic-client/src/dashboard/shared/getActiveTeam.ts
  quadratic-client/src/router.tsx
  quadratic-client/src/routes/_dashboard.tsx
  quadratic-client/src/routes/files.create.tsx
  quadratic-client/src/routes/login-result.tsx
  quadratic-client/src/routes/teams.$teamUuid.files.create.tsx
  quadratic-client/src/routes/teams.$teamUuid.tsx
  quadratic-client/src/shared/constants/routes.ts
  quadratic-client/src/shared/hooks/useNewFileFromState.ts
  quadratic-shared/typesAndSchemas.ts
Labels: cla-signed

#2148 QA <- Main
  quadratic-api/src/middleware/user.ts
  quadratic-api/src/routes/v0/users.acknowledge.GET.ts
  quadratic-api/src/types/Request.ts
  quadratic-client/src/app/actions.ts
  quadratic-client/src/app/atoms/aiAnalystAtom.ts
  quadratic-client/src/app/atoms/codeEditorAtom.ts
  quadratic-client/src/app/debugFlags.ts
  quadratic-client/src/app/events/events.ts
  quadratic-client/src/app/gridGL/HTMLGrid/EmptyGridMessage.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/HTMLGridContainer.tsx
  quadratic-client/src/app/gridGL/PixiAppEffects.tsx
  quadratic-client/src/app/gridGL/pixiApp/PixiAppSettings.ts
  quadratic-client/src/app/gridGL/pixiApp/urlParams/UrlParamsUser.ts
  quadratic-client/src/app/gridGL/pixiApp/urlParams/urlParams.ts
  quadratic-client/src/app/ui/hooks/useFileImport.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/hooks/useSubmitAIAnalystPrompt.tsx
  quadratic-client/src/dashboard/components/DashboardSidebar.tsx
  quadratic-client/src/dashboard/components/FilesListEmptyState.tsx
  quadratic-client/src/dashboard/components/NewFileButton.tsx
  quadratic-client/src/dashboard/shared/getActiveTeam.ts
  quadratic-client/src/router.tsx
  quadratic-client/src/routes/_dashboard.tsx
  quadratic-client/src/routes/files.create.tsx
  quadratic-client/src/routes/login-result.tsx
  quadratic-client/src/routes/teams.$teamUuid.files.create.tsx
  quadratic-client/src/routes/teams.$teamUuid.tsx
  quadratic-client/src/shared/constants/routes.ts
  quadratic-client/src/shared/hooks/useNewFileFromState.ts
  quadratic-shared/typesAndSchemas.ts
Labels: cla-signed

#2146 Data tables v1 merge 2
  quadratic-client/src/app/atoms/editorInteractionStateAtom.ts
  quadratic-client/src/app/grid/sheet/SheetCursor.ts
  quadratic-client/src/app/gridGL/HTMLGrid/contextMenus/tableSort/TableSort.tsx
  quadratic-client/src/app/gridGL/UI/Cursor.ts
  quadratic-client/src/app/gridGL/UI/UICopy.ts
  quadratic-client/src/app/gridGL/UI/cellHighlights/CellHighlights.ts
  quadratic-client/src/app/gridGL/UI/cellHighlights/cellHighlightsDraw.ts
  quadratic-client/src/app/gridGL/UI/drawCursor.ts
  quadratic-client/src/app/gridGL/cells/tables/Table.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerHeading.ts
  quadratic-client/src/app/gridGL/pixiApp/viewport/Decelerate.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/javascriptCoreMessages.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascript.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascriptAPI.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/generateJavascriptForRunner.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/generatedJavascriptForEditor.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/javascriptLibrary.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascriptCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreJavascript.ts
  quadratic-client/src/shared/components/connections/ConnectionFormSnowflake.tsx
  quadratic-client/src/shared/constants/urls.ts
  quadratic-core/src/a1/a1_selection/a1_selection_exclude.rs
  quadratic-core/src/controller/execution/run_code/get_cells.rs
Labels: cla-signed

#2149 fix: show "import data" message on new empty file
  .github/workflows/ci.yml
  quadratic-client/src/app/gridGL/HTMLGrid/EmptyGridMessage.tsx
  quadratic-core/src/grid/sheet/cell_array.rs
Labels: cla-signed

#2150 Data tables references
  quadratic-core/src/a1/error.rs
  quadratic-core/src/a1/mod.rs
  quadratic-core/src/a1/table_ref/column_range.rs
  quadratic-core/src/a1/table_ref/display.rs
  quadratic-core/src/a1/table_ref/mod.rs
  quadratic-core/src/a1/table_ref/parse.rs
  quadratic-core/src/a1/table_ref/tokenize.rs
Labels: cla-signed, prototype
