Repository quadratichq/quadratic, pull requests merged in 2024-08, with the labels that each got.

#1635 Fixes number formatting bugs
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/convertNumber.test.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/convertNumber.ts
  quadratic-core/src/controller/operations/cell_value.rs
  quadratic-core/src/controller/operations/formatting.rs
  quadratic-core/src/controller/user_actions/cells.rs
  quadratic-core/src/controller/user_actions/formats.rs
  quadratic-core/src/formulas/functions/mathematics.rs
  quadratic-core/src/grid/js_types.rs
  quadratic-core/src/grid/sheet.rs
  quadratic-core/src/values/cellvalue.rs
Labels: cla-signed

#1599 fix: execute keyboard events only when suggestion widget is hidden
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorMonaco.ts
Labels: cla-signed, status: ready for code review

#1594 Change when formula reference insertion happens
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorFormula.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorKeyboard.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorMonaco.ts
Labels: cla-signed, status: ready for user test

#1641 fix create new file on qa branch
  quadratic-api/package.json
Labels: cla-signed, status: ready for code review

#1619 feat: maintain border state
  quadratic-client/src/app/atoms/borderMenuAtom.ts
  quadratic-client/src/app/ui/menus/TopBar/SubMenus/FormatMenu/useGetBorderMenu.tsx
  quadratic-client/src/app/ui/menus/TopBar/SubMenus/useBorders.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-core/src/controller/operations/borders.rs
  quadratic-core/src/controller/operations/formats.rs
  quadratic-core/src/grid/borders/compute_indices.rs
  quadratic-core/src/grid/borders/sheet.rs
Labels: cla-signed, status: ready for code review

#1622 fix: duplicate sheet & undo delete sheet should rerun code cells
  quadratic-core/src/controller/execution/execute_operation/execute_borders.rs
  quadratic-core/src/controller/execution/execute_operation/execute_code.rs
  quadratic-core/src/controller/execution/execute_operation/execute_sheets.rs
  quadratic-core/src/controller/execution/run_code/get_cells.rs
  quadratic-core/src/controller/operations/sheets.rs
  quadratic-core/src/controller/send_render.rs
  quadratic-core/src/controller/user_actions/sheets.rs
Labels: cla-signed, status: ready for code review

#1595 perf: improve autocomplete performance
  quadratic-core/benches/grid_benchmark.rs
  quadratic-core/src/controller/active_transactions/pending_transaction.rs
  quadratic-core/src/controller/execution/auto_resize_row_heights.rs
  quadratic-core/src/controller/execution/control_transaction.rs
  quadratic-core/src/controller/execution/execute_operation/execute_borders.rs
  quadratic-core/src/controller/execution/execute_operation/execute_formats.rs
  quadratic-core/src/controller/execution/execute_operation/execute_offsets.rs
  quadratic-core/src/controller/execution/execute_operation/execute_sheets.rs
  quadratic-core/src/controller/execution/execute_operation/execute_values.rs
  quadratic-core/src/controller/execution/execute_operation/mod.rs
  quadratic-core/src/controller/execution/run_code/mod.rs
  quadratic-core/src/controller/execution/spills.rs
  quadratic-core/src/controller/operations/autocomplete.rs
  quadratic-core/src/controller/user_actions/cells.rs
  quadratic-core/src/controller/user_actions/formatting.rs
  quadratic-core/src/controller/user_actions/sheets.rs
  quadratic-core/src/grid/sheet.rs
  quadratic-core/src/grid/sheet/bounds.rs
  quadratic-core/src/grid/sheet/formats/format_rects.rs
  quadratic-core/src/grid/sheet/formats/format_rows.rs
  quadratic-core/src/grid/sheet/formatting.rs
Labels: cla-signed, status: ready for code review, status: ready for user test

#1628 wait for server sync before showing grid
  quadratic-client/src/app/events/events.ts
  quadratic-client/src/app/ui/QuadraticApp.tsx
  quadratic-client/src/app/web-workers/quadraticCore/coreClientMessages.ts
  quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/rustCallbacks.ts
  quadratic-core/src/controller/execution/receive_multiplayer.rs
  quadratic-core/src/wasm_bindings/js.rs
Labels: cla-signed, status: ready to merge

#1642 fix: text displays as NaN for code result
  quadratic-core/src/grid/sheet.rs
  quadratic-core/src/grid/sheet/rendering.rs
Labels: cla-signed, status: ready for code review

#1555 Add `INDEX` function
  quadratic-core/src/controller/execution/run_code/mod.rs
  quadratic-core/src/formulas/ast.rs
  quadratic-core/src/formulas/ctx.rs
  quadratic-core/src/formulas/functions/lookup.rs
  quadratic-core/src/formulas/functions/macros.rs
  quadratic-core/src/formulas/functions/mathematics.rs
  quadratic-core/src/formulas/functions/mod.rs
  quadratic-core/src/formulas/functions/tests.rs
  quadratic-core/src/formulas/mod.rs
  quadratic-core/src/formulas/parser/mod.rs
  quadratic-core/src/formulas/parser/rules/combinators.rs
  quadratic-core/src/formulas/parser/rules/expression.rs
  quadratic-core/src/formulas/tests.rs
  quadratic-core/src/grid/code_run.rs
  quadratic-core/src/grid/file/current.rs
  quadratic-core/src/grid/file/v1_6/schema.rs
  quadratic-core/src/grid/sheet/search.rs
  quadratic-core/src/grid/sheet/selection.rs
  quadratic-core/src/position.rs
  quadratic-core/src/span.rs
  quadratic-core/src/values/array.rs
  quadratic-core/src/values/array_size.rs
  quadratic-core/src/values/convert.rs
  quadratic-core/src/values/isblank.rs
  quadratic-core/src/values/mod.rs
Labels: cla-signed, status: ready for user test

#1625 feat: add chart interactions on click / dblclick
  quadratic-client/src/app/gridGL/HTMLGrid/hoverCell/HoverCell.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/htmlCells/HtmlCell.ts
  quadratic-client/src/app/gridGL/HTMLGrid/htmlCells/HtmlCells.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/htmlCells/htmlCellsHandler.ts
  quadratic-client/src/app/gridGL/interaction/pointer/Pointer.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerHtmlCells.ts
Labels: cla-signed, status: ready to merge

#1634 perf: improve performance of auto row resize when wrapping large dataset
  quadratic-client/src/app/events/events.ts
  quadratic-client/src/app/gridGL/cells/cellsLabel/CellsTextHash.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerAutoComplete.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerHeading.ts
  quadratic-client/src/app/gridGL/pixiApp/Update.ts
  quadratic-client/src/app/ui/components/FileUploadWrapper.tsx
  quadratic-client/src/app/ui/menus/ContextMenu/FloatingContextMenu.tsx
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsLabels.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHash.ts
  quadratic-core/benches/grid_benchmark.rs
  quadratic-core/src/controller/active_transactions/pending_transaction.rs
  quadratic-core/src/controller/execution/auto_resize_row_heights.rs
  quadratic-core/src/controller/execution/control_transaction.rs
  quadratic-core/src/controller/execution/execute_operation/execute_borders.rs
  quadratic-core/src/controller/execution/execute_operation/execute_formats.rs
  quadratic-core/src/controller/execution/execute_operation/execute_offsets.rs
  quadratic-core/src/controller/execution/execute_operation/execute_sheets.rs
  quadratic-core/src/controller/execution/execute_operation/execute_values.rs
  quadratic-core/src/controller/execution/execute_operation/mod.rs
  quadratic-core/src/controller/execution/run_code/mod.rs
  quadratic-core/src/controller/execution/spills.rs
  quadratic-core/src/controller/operations/autocomplete.rs
  quadratic-core/src/controller/user_actions/cells.rs
  quadratic-core/src/controller/user_actions/formatting.rs
  quadratic-core/src/controller/user_actions/sheets.rs
  quadratic-core/src/grid/formats/format_update.rs
  quadratic-core/src/grid/sheet.rs
  quadratic-core/src/grid/sheet/bounds.rs
  quadratic-core/src/grid/sheet/formats/format_all.rs
  quadratic-core/src/grid/sheet/formats/format_columns.rs
  quadratic-core/src/grid/sheet/formats/format_rects.rs
  quadratic-core/src/grid/sheet/formats/format_rows.rs
  quadratic-core/src/grid/sheet/formats/mod.rs
  quadratic-core/src/grid/sheet/formatting.rs
Labels: cla-signed, status: ready to merge

#1630 Add `SUMIFS` and `COUNTIFS`
  quadratic-core/src/formulas/criteria.rs
  quadratic-core/src/formulas/ctx.rs
  quadratic-core/src/formulas/functions/macros.rs
  quadratic-core/src/formulas/functions/mathematics.rs
  quadratic-core/src/formulas/functions/mod.rs
  quadratic-core/src/formulas/functions/statistics.rs
  quadratic-core/src/values/mod.rs
Labels: cla-signed, status: ready for code review

#1651 fix: position of text in inline editor wrt grid
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorMonaco.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts
Labels: cla-signed, status: ready for user test

#1660 fix: bug when clicking on code cells
  quadratic-client/src/app/gridGL/interaction/pointer/PointerHtmlCells.ts
Labels: cla-signed, status: ready for code review

#1664 fix: command + Enter should not insert a second line
  quadratic-client/src/app/keyboard/defaults.ts
Labels: cla-signed, status: ready for code review

#1669 Fix duplication issues
  quadratic-client/src/shared/api/apiClient.ts
Labels: cla-signed, status: ready for code review

#1667 fix: auto row resize for multiplayer
  quadratic-core/src/controller/execution/execute_operation/execute_formats.rs
  quadratic-core/src/controller/execution/execute_operation/execute_offsets.rs
  quadratic-core/src/controller/execution/execute_operation/execute_values.rs
  quadratic-core/src/controller/execution/run_code/mod.rs
Labels: cla-signed, status: ready for code review

#1674 fix: multiline formula bug
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorKeyboard.ts
Labels: cla-signed

#1668 fix: number formatting bugs
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHash.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/convertNumber.test.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/convertNumber.ts
  quadratic-core/src/values/cellvalue.rs
Labels: cla-signed, status: ready for user test

#1679 fix: character spacing
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts
Labels: cla-signed

#1683 start viewport at + 1 to ensure the full cursor shows
  quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
Labels: cla-signed, status: ready for code review, status: ready for user test

#1672 Improved calculation of JS line numbers for returns and Quadratic API errors
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascriptCompile.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/generateJavascriptForRunner.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/generatedJavascriptForEditor.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/javascriptLibrary.ts
Labels: cla-signed, status: ready to merge

#1689 fix: inter hash text clipping
  quadratic-client/src/app/gridGL/interaction/pointer/PointerHeading.ts
  quadratic-client/src/app/web-workers/renderWebWorker/renderClientMessages.ts
  quadratic-client/src/app/web-workers/renderWebWorker/renderWebWorker.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsLabels.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/renderClient.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/renderText.ts
Labels: cla-signed

#1690 fix: precision for formula results resolving to huge numbers
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts
Labels: cla-signed

#1692 fix: drag to move papercuts
  quadratic-client/src/app/gridGL/UI/UICellMoving.ts
  quadratic-client/src/app/gridGL/interaction/pointer/Pointer.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerCellMoving.ts
Labels: cla-signed

#1693 fix: when dragging on grid, ignore charts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerHtmlCells.ts
Labels: cla-signed, status: ready for code review, status: ready for user test

#1699 fix: lint clippy
  quadratic-core/src/formulas/functions/tests.rs
  quadratic-core/src/values/isblank.rs
Labels: cla-signed, status: ready for code review

#1701 fix: typing text into a cell inline is wrongly interpreted as a formula
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
Labels: cla-signed, status: ready for code review, status: ready for user test

#1640 Add `IFERROR` and make `IF` short-circuit
  quadratic-core/src/controller/execution/run_code/run_formula.rs
  quadratic-core/src/controller/user_actions/import.rs
  quadratic-core/src/error_run.rs
  quadratic-core/src/formulas/ast.rs
  quadratic-core/src/formulas/ctx.rs
  quadratic-core/src/formulas/functions/logic.rs
  quadratic-core/src/formulas/functions/lookup.rs
  quadratic-core/src/formulas/functions/mathematics.rs
  quadratic-core/src/formulas/functions/statistics.rs
  quadratic-core/src/formulas/functions/tests.rs
  quadratic-core/src/formulas/mod.rs
  quadratic-core/src/formulas/parser/mod.rs
  quadratic-core/src/formulas/tests.rs
  quadratic-core/src/grid/code_run.rs
  quadratic-core/src/grid/file/v1_5/run_error.rs
  quadratic-core/src/grid/sheet.rs
  quadratic-core/src/values/array.rs
  quadratic-core/src/values/cellvalue.rs
  quadratic-core/src/values/convert.rs
  quadratic-core/src/values/mod.rs
Labels: cla-signed, status: ready for code review

#1655 Add `LEN` and `LENB`
  quadratic-core/src/formulas/functions/macros.rs
  quadratic-core/src/formulas/functions/statistics.rs
  quadratic-core/src/formulas/functions/string.rs
  quadratic-core/src/formulas/functions/tests.rs
  quadratic-core/src/values/convert.rs
Labels: cla-signed, status: ready for code review

#1688 fix: flash of content when creating formulas
  quadratic-client/src/app/atoms/inlineEditorAtom.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/InlineEditor.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
  quadratic-client/src/app/gridGL/QuadraticGrid.tsx
  quadratic-client/src/app/gridGL/pixiApp/PixiAppSettings.ts
Labels: cla-signed, status: ready for code review, status: ready for user test

#1691 fix: border formatting/styling options don't work correctly
  quadratic-client/src/app/ui/menus/TopBar/SubMenus/useBorders.ts
  quadratic-core/src/controller/execution/execute_operation/execute_borders.rs
Labels: cla-signed, status: ready for code review, status: ready for user test

#1704 fix: unsynced charts disappear on refresh
  quadratic-client/src/app/gridGL/HTMLGrid/htmlCells/HtmlCells.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/htmlCells/htmlCellsHandler.ts
Labels: cla-signed

#1610 feat: import excel file into open file on xlsx file drop
  quadratic-client/src/app/atoms/userMessageAtom.ts
  quadratic-client/src/app/helpers/files.ts
  quadratic-client/src/app/ui/QuadraticUI.tsx
  quadratic-client/src/app/ui/UpdateAlertVersion.tsx
  quadratic-client/src/app/ui/components/FileUploadWrapper.tsx
  quadratic-client/src/app/ui/components/PermissionOverlay.tsx
  quadratic-client/src/app/ui/menus/TopBar/SubMenus/DataMenu.tsx
  quadratic-client/src/app/web-workers/quadraticCore/coreClientMessages.ts
  quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/shared/components/FixedBottomAlert.tsx
  quadratic-client/src/shared/components/SlideUpBottomAlert.tsx
  quadratic-client/src/shared/components/UserMessage.tsx
  quadratic-client/src/shared/constants/appConstants.ts
  quadratic-client/tailwind.config.ts
  quadratic-core/src/controller/operations/import.rs
  quadratic-core/src/controller/user_actions/import.rs
  quadratic-core/src/wasm_bindings/controller/import.rs
Labels: cla-signed, status: ready for code review

#1708 Remove nonsense digits for `f64 -> BigDecimal`
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts
  quadratic-core/src/formulas/functions/mathematics.rs
  quadratic-core/src/formulas/functions/trigonometry.rs
  quadratic-core/src/values/convert.rs
Labels: cla-signed, status: ready for code review

#1707 Add `POWER`, `EXP`, `LOG`, `LOG10`, and `LN` functions
  quadratic-core/src/formulas/functions/mathematics.rs
Labels: cla-signed, status: ready for code review

#1716 Rework get_cell_for_formula
  quadratic-core/src/grid/sheet.rs
Labels: cla-signed

#1717 Add Formulas fix to QA
  quadratic-core/src/grid/sheet.rs
Labels: cla-signed

#1719 fix python request warning
  quadratic-client/src/app/web-workers/pythonWebWorker/worker/python.ts
Labels: cla-signed, status: ready for user test

#1723 fix: number decimals clip
  quadratic-client/src/app/quadratic-core-types/index.d.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/convertNumber.ts
Labels: cla-signed, status: ready for code review

#1727 Proper fix for formula fetching cells from grid
  quadratic-core/src/controller/mod.rs
  quadratic-core/src/controller/operations/import.rs
  quadratic-core/src/controller/user_actions/code.rs
  quadratic-core/src/controller/user_actions/import.rs
  quadratic-core/src/grid/code_run.rs
  quadratic-core/src/grid/sheet.rs
Labels: cla-signed, status: ready for user test

#1743 fix: transaction would not save for manually resized rows having wrap
  quadratic-core/src/controller/execution/auto_resize_row_heights.rs
  quadratic-core/src/controller/execution/control_transaction.rs
Labels: cla-signed, status: ready to merge

#1724 fix: JS charts after refresh
  quadratic-core/src/grid/file/v1_5/file.rs
  quadratic-core/src/grid/file/v1_6/file.rs
  quadratic-rust-shared/data/grid/upgrade_code_runs_v1_5.grid
Labels: cla-signed, status: ready to merge

#1745 fix(qa): transaction would not save for manually resized rows having wrap
  quadratic-core/src/controller/execution/auto_resize_row_heights.rs
  quadratic-core/src/controller/execution/control_transaction.rs
Labels: cla-signed

#1725 fix: update code spills on value change
  quadratic-client/src/app/gridGL/cells/CellsArray.ts
  quadratic-client/src/app/gridGL/cells/CellsFills.ts
  quadratic-core/src/controller/execution/execute_operation/execute_values.rs
  quadratic-core/src/controller/execution/run_code/mod.rs
  quadratic-core/src/controller/execution/spills.rs
Labels: cla-signed, status: ready to merge, status: ready for user test

#1709 Add more string functions
  Cargo.lock
  quadratic-core/Cargo.toml
  quadratic-core/src/formulas/functions/mod.rs
  quadratic-core/src/formulas/functions/string.rs
Labels: cla-signed, status: ready to merge

#1747 fix: when resizing cursor changes to grabber when hovering over selection edge
  quadratic-client/src/app/gridGL/interaction/pointer/PointerCellMoving.ts
Labels: cla-signed, status: ready for code review, status: ready for user test

#1753 fix: importing 2nd file without page refresh results in app error
  quadratic-client/src/app/gridGL/loadAssets.ts
Labels: cla-signed, status: ready for code review, status: ready for user test

#1752 fix: disable command + r while in a code editor
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorBody.tsx
Labels: cla-signed, status: ready for code review, status: ready for user test

#1751 fix: cell highlighting not working from Python/JS
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorBody.tsx
Labels: cla-signed, status: ready for user test

#1760 fix: button on onboarding banner
  quadratic-client/src/dashboard/components/OnboardingBanner.tsx
Labels: cla-signed, status: ready for user test

#1765 fix: force reload page when switching from dashboard to app
  quadratic-client/src/app/ui/hooks/useFileImport.tsx
Labels: cla-signed

#1796 feat: team file list avatars (& misc. improvements)
  quadratic-client/src/dashboard/components/FilesListItem.tsx
  quadratic-client/src/dashboard/components/FilesListViewControlsDropdown.tsx
  quadratic-client/src/routes/teams.$teamUuid.index.tsx
  quadratic-client/src/shared/shadcn/ui/tooltip.tsx
Labels: cla-signed, status: ready to merge

#1806 patch fast xml parser
  package-lock.json
Labels: cla-signed, security

#1801 fix: add Shift+/ shortcut for show code cell menu
  quadratic-client/src/app/keyboard/defaults.ts
Labels: cla-signed, status: ready to merge

#1772 QA: Aug 22
  package-lock.json
  quadratic-client/src/app/keyboard/defaults.ts
  quadratic-client/src/dashboard/components/FilesListItem.tsx
  quadratic-client/src/dashboard/components/FilesListViewControlsDropdown.tsx
  quadratic-client/src/routes/teams.$teamUuid.index.tsx
  quadratic-client/src/shared/shadcn/ui/tooltip.tsx
Labels: cla-signed

#1677 fix: SharedArrayBuffer on safari
  amplify.yml
  package-lock.json
  quadratic-client/index.html
  quadratic-client/package.json
  quadratic-client/src/app/ui/menus/CodeEditor/AiAssistant.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBarUsers.tsx
  quadratic-client/src/dashboard/components/AvatarTeam.tsx
  quadratic-client/src/dashboard/components/BrowserCompatibilityLayoutRoute.tsx
  quadratic-client/src/dashboard/components/DashboardSidebar.tsx
  quadratic-client/src/dashboard/components/FilesListItem.tsx
  quadratic-client/src/dashboard/components/FilesListItemCore.tsx
  quadratic-client/src/dashboard/components/TeamLogo.tsx
  quadratic-client/src/routes/_dashboard.tsx
  quadratic-client/src/routes/teams.$teamUuid.index.tsx
  quadratic-client/src/shared/components/Avatar.tsx
  quadratic-client/src/shared/components/AvatarWithLetters.tsx
  quadratic-client/src/shared/components/ShareDialog.tsx
  quadratic-client/src/shared/shadcn/ui/avatar.tsx
  quadratic-client/src/shared/utils/auth0UserImageSrc.ts
  quadratic-client/vite.config.js
  vercel.json
Labels: cla-signed, status: ready for user test

#1748 fix: update codeHint show criteria
  quadratic-client/src/app/atoms/codeHintAtom.ts
  quadratic-client/src/app/gridGL/HTMLGrid/CodeHint.tsx
Labels: cla-signed, status: ready to merge

#1749 fix: text in cells not positioned properly
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorMonaco.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts
Labels: cla-signed, status: ready to merge

#1750 fix: moving formula with multi cursor incorrectly shifts formula references
  quadratic-core/src/controller/operations/clipboard.rs
Labels: cla-signed, status: ready to merge

#1775 fix: fill color should persist while editing
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorMonaco.ts
Labels: cla-signed, status: ready to merge

#1784 fix: navigate to connection from error state
  quadratic-client/src/app/ui/menus/CodeEditor/panels/CodeEditorPanel.tsx
  quadratic-client/src/dashboard/components/NewFileDialog.tsx
  quadratic-client/src/shared/components/connections/ConnectionDetails.tsx
  quadratic-client/src/shared/components/connections/ConnectionSchemaBrowser.tsx
  quadratic-client/src/shared/components/connections/Connections.tsx
  quadratic-client/src/shared/constants/routes.ts
Labels: cla-signed, status: ready to merge

#1778 Fix error reporting in formulas
  quadratic-core/src/controller/execution/run_code/run_formula.rs
  quadratic-core/src/grid/sheet/rendering.rs
  quadratic-core/src/values/array.rs
  quadratic-core/src/values/mod.rs
Labels: cla-signed, status: ready to merge

#1786 fix: clicking to close code type selector loses focus
  quadratic-client/src/app/ui/menus/CellTypeMenu/CellTypeMenu.tsx
  quadratic-client/src/app/ui/menus/CommandPalette/CommandPalette.tsx
  quadratic-client/src/app/ui/menus/GoTo/GoTo.tsx
  quadratic-client/src/shared/shadcn/ui/command.tsx
Labels: cla-signed, status: ready to merge

#1776 fix: double-click to inline edit scrolls the sheet incorrectly
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorMonaco.ts
Labels: cla-signed, status: ready for user test

#1787 fix: pasting formula text doesn't automatically create formula
  quadratic-core/src/controller/operations/cell_value.rs
  quadratic-core/src/controller/operations/clipboard.rs
Labels: cla-signed, status: ready to merge

#1793 fix: early keystrokes are dropped when editing a cell
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
Labels: cla-signed, status: ready to merge

#1803 fix: drag n drop for moving clashes with drag n drop for import
  quadratic-client/src/app/ui/components/FileDragDropWrapper.tsx
  quadratic-client/src/dashboard/components/FilesList.tsx
  quadratic-client/src/dashboard/components/NewFileDialog.tsx
Labels: cla-signed, status: ready for code review, status: ready for user test

#1789 fix: move viewport event handler to QuadraticGrid component from window object
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardSearch.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardViewport.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/useKeyboard.ts
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorBody.tsx
Labels: cla-signed, status: ready for user test

#1782 Fix console.log bug in JS
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascriptCompile.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/generatedJavascriptForEditor.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/javascriptLibrary.ts
Labels: cla-signed, status: ready to merge

#1788 fix: passing a bad sheetId params in javascript getCells puts you in an infinite loop
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreJavascript.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/corePython.ts
  quadratic-core/src/controller/execution/run_code/mod.rs
  quadratic-core/src/error_run.rs
Labels: cla-signed, status: ready to merge

#1783 fix: plain-text user prompt in the AI assistant
  quadratic-client/src/app/ui/menus/CodeEditor/AiAssistant.tsx
Labels: cla-signed, status: ready to merge

#1769 fix: excel import in existing file
  quadratic-client/src/app/ui/hooks/useFileImport.tsx
  quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/dashboard/atoms/filesImportProgressAtom.ts
Labels: cla-signed, status: ready to merge

#1792 fix: long loading time due to multiplayer connection
  quadratic-client/src/app/ui/QuadraticApp.tsx
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/offline.ts
  quadratic-core/src/controller/execution/receive_multiplayer.rs
Labels: cla-signed, status: ready to merge

#1812 fix: stacktrace for JS coderun in safari
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascriptCompile.ts
Labels: cla-signed, status: ready to merge

#1794 fix: javaScript charts not anchored to their cell when resizing columns
  quadratic-client/src/app/gridGL/cells/CellsSheets.ts
  quadratic-client/src/app/gridGL/cells/cellsImages/CellsImages.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHash.ts
Labels: cla-signed, status: ready for user test

#1811 Data validation fixes
  quadratic-client/src/app/gridGL/HTMLGrid/validations/HtmlValidationList.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/validations/HtmlValidationMessage.tsx
Labels: cla-signed, status: ready to merge

#1817 fix: click to select on command dialog
  quadratic-client/src/app/ui/menus/CellTypeMenu/CellTypeMenu.tsx
  quadratic-client/src/app/ui/menus/CommandPalette/CommandPaletteListItem.tsx
  quadratic-client/src/app/ui/menus/GoTo/GoTo.tsx
Labels: cla-signed, status: ready to merge
