Repository quadratichq/quadratic, pull requests merged in 2024-10, with the labels that each got.

#1934 feat: post-redesign tweaks
  quadratic-client/src/app/actions/actions.ts
  quadratic-client/src/app/actions/editActionsSpec.ts
  quadratic-client/src/app/actions/helpActionsSpec.ts
  quadratic-client/src/app/ui/QuadraticSidebar.tsx
  quadratic-client/src/app/ui/menus/CommandPalette/commands/Help.tsx
  quadratic-client/src/app/ui/menus/FeedbackMenu/FeedbackMenu.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBarFileMenu/EditMenubarMenu.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBarFileMenu/HelpMenubarMenu.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBarFileMenu/index.tsx
  quadratic-client/src/shared/components/connections/logo-mssql.svg
  quadratic-client/src/shared/components/connections/logo-postgres.svg
  quadratic-client/src/shared/components/connections/logo-snowflake.svg
  quadratic-client/src/shared/shadcn/ui/menubar.tsx
Labels: cla-signed, status: ready for code review, status: ready for user test

#1931 Fixes bug with drag position when dragging sheet (in prod)
  quadratic-client/src/app/ui/menus/SheetBar/SheetBar.tsx
Labels: cla-signed

#1939 Fix Match formula
  quadratic-core/src/formulas/functions/lookup.rs
  quadratic-core/src/values/convert.rs
Labels: cla-signed, status: ready for user test

#1940 fix: esc on file menu will refocus grid
  quadratic-client/src/shared/shadcn/ui/menubar.tsx
Labels: status: ready for code review, status: ready for user test

#1905 Text autocomplete based on column neighbors
  Cargo.lock
  quadratic-client/src/app/events/events.ts
  quadratic-client/src/app/grid/sheet/Sheet.ts
  quadratic-client/src/app/gridGL/HTMLGrid/HTMLGridContainer.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/SuggestionDropdown.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorEvents.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorKeyboard.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorMonaco.ts
  quadratic-client/src/app/gridGL/HTMLGrid/validations/HtmlValidationList.tsx
  quadratic-client/src/app/gridGL/helpers/intersects.test.ts
  quadratic-client/src/app/gridGL/helpers/intersects.ts
  quadratic-client/src/app/web-workers/quadraticCore/coreClientMessages.ts
  quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
  quadratic-core/src/grid/sheet/search.rs
  quadratic-core/src/wasm_bindings/controller/search.rs
  quadratic-core/src/wasm_bindings/controller/summarize.rs
Labels: cla-signed, status: ready to merge

#1929 Insert today's date (shortcut: ctrl+;)
  quadratic-client/src/app/actions/actions.ts
  quadratic-client/src/app/actions/insertActionsSpec.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorKeyboard.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/useKeyboard.ts
  quadratic-client/src/app/keyboard/defaults.ts
  quadratic-client/src/app/ui/menus/CommandPalette/commands/Edit.tsx
Labels: cla-signed, status: ready to merge

#1942 added ctrl+; for time now; fixed bug with inserting while editor is open
  quadratic-client/.vscode/settings.json
  quadratic-client/src/app/actions/actions.ts
  quadratic-client/src/app/actions/insertActionsSpec.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorKeyboard.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/useKeyboard.ts
  quadratic-client/src/app/keyboard/defaults.ts
  quadratic-client/src/app/ui/menus/CommandPalette/commands/Edit.tsx
Labels: cla-signed, status: ready for code review

#1885 Change Sheet saves input (for non-formula inline editor)
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
Labels: cla-signed, status: ready for user test, QA

#1930 chore: enable receive multiplayer transactions
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-core/src/controller/execution/receive_multiplayer.rs
  quadratic-core/src/wasm_bindings/controller/transactions.rs
Labels: cla-signed, type: dev, status: ready to merge, QA

#1742 Add `UNIQUE`, `SORT`, and `FILTER`
  quadratic-core/src/error_run.rs
  quadratic-core/src/formulas/criteria.rs
  quadratic-core/src/formulas/functions/array.rs
  quadratic-core/src/formulas/functions/logic.rs
  quadratic-core/src/formulas/functions/lookup.rs
  quadratic-core/src/formulas/functions/mod.rs
  quadratic-core/src/formulas/functions/operators.rs
  quadratic-core/src/formulas/tests.rs
  quadratic-core/src/util.rs
  quadratic-core/src/values/array.rs
  quadratic-core/src/values/cellvalue.rs
  quadratic-core/src/values/convert.rs
  quadratic-core/src/values/mod.rs
Labels: cla-signed, status: ready to merge, QA

#1945 fix: focus
  quadratic-client/src/app/gridGL/Events.tsx
  quadratic-client/src/app/ui/QuadraticUI.tsx
  quadratic-client/src/app/ui/components/Search.tsx
  quadratic-client/src/app/ui/menus/AIAssistant/AIAssistant.tsx
  quadratic-client/src/app/ui/menus/BottomBar/BottomBar.tsx
  quadratic-client/src/app/ui/menus/BottomBar/KernelMenu.tsx
  quadratic-client/src/app/ui/menus/BottomBar/PythonStateItem.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBar.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBarMenus/InsertMenubarMenu.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBarUsers.tsx
  quadratic-client/src/shared/shadcn/ui/menubar.tsx
Labels: cla-signed, status: ready to merge

#1953 fix: sheet gets stuck in pan mode
  quadratic-client/src/app/atoms/gridPanModeAtom.ts
  quadratic-client/src/app/atoms/gridSettingsAtom.ts
  quadratic-client/src/app/events/events.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorKeyboard.ts
  quadratic-client/src/app/gridGL/PixiAppEffects.tsx
  quadratic-client/src/app/gridGL/QuadraticGrid.tsx
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardPanMode.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/useKeyboard.ts
  quadratic-client/src/app/gridGL/interaction/pointer/Pointer.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerAutoComplete.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerCellMoving.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerDown.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerHeading.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiAppSettings.ts
Labels: cla-signed, status: ready for user test, QA

#1928 fix(manipulate-column-row): update offsets modified and fix auto row resize bug
  .vscode/settings.json
  package-lock.json
  quadratic-client/package.json
  quadratic-client/src/app/atoms/gridHeadingAtom.ts
  quadratic-client/src/app/events/events.ts
  quadratic-client/src/app/grid/controller/Sheets.ts
  quadratic-client/src/app/grid/sheet/Sheet.ts
  quadratic-client/src/app/gridGL/HTMLGrid/GridContextMenu.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/htmlCells/htmlCellsHandler.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
  quadratic-client/src/app/gridGL/UI/gridHeadings/GridHeadings.ts
  quadratic-client/src/app/gridGL/cells/CellsArray.ts
  quadratic-client/src/app/gridGL/cells/CellsFills.ts
  quadratic-client/src/app/gridGL/cells/CellsSheets.ts
  quadratic-client/src/app/gridGL/cells/borders/Borders.ts
  quadratic-client/src/app/gridGL/cells/cellsLabel/CellsLabels.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerHeading.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiAppSettings.ts
  quadratic-client/src/app/gridGL/pixiApp/Update.ts
  quadratic-client/src/app/quadratic-core-types/index.d.ts
  quadratic-client/src/app/web-workers/quadraticCore/coreClientMessages.ts
  quadratic-client/src/app/web-workers/quadraticCore/coreRenderMessages.ts
  quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreRender.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/rustCallbacks.ts
  quadratic-client/src/app/web-workers/renderWebWorker/renderClientMessages.ts
  quadratic-client/src/app/web-workers/renderWebWorker/renderWebWorker.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsLabels.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHash.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/renderCore.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/renderText.ts
  quadratic-client/src/shared/constants/gridConstants.ts
  quadratic-core/src/bin/export_types.rs
  quadratic-core/src/controller/active_transactions/pending_transaction.rs
  quadratic-core/src/controller/execution/auto_resize_row_heights.rs
  quadratic-core/src/controller/execution/control_transaction.rs
  quadratic-core/src/controller/execution/execute_operation/execute_col_rows.rs
  quadratic-core/src/controller/execution/execute_operation/execute_offsets.rs
  quadratic-core/src/controller/send_render.rs
  quadratic-core/src/controller/viewport.rs
  quadratic-core/src/grid/js_types.rs
  quadratic-core/src/grid/sheet/col_row/column.rs
  quadratic-core/src/grid/sheet/col_row/row.rs
  quadratic-core/src/pos.rs
  quadratic-core/src/sheet_offsets/sheet_offsets_wasm.rs
  quadratic-core/src/wasm_bindings/controller/sheet_offsets.rs
  quadratic-core/src/wasm_bindings/controller/transactions.rs
  quadratic-core/src/wasm_bindings/js.rs
Labels: cla-signed, QA

#1948 Border fixes
  quadratic-client/src/app/gridGL/HTMLGrid/validations/HtmlValidationList.tsx
  quadratic-core/src/controller/operations/borders.rs
  quadratic-core/src/grid/sheet/borders/borders_set.rs
  quadratic-core/src/grid/sheet/borders/borders_style.rs
  quadratic-core/src/grid/sheet/borders/borders_toggle.rs
  quadratic-core/src/grid/sheet/borders/mod.rs
  quadratic-core/src/grid/sheet/borders/sides.rs
  quadratic-core/src/selection.rs
Labels: cla-signed, status: ready for user test, QA

#1946 fix: toggle code editor
  quadratic-client/src/app/grid/actions/openCodeEditor.ts
  quadratic-client/src/app/gridGL/cells/CellsArray.ts
Labels: cla-signed, status: ready to merge

#1932 chore: add persistent live viewport buffer on grid controller
  quadratic-client/src/app/web-workers/quadraticCore/coreRenderMessages.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreRender.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/rustCallbacks.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsLabels.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/renderCore.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/renderText.ts
  quadratic-core/src/controller/active_transactions/pending_transaction.rs
  quadratic-core/src/controller/execution/control_transaction.rs
  quadratic-core/src/controller/execution/execute_operation/execute_borders.rs
  quadratic-core/src/controller/execution/execute_operation/execute_formats.rs
  quadratic-core/src/controller/execution/execute_operation/execute_values.rs
  quadratic-core/src/controller/execution/run_code/mod.rs
  quadratic-core/src/controller/mod.rs
  quadratic-core/src/controller/send_render.rs
  quadratic-core/src/controller/viewport.rs
  quadratic-core/src/grid/sheet/rendering.rs
  quadratic-core/src/viewport.rs
  quadratic-core/src/wasm_bindings/controller/mod.rs
  quadratic-core/src/wasm_bindings/js.rs
Labels: cla-signed, status: ready to merge, status: ready for user test

#1952 feat: new design + bug fixes for multiplayer avatars
  quadratic-client/src/app/gridGL/HTMLGrid/HTMLGridContainer.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/multiplayerCursor/multiplayerColors.ts
  quadratic-client/src/app/ui/QuadraticUI.tsx
  quadratic-client/src/app/ui/components/Following.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBarUsers.tsx
  quadratic-client/src/shared/components/Avatar.tsx
  quadratic-client/src/shared/components/Icons.tsx
Labels: cla-signed

#1947 fix: sheet bar dropdown
  quadratic-client/src/app/ui/menus/SheetBar/SheetBar.tsx
  quadratic-client/src/app/ui/menus/SheetBar/SheetBarTab.tsx
  quadratic-client/src/app/ui/menus/SheetBar/SheetBarTabContextMenu.tsx
  quadratic-client/src/app/ui/menus/SheetBar/SheetBarTabDropdownMenu.tsx
Labels: cla-signed, status: ready for code review, status: ready for user test

#1933 Add date & time formulas
  quadratic-core/src/bin/docgen.rs
  quadratic-core/src/formulas/functions/array.rs
  quadratic-core/src/formulas/functions/datetime.rs
  quadratic-core/src/formulas/functions/datetime_docs.md
  quadratic-core/src/formulas/functions/logic.rs
  quadratic-core/src/formulas/functions/logic_docs.md
  quadratic-core/src/formulas/functions/lookup.rs
  quadratic-core/src/formulas/functions/mathematics.rs
  quadratic-core/src/formulas/functions/mod.rs
  quadratic-core/src/formulas/functions/operators.rs
  quadratic-core/src/formulas/functions/statistics.rs
  quadratic-core/src/formulas/functions/string.rs
  quadratic-core/src/formulas/functions/tests.rs
  quadratic-core/src/formulas/functions/trigonometry.rs
  quadratic-core/src/values/time.rs
Labels: cla-signed, status: ready to merge, QA

#1958 fix: pressing the shift key closes the goto menu and custom date time input box
  quadratic-client/src/app/gridGL/Events.tsx
  quadratic-client/src/app/ui/menus/Toolbar/CursorPosition.tsx
  quadratic-client/src/app/ui/menus/Toolbar/FormattingBar.tsx
  quadratic-client/src/shared/shadcn/ui/command.tsx
  quadratic-client/src/shared/shadcn/ui/dialog.tsx
  quadratic-client/src/shared/shadcn/ui/popover.tsx
Labels: cla-signed, status: ready for user test, QA

#1960 Allows deleting of multiple columns and rows via multiselect
  quadratic-client/src/app/grid/sheet/SheetCursor.ts
  quadratic-core/src/controller/active_transactions/pending_transaction.rs
  quadratic-core/src/controller/execution/execute_operation/execute_offsets.rs
  quadratic-core/src/grid/bounds.rs
  quadratic-core/src/grid/sheet/col_row/column.rs
  quadratic-core/src/grid/sheet/col_row/row.rs
Labels: cla-signed, status: ready for user test, QA

#1964 fix: getting started buttons wrapping issues
  quadratic-client/src/dashboard/components/OnboardingBanner.tsx
Labels: cla-signed, status: ready for code review, status: ready for user test, QA

#1970 Theme picker recoil
  quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
  quadratic-client/src/app/ui/components/ThemePickerMenu.tsx
  quadratic-client/src/dashboard/components/DashboardSidebar.tsx
  quadratic-client/src/dashboard/components/Labs.tsx
  quadratic-client/src/router.tsx
  quadratic-client/src/routes/_root.tsx
  quadratic-client/src/routes/account.tsx
  quadratic-client/src/routes/labs.tsx
  quadratic-client/src/shared/atoms/featureFlags.ts
  quadratic-client/src/shared/atoms/themeAccentColor.ts
  quadratic-client/src/shared/atoms/themeAppearanceMode.ts
  quadratic-client/src/shared/components/Icons.tsx
  quadratic-client/src/shared/components/Theme.tsx
  quadratic-client/src/shared/components/ThemeAccentColors.tsx
  quadratic-client/src/shared/components/ThemeAppearanceModes.tsx
  quadratic-client/src/shared/constants/routes.ts
  quadratic-client/src/shared/shadcn/styles.css
  quadratic-client/src/shared/sharedEvents.ts
  quadratic-client/src/shared/utils/recoilHelpers.ts
Labels: cla-signed

#1971 table name
  quadratic-client/src/app/events/events.ts
  quadratic-client/src/app/gridGL/HTMLGrid/HTMLGridContainer.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/tablesOverlay/TablesOverlay.tsx
  quadratic-client/src/app/gridGL/cells/CellsArray.ts
  quadratic-client/src/app/gridGL/helpers/intersects.ts
  quadratic-client/src/app/gridGL/interaction/pointer/Pointer.ts
  quadratic-client/src/app/gridGL/interaction/pointer/pointerCursor.ts
  quadratic-client/src/app/quadratic-core-types/index.d.ts
  quadratic-core/src/grid/js_types.rs
  quadratic-core/src/grid/sheet/rendering.rs
  quadratic-rust-shared/src/auto_gen_path.rs
Labels: prototype

#1969 fix: prevent default paste on middle click in Linux
  quadratic-client/src/app/gridGL/interaction/pointer/Pointer.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerDown.ts
  quadratic-client/src/shared/utils/isLinux.ts
Labels: cla-signed, status: ready for user test, QA

#1967 fix: offline sync fieId
  quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
  quadratic-client/src/routes/file.$uuid.tsx
Labels: cla-signed, status: ready for user test, QA

#1966 fix(QA Wolf): Border formatting is not working as expected
  quadratic-client/src/app/gridGL/cells/borders/Borders.ts
Labels: cla-signed, status: ready for user test, QA

#1977 jim: csv delimiter tweaks
  quadratic-client/src/app/ui/components/ImportSettings.tsx
  quadratic-client/src/dashboard/components/ImportProgressList.tsx
Labels: cla-signed

#1980 feat: show logged in user context
  quadratic-client/src/dashboard/components/Empty.tsx
  quadratic-client/src/routes/_dashboard.tsx
  quadratic-client/src/routes/file.$uuid.tsx
Labels: cla-signed, status: ready to merge

#1981 chore: update dependencies
  Cargo.lock
  package-lock.json
  quadratic-client/package.json
  quadratic-rust-shared/Cargo.toml
  quadratic-rust-shared/src/sql/mssql_connection.rs
  quadratic-rust-shared/src/sql/mysql_connection.rs
Labels: cla-signed, status: ready for user test, dependencies

#1890 feat: labs page & theme picker
  quadratic-client/src/app/gridGL/UI/Cursor.ts
  quadratic-client/src/app/gridGL/UI/UICellMoving.ts
  quadratic-client/src/app/gridGL/UI/boxCells.ts
  quadratic-client/src/app/gridGL/UI/gridHeadings/GridHeadings.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
  quadratic-client/src/app/helpers/convertColor.ts
  quadratic-client/src/app/ui/QuadraticSidebar.tsx
  quadratic-client/src/app/ui/components/ThemePickerMenu.tsx
  quadratic-client/src/app/ui/components/borderMenuStyles.scss
  quadratic-client/src/app/ui/components/qColorPicker.scss
  quadratic-client/src/app/ui/menus/AIAssistant/AIAssistant.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorBody.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/ReturnTypeInspector.tsx
  quadratic-client/src/dashboard/components/AccountSection.tsx
  quadratic-client/src/dashboard/components/DashboardSidebar.tsx
  quadratic-client/src/dashboard/components/FilesListItem.tsx
  quadratic-client/src/index.css
  quadratic-client/src/router.tsx
  quadratic-client/src/routes/_dashboard.tsx
  quadratic-client/src/routes/_root.tsx
  quadratic-client/src/routes/account.tsx
  quadratic-client/src/routes/labs.tsx
  quadratic-client/src/shared/components/Icons.tsx
  quadratic-client/src/shared/components/MuiTheme.tsx
  quadratic-client/src/shared/components/ThemeAccentColors.tsx
  quadratic-client/src/shared/components/ThemeAppearanceModes.tsx
  quadratic-client/src/shared/constants/routes.ts
  quadratic-client/src/shared/hooks/useFeatureFlag.tsx
  quadratic-client/src/shared/hooks/useThemeAccentColor.tsx
  quadratic-client/src/shared/hooks/useThemeAppearanceMode.tsx
  quadratic-client/src/shared/shadcn/styles.css
  quadratic-client/src/shared/shadcn/ui/tooltip.tsx
  quadratic-client/src/shared/sharedEvents.ts
Labels: cla-signed, status: ready for code review

#1988 fix: optimistic UI when changing user role
  quadratic-client/src/shared/components/ShareDialog.tsx
Labels: cla-signed, status: ready for user test

#1974 QA: Oct 15th
  Cargo.lock
  package-lock.json
  quadratic-client/package.json
  quadratic-client/src/app/gridGL/UI/Cursor.ts
  quadratic-client/src/app/gridGL/UI/UICellMoving.ts
  quadratic-client/src/app/gridGL/UI/boxCells.ts
  quadratic-client/src/app/gridGL/UI/gridHeadings/GridHeadings.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
  quadratic-client/src/app/helpers/convertColor.ts
  quadratic-client/src/app/ui/QuadraticSidebar.tsx
  quadratic-client/src/app/ui/components/ThemePickerMenu.tsx
  quadratic-client/src/app/ui/components/borderMenuStyles.scss
  quadratic-client/src/app/ui/components/qColorPicker.scss
  quadratic-client/src/app/ui/menus/AIAssistant/AIAssistant.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorBody.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/ReturnTypeInspector.tsx
  quadratic-client/src/dashboard/components/AccountSection.tsx
  quadratic-client/src/dashboard/components/DashboardSidebar.tsx
  quadratic-client/src/dashboard/components/Empty.tsx
  quadratic-client/src/dashboard/components/FilesListItem.tsx
  quadratic-client/src/index.css
  quadratic-client/src/router.tsx
  quadratic-client/src/routes/_dashboard.tsx
  quadratic-client/src/routes/_root.tsx
  quadratic-client/src/routes/account.tsx
  quadratic-client/src/routes/file.$uuid.tsx
  quadratic-client/src/routes/labs.tsx
  quadratic-client/src/shared/components/Icons.tsx
  quadratic-client/src/shared/components/MuiTheme.tsx
  quadratic-client/src/shared/components/ShareDialog.tsx
  quadratic-client/src/shared/components/ThemeAccentColors.tsx
  quadratic-client/src/shared/components/ThemeAppearanceModes.tsx
  quadratic-client/src/shared/constants/routes.ts
  quadratic-client/src/shared/hooks/useFeatureFlag.tsx
  quadratic-client/src/shared/hooks/useThemeAccentColor.tsx
  quadratic-client/src/shared/hooks/useThemeAppearanceMode.tsx
  quadratic-client/src/shared/shadcn/styles.css
  quadratic-client/src/shared/shadcn/ui/tooltip.tsx
  quadratic-client/src/shared/sharedEvents.ts
  quadratic-rust-shared/Cargo.toml
  quadratic-rust-shared/src/sql/mssql_connection.rs
  quadratic-rust-shared/src/sql/mysql_connection.rs
Labels: cla-signed

#2000 feat: dashboard design tweaks
  quadratic-client/src/dashboard/components/DashboardSidebar.tsx
  quadratic-client/src/dashboard/components/TeamSwitcher.tsx
  quadratic-client/src/shared/components/Icons.tsx
Labels: cla-signed

#2005 fix: support theming in app bar
  quadratic-client/src/shared/hooks/useThemeAppearanceMode.tsx
  quadratic-client/src/shared/utils/colors.ts
Labels: cla-signed, status: ready for code review, status: ready for user test
