Repository quadratichq/quadratic, pull requests merged in 2024-05, with the labels that each got.

#1330 mixpanel cross marketing site
  quadratic-client/src/shared/utils/analytics.ts
Labels: cla-signed

#1333 fix: border offset
  quadratic-client/src/routes/files.tsx
Labels: cla-signed, status: ready for review

#1335 Dependabot/npm and yarn/quadratic client/decode uri component 0.2.2
  quadratic-client/package-lock.json
Labels: cla-signed

#1332 Drag cells to move
  quadratic-client/src/app/events/events.ts
  quadratic-client/src/app/gridGL/UI/Cursor.ts
  quadratic-client/src/app/gridGL/UI/UICellMoving.ts
  quadratic-client/src/app/gridGL/interaction/pointer/Pointer.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerCellMoving.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
  quadratic-client/src/app/gridGL/pixiApp/Update.ts
  quadratic-client/src/app/helpers/parseEditorPythonCell.ts
  quadratic-client/src/app/quadratic-core-types/index.d.ts
  quadratic-client/src/app/theme/colors.ts
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditor.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorBody.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/useEditorCellHighlights.ts
  quadratic-client/src/app/ui/menus/ContextMenu/FloatingContextMenu.tsx
  quadratic-client/src/app/web-workers/quadraticCore/coreClientMessages.ts
  quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
  quadratic-core/src/bin/export_types.rs
  quadratic-core/src/controller/active_transactions/pending_transaction.rs
  quadratic-core/src/controller/active_transactions/transaction_name.rs
  quadratic-core/src/controller/execution/execute_operation/execute_move_cells.rs
  quadratic-core/src/controller/execution/execute_operation/execute_sheets.rs
  quadratic-core/src/controller/execution/execute_operation/mod.rs
  quadratic-core/src/controller/operations/clipboard.rs
  quadratic-core/src/controller/operations/operation.rs
  quadratic-core/src/controller/user_actions/clipboard.rs
  quadratic-core/src/formulas/tests.rs
  quadratic-core/src/grid/series.rs
  quadratic-core/src/wasm_bindings/controller/clipboard.rs
Labels: cla-signed, status: ready for review

#1339 bug: Auto Resize Column
  quadratic-client/src/app/actions.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerHeading.ts
  quadratic-client/src/app/ui/menus/CommandPalette/CommandPalette.tsx
  quadratic-client/src/app/ui/menus/CommandPalette/commands/ColumnRow.tsx
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
  quadratic-client/src/app/web-workers/renderWebWorker/renderWebWorker.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsLabels.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/renderClient.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/renderCore.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/renderText.ts
  quadratic-core/src/controller/execution/execute_operation/execute_offsets.rs
Labels: cla-signed, status: ready for review

#1352 Remove Old Discord from Readme
  README.md
Labels: cla-signed

#1345 Improvements to floating menu
  quadratic-client/src/app/gridGL/UI/Cursor.ts
  quadratic-client/src/app/ui/menus/ContextMenu/FloatingContextMenu.tsx
Labels: cla-signed, status: ready for review

#1281 Url params
  quadratic-client/src/app/debugFlags.ts
  quadratic-client/src/app/events/events.ts
  quadratic-client/src/app/grid/controller/Sheets.ts
  quadratic-client/src/app/gridGL/interaction/viewportHelper.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
  quadratic-client/src/app/gridGL/pixiApp/Viewport.ts
  quadratic-client/src/app/gridGL/pixiApp/urlParams/UrlParamsDev.ts
  quadratic-client/src/app/gridGL/pixiApp/urlParams/UrlParamsUser.ts
  quadratic-client/src/app/gridGL/pixiApp/urlParams/urlParams.ts
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditor.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBarUsers.tsx
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayer.ts
  quadratic-client/src/shared/components/ShareDialog.tsx
Labels: cla-signed, status: ready for review

#1334 Code editor paneling
  quadratic-client/src/app/gridGL/QuadraticGrid.tsx
  quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
  quadratic-client/src/app/ui/QuadraticUI.tsx
  quadratic-client/src/app/ui/components/FileUploadWrapper.tsx
  quadratic-client/src/app/ui/components/Search.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditor.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorPanels.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/Console.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/ResizeControl.css
  quadratic-client/src/app/ui/menus/CodeEditor/useCodeEditorPanelData.ts
  quadratic-client/src/app/ui/menus/TopBar/TopBar.tsx
Labels: cla-signed, status: ready for review

#1353 Update .clabot
  .clabot
Labels: cla-signed

#1356 Dependabot Fixes
  package-lock.json
  quadratic-api/package.json
Labels: cla-signed, security

#1361 Fix "Create Team" button
  quadratic-client/src/routes/_dashboard.tsx
Labels: cla-signed

#1358 update port type
  quadratic-client/src/app/ui/connections/ConnectionFormPostgres.tsx
  quadratic-shared/typesAndSchemasConnections.ts
Labels: cla-signed

#1346 feat: multiline ai assist prompts
  quadratic-client/src/app/ui/menus/CodeEditor/AICodeBlockParser.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/AiAssistant.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/Console.tsx
  quadratic-client/src/shared/shadcn/ui/textarea.tsx
Labels: cla-signed

#1316 Inline formula
  README.md
  quadratic-client/src/app/atoms/editorInteractionStateAtom.ts
  quadratic-client/src/app/events/events.ts
  quadratic-client/src/app/grid/controller/Sheets.ts
  quadratic-client/src/app/grid/sheet/SheetCursor.ts
  quadratic-client/src/app/gridGL/HTMLGrid/CellInput.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/CodeHint.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/HTMLGridContainer.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/hoverCell/HoverCell.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/InlineEditor.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorFormula.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorKeyboard.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorMonaco.ts
  quadratic-client/src/app/gridGL/UI/Cursor.ts
  quadratic-client/src/app/gridGL/UI/cellHighlights/CellHighlights.ts
  quadratic-client/src/app/gridGL/UI/cellHighlights/cellHighlightsDraw.ts
  quadratic-client/src/app/gridGL/UI/gridHeadings/getA1Notation.ts
  quadratic-client/src/app/gridGL/UI/gridHeadings/tests/getA1Notation.test.ts
  quadratic-client/src/app/gridGL/cells/CellsArray.ts
  quadratic-client/src/app/gridGL/dashedTextures.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardCell.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardCellChars.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardPosition.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/useKeyboard.ts
  quadratic-client/src/app/gridGL/interaction/pointer/Pointer.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerDown.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerHeading.ts
  quadratic-client/src/app/gridGL/interaction/pointer/doubleClickCell.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiAppSettings.ts
  quadratic-client/src/app/gridGL/pixiApp/Update.ts
  quadratic-client/src/app/gridGL/pixiApp/highlightedCells.ts
  quadratic-client/src/app/helpers/convertColor.ts
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditor.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/useEditorCellHighlights.ts
  quadratic-client/src/app/ui/menus/CodeEditor/useEditorOnSelectionChange.ts
  quadratic-client/src/app/ui/menus/ContextMenu/FloatingContextMenu.tsx
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayer.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayerTypes.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/worker/multiplayerServer.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/offline.ts
  quadratic-core/src/controller/execution/run_code/run_formula.rs
  quadratic-core/src/formulas/ast.rs
  quadratic-core/src/formulas/functions/logic.rs
  quadratic-core/src/formulas/functions/lookup.rs
  quadratic-core/src/formulas/functions/macros.rs
  quadratic-core/src/formulas/functions/mathematics.rs
  quadratic-core/src/formulas/functions/mod.rs
  quadratic-core/src/formulas/functions/statistics.rs
  quadratic-core/src/formulas/mod.rs
  quadratic-core/src/formulas/parser/mod.rs
  quadratic-core/src/formulas/tests.rs
  quadratic-multiplayer/src/message/mod.rs
  quadratic-multiplayer/src/state/user.rs
  quadratic-rust-client/src/lib.rs
  quadratic-rust-client/src/parse_formula.rs
Labels: cla-signed, status: ready for review

#1367 make sure instance is launched with the correct subnet
  infra/multiplayer/multiplayer.ts
Labels: cla-signed

#1368 trigger prod deployment on merge
  .github/workflows/production-deploy.yml
Labels: cla-signed

#1370 Collect schema vec
  quadratic-connection/src/sql/mysql.rs
  quadratic-connection/src/sql/postgres.rs
Labels: cla-signed

#1342 fix: ctrl+b shortcut should not trigger browser native actions
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardViewport.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/useKeyboard.ts
Labels: cla-signed, status: ready for review

#1372 Fixes bug with expand formula button appearing for non-formulas
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
  quadratic-kernels/python-wasm/poetry.lock
Labels: cla-signed, status: ready for review

#1376 fix bug with python cell references and sheet id
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
  quadratic-client/src/app/gridGL/UI/cellHighlights/CellHighlights.ts
  quadratic-client/src/app/gridGL/pixiApp/urlParams/UrlParamsDev.ts
  quadratic-client/src/app/helpers/formulaNotation.ts
  quadratic-client/src/app/helpers/parseEditorPythonCell.ts
  quadratic-client/src/app/ui/menus/CodeEditor/useEditorCellHighlights.ts
  quadratic-kernels/python-wasm/poetry.lock
Labels: cla-signed

#1278 Truncate redis streams
  .github/workflows/preview-branches.yml
  Cargo.lock
  infra/helpers/isPreviewEnvironment.ts
  infra/shared/securityGroups.ts
  quadratic-client/src/app/events/events.ts
  quadratic-client/src/app/ui/UpdateAlertVersion.tsx
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayer.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayerClientMessages.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayerTypes.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/worker/multiplayerClient.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/worker/multiplayerServer.ts
  quadratic-files/.env.docker
  quadratic-files/.env.example
  quadratic-files/.env.test
  quadratic-files/src/config.rs
  quadratic-files/src/error.rs
  quadratic-files/src/file.rs
  quadratic-files/src/main.rs
  quadratic-files/src/server.rs
  quadratic-files/src/state/settings.rs
  quadratic-files/src/state/stats.rs
  quadratic-files/src/truncate.rs
  quadratic-multiplayer/src/error.rs
  quadratic-multiplayer/src/message/handle.rs
  quadratic-multiplayer/src/server.rs
  quadratic-multiplayer/src/state/pubsub.rs
  quadratic-multiplayer/src/state/room.rs
  quadratic-rust-shared/src/pubsub/mod.rs
  quadratic-rust-shared/src/pubsub/redis.rs
  quadratic-rust-shared/src/pubsub/redis_streams.rs
Labels: cla-signed, status: ready for review

#1378 tab/shift+tab support for inline editor
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorKeyboard.ts
Labels: cla-signed

#1347 fix: inequality comparison issue using <>
  quadratic-core/src/formulas/lexer.rs
Labels: cla-signed, status: ready to merge

#1382 fix: meta+shift+select is off by 1
  quadratic-core/src/grid/sheet/bounds.rs
Labels: cla-signed

#1380 Next Connection Infra
  infra/connection/connection.ts
  package-lock.json
Labels: cla-signed

#1386 Canvas maintains focus when pressing tab button in formula editor
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorKeyboard.ts
Labels: cla-signed, status: ready for review

#1348 fix: clear history stack in the code editor when cell location changes
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditor.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorBody.tsx
Labels: cla-signed, status: ready to merge

#1390 Fixes inline editor when resizing columns
  quadratic-client/src/app/events/events.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerHeading.ts
Labels: cla-signed

#1392 Code Editor doesn't clear undo stack unless CellLocation really changed
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorBody.tsx
Labels: cla-signed

#1349 feat: support copy-paste to google sheets / excel with formatting
  quadratic-core/src/color.rs
  quadratic-core/src/controller/user_actions/clipboard.rs
  quadratic-core/src/grid/borders/style.rs
  quadratic-core/src/grid/formatting.rs
Labels: cla-signed, status: ready to merge

#1381 feat: toggle borders
  quadratic-core/src/controller/operations/borders.rs
  quadratic-core/src/controller/user_actions/borders.rs
  quadratic-core/src/grid/borders/sheet.rs
Labels: cla-signed, status: ready to merge

#1398 prevent submit on shift and control
  quadratic-client/src/app/ui/menus/CodeEditor/AiAssistant.tsx
Labels: cla-signed
