Repository quadratichq/quadratic, pull requests merged in 2025-07, with the labels that each got.

#3158 fix: revert growable SharedArrayBuffer
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascript.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascriptRunnerMessages.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/generateJavascriptForRunner.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/generatedJavascriptForEditor.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/javascriptLibrary.ts
  quadratic-client/src/app/web-workers/pythonWebWorker/pythonCoreMessages.ts
  quadratic-client/src/app/web-workers/pythonWebWorker/worker/pythonCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/corePython.ts
  quadratic-client/src/routes/file.$uuid.tsx
Labels: cla-signed, status: ready for code review, status: ready for user test, QA

#3161 Pressing tab on suggestion list moves right instead of down
  quadratic-client/src/app/gridGL/HTMLGrid/SuggestionDropdown.tsx
  test/e2e/src/spreadsheetComputation.spec.ts
Labels: cla-signed, status: ready to merge, QA

#3162 Fix bug with moving table and highlighting table
  quadratic-client/src/app/gridGL/cells/tables/Tables.ts
  quadratic-client/src/app/gridGL/cells/tables/TablesCache.ts
  quadratic-core/src/controller/send_render.rs
Labels: cla-signed, status: ready for user test, QA

#3160 Fix right-click for code tables
  quadratic-client/src/app/gridGL/cells/tables/TableColumnHeader.ts
  quadratic-client/src/app/gridGL/cells/tables/TableColumnHeaders.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerDown.ts
  test/e2e/src/helpers/query.helper.ts
Labels: cla-signed, status: ready to merge, QA

#3165 fix: copyAsPng bug
  quadratic-client/src/app/gridGL/UI/HtmlPlaceholders.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
  quadratic-client/src/app/gridGL/pixiApp/copyAsPNG.ts
  quadratic-client/src/app/gridGL/pixiApp/thumbnail.ts
Labels: cla-signed, status: ready to merge

#3153 infra: add db in pulumi infra
  .vscode/settings.json
  infra/api/api.ts
  infra/api/api_network.ts
  infra/connection/connection_network.ts
  infra/db/db.ts
  infra/db/migrate.sh
  infra/iam/github-actions.json
  infra/iam/infra-<stack>-1.json
  infra/iam/infra-<stack>-2.json
  infra/iam/s3bucketsclientdeploymenttocloudflare.json
  quadratic-api/src/routes/v0/ai.chat.POST.ts
Labels: cla-signed, status: ready for code review

#3182 Fixes placement of table headers when generating thumbnail
  quadratic-client/src/app/gridGL/cells/tables/Tables.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
  quadratic-client/src/app/gridGL/pixiApp/thumbnail.ts
Labels: cla-signed, status: ready to merge, QA

#3181 Ensures GridSettings are loaded before app starts
  quadratic-client/src/app/gridGL/pixiApp/PixiAppSettings.ts
  quadratic-client/src/app/ui/QuadraticApp.tsx
Labels: cla-signed, status: ready to merge, QA

#3172 Fix snowflake in production
  quadratic-connection/Cargo.toml
  quadratic-connection/src/sql/snowflake.rs
  quadratic-rust-shared/Cargo.toml
  quadratic-rust-shared/package.json
  quadratic-rust-shared/src/lib.rs
  quadratic-rust-shared/src/sql/cockroachdb_connection.rs
  quadratic-rust-shared/src/sql/mysql_connection.rs
  quadratic-rust-shared/src/sql/snowflake_connection.rs
  quadratic-rust-shared/src/test/mod.rs
Labels: cla-signed, status: ready to merge, QA

#3177 handle user-inputted percent number
  Cargo.toml
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-client/src/app/gridGL/interaction/pointer/doubleClickCell.ts
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-core/src/controller/execution/auto_resize_row_heights.rs
  quadratic-core/src/controller/execution/execute_operation/execute_values.rs
  quadratic-core/src/controller/execution/execute_operation/mod.rs
  quadratic-core/src/controller/operations/cell_value.rs
  quadratic-core/src/controller/user_actions/cells.rs
  quadratic-core/src/controller/user_actions/formats.rs
  quadratic-core/src/formulas/functions/trigonometry.rs
  quadratic-core/src/grid/formatting.rs
  quadratic-core/src/grid/sheet.rs
  quadratic-core/src/values/cellvalue.rs
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: cla-signed, status: ready to merge, QA

#3190 chore: upgrade vite to v7
  quadratic-client/package.json
Labels: cla-signed, status: ready for code review

#3202 chore: add open router
  .env.docker
  .vscode/settings.json
  docker-compose.yml
  infra/aws-cloudformation/quadratic-preview.yml
  quadratic-api/.env.example
  quadratic-api/src/ai/handler/ai.handler.ts
  quadratic-api/src/ai/handler/bedrock.handler.ts
  quadratic-api/src/ai/handler/genai.handler.ts
  quadratic-api/src/ai/handler/openai.handler.ts
  quadratic-api/src/ai/helpers/openai.helper.ts
  quadratic-api/src/ai/providers.ts
  quadratic-api/src/env-vars.ts
  quadratic-client/src/app/ai/toolCards/SetCellValues.tsx
  quadratic-shared/ai/helpers/model.helper.ts
  quadratic-shared/ai/models/AI_MODELS.ts
  quadratic-shared/typesAndSchemasAI.ts
Labels: cla-signed

#3205 fix: arrow keys in new sheet
  quadratic-core/src/controller/send_render.rs
Labels: cla-signed, status: ready to merge

#3211 fix: ai analytics logging, include system prompt
  quadratic-api/src/ai/handler/ai.handler.ts
  quadratic-api/src/routes/v0/ai.chat.POST.ts
Labels: cla-signed, status: ready to merge

#3193 chore: remove heroku stream hack for pdf import
  quadratic-api/src/ai/handler/genai.handler.ts
  quadratic-client/src/app/ui/menus/AIAnalyst/hooks/useAnalystPDFImport.tsx
Labels: cla-signed, status: ready to merge, QA

#3218 chore: add baseten
  .env.docker
  .vscode/settings.json
  docker-compose.yml
  infra/aws-cloudformation/quadratic-preview.yml
  quadratic-api/.env.example
  quadratic-api/src/ai/handler/ai.handler.ts
  quadratic-api/src/ai/handler/openai.handler.ts
  quadratic-api/src/ai/helpers/openai.helper.ts
  quadratic-api/src/ai/providers.ts
  quadratic-api/src/env-vars.ts
  quadratic-shared/ai/helpers/model.helper.ts
  quadratic-shared/ai/models/AI_MODELS.ts
  quadratic-shared/typesAndSchemasAI.ts
Labels: cla-signed, status: ready to merge, QA

#3214 infra: add bastion host for db access (ssh tunnel)
  infra/db/bastian.ts
  infra/db/db.ts
  infra/iam/infra-<stack>-1.json
Labels: cla-signed, status: ready to merge, QA

#3212 chore: add azure openai
  .env.docker
  docker-compose.yml
  infra/aws-cloudformation/quadratic-preview.yml
  quadratic-api/.env.example
  quadratic-api/src/ai/handler/ai.handler.ts
  quadratic-api/src/ai/handler/openai.handler.ts
  quadratic-api/src/ai/helpers/openai.helper.ts
  quadratic-api/src/ai/providers.ts
  quadratic-api/src/env-vars.ts
  quadratic-shared/ai/helpers/model.helper.ts
  quadratic-shared/ai/models/AI_MODELS.ts
  quadratic-shared/ai/specs/aiToolsSpec.ts
  quadratic-shared/typesAndSchemasAI.ts
Labels: cla-signed, status: ready to merge, QA

#3227 Adds `flex` to debugging menu
  quadratic-client/src/app/ui/QuadraticAppDebugSettings.tsx
Labels: cla-signed, status: ready for code review

#3230 Fixes subtle bug with autocomplete
  quadratic-client/src/app/gridGL/HTMLGrid/SuggestionDropdown.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorKeyboard.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorMonaco.ts
Labels: cla-signed, status: ready to merge, QA

#3248 Fix core error after getRenderCells
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreRender.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/renderCore.ts
  quadratic-core/src/wasm_bindings/controller/render.rs
  quadratic-rust-shared/Cargo.toml
Labels: cla-signed, status: ready for user test, QA

#3240 QA July 17th
  Cargo.toml
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-api/src/ai/handler/ai.handler.ts
  quadratic-api/src/ai/helpers/modelRouter.helper.ts
  quadratic-api/src/app.ts
  quadratic-api/src/auth/auth0.ts
  quadratic-api/src/auth/ory.ts
  quadratic-api/src/data/connections.ts
  quadratic-api/src/env-vars.ts
  quadratic-api/src/licenseClient.ts
  quadratic-api/src/middleware/logRequestInfo.ts
  quadratic-api/src/middleware/validateRequestSchema.ts
  quadratic-api/src/routes/v0/ai.chat.POST.ts
  quadratic-api/src/routes/v0/examples.POST.ts
  quadratic-api/src/routes/v0/feedback.POST.ts
  quadratic-api/src/routes/v0/files.$uuid.thumbnail.POST.ts
  quadratic-api/src/routes/v0/files.GET.ts
  quadratic-api/src/routes/v0/webhooks.stripe.POST.ts
  quadratic-api/src/server.ts
  quadratic-api/src/storage/fileSystem.ts
  quadratic-api/src/stripe/stripe.ts
  quadratic-api/src/utils/crypto.ts
  quadratic-api/src/utils/permissions.ts
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreRender.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/renderCore.ts
  quadratic-client/src/shared/components/EmptyPage.tsx
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-core/src/wasm_bindings/controller/render.rs
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/ai/specs/aiToolsSpec.ts
  quadratic-shared/package.json
Labels: cla-signed

#3273 fix: auto resize doesn't apply correctly to chart
  quadratic-client/src/app/events/events.ts
  quadratic-client/src/app/grid/controller/Sheets.ts
  quadratic-client/src/app/gridGL/HTMLGrid/htmlCells/htmlCellsHandler.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
  quadratic-client/src/app/gridGL/HTMLGrid/validations/useHtmlValidations.ts
  quadratic-client/src/app/gridGL/UI/UISingleCellOutlines.ts
  quadratic-client/src/app/gridGL/UI/cellHighlights/CellHighlights.ts
  quadratic-client/src/app/gridGL/cells/Borders.ts
  quadratic-client/src/app/gridGL/cells/CellsArray.ts
  quadratic-client/src/app/gridGL/cells/CellsFills.ts
  quadratic-client/src/app/gridGL/cells/cellsImages/CellsImages.ts
  quadratic-client/src/app/gridGL/cells/tables/Tables.ts
Labels: cla-signed, status: ready to merge, QA, e2e

#3272 fix: underline underlines empty cells in tables
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts
Labels: cla-signed, status: ready to merge, QA

#3274 fix format summary behind tables
  quadratic-core/src/controller/user_actions/formats.rs
  quadratic-core/src/grid/sheet/format_summary.rs
  quadratic-core/src/wasm_bindings/controller/formatting.rs
Labels: cla-signed, status: ready to merge, QA, e2e

#3241 Quad-mini
  Cargo.toml
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-api/src/ai/helpers/modelRouter.helper.ts
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-client/src/app/ai/components/SelectAIModelMenu.tsx
  quadratic-client/src/app/ai/hooks/useAIModel.tsx
  quadratic-client/src/app/atoms/aiAnalystAtom.ts
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystMessages.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/hooks/useSubmitAIAnalystPrompt.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/hooks/useSubmitAIAssistantPrompt.tsx
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/ai/models/AI_MODELS.ts
  quadratic-shared/ai/specs/aiToolsSpec.ts
  quadratic-shared/package.json
  quadratic-shared/typesAndSchemasAI.ts
Labels: cla-signed, status: ready for code review, status: ready for user test, QA

#3268 fix: can't copy table column data to another table column
  quadratic-core/src/a1/a1_selection/intersects.rs
  quadratic-core/src/a1/table_ref/query.rs
  quadratic-core/src/controller/execution/execute_operation/execute_data_table.rs
  quadratic-core/src/controller/operations/cell_value.rs
  quadratic-core/src/controller/operations/clipboard.rs
  quadratic-core/src/controller/operations/code_cell.rs
  quadratic-core/src/controller/operations/data_table.rs
  quadratic-core/src/controller/user_actions/clipboard.rs
  quadratic-core/src/grid/data_table/column.rs
  quadratic-core/src/grid/data_table/column_header.rs
  quadratic-core/src/grid/data_table/fix_names.rs
  quadratic-core/src/grid/data_table/mod.rs
Labels: cla-signed, status: ready to merge, QA, e2e

#3282 Fix hard-coded biqquery dataset in Query Selected Table
  quadratic-rust-shared/src/sql/bigquery_connection.rs
Labels: cla-signed, status: ready to merge, QA

#3276 fix: drag and drop AI Chat image/pdf indicator persists
  quadratic-client/src/app/ui/components/AIUserMessageForm.tsx
Labels: cla-signed, status: ready to merge, QA

#3287 fix(main): image not supported by quad-mini model
  Cargo.toml
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-api/src/ai/handler/ai.handler.ts
  quadratic-api/src/ai/handler/openai.handler.ts
  quadratic-api/src/ai/helpers/fineTuning.helper.ts
  quadratic-api/src/ai/helpers/modelRouter.helper.ts
  quadratic-api/src/ai/helpers/openai.helper.ts
  quadratic-api/src/app.ts
  quadratic-api/src/auth/auth0.ts
  quadratic-api/src/auth/ory.ts
  quadratic-api/src/data/connections.ts
  quadratic-api/src/licenseClient.ts
  quadratic-api/src/middleware/logRequestInfo.ts
  quadratic-api/src/middleware/validateRequestSchema.ts
  quadratic-api/src/routes/v0/ai.chat.POST.ts
  quadratic-api/src/routes/v0/examples.POST.ts
  quadratic-api/src/routes/v0/feedback.POST.ts
  quadratic-api/src/routes/v0/webhooks.stripe.POST.ts
  quadratic-api/src/server.ts
  quadratic-api/src/storage/fileSystem.ts
  quadratic-api/src/stripe/stripe.ts
  quadratic-api/src/utils/crypto.ts
  quadratic-api/src/utils/permissions.ts
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-client/src/app/ai/hooks/useAIRequestToAPI.tsx
  quadratic-client/src/app/ui/components/AIContext.tsx
  quadratic-client/src/app/ui/components/AIUserMessageForm.tsx
  quadratic-client/src/app/ui/components/AIUserMessageFormAttachFileButton.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystMessages.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystUserMessageForm.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/hooks/useSubmitAIAnalystPrompt.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/hooks/useSubmitAIAssistantPrompt.tsx
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/ai/helpers/message.helper.ts
  quadratic-shared/ai/helpers/model.helper.ts
  quadratic-shared/ai/models/AI_MODELS.ts
  quadratic-shared/package.json
  quadratic-shared/typesAndSchemas.ts
  quadratic-shared/typesAndSchemasAI.ts
Labels: cla-signed, status: ready to merge

#3263 fix: move table from top most edge copies table contents instead of moving
  quadratic-client/src/app/gridGL/interaction/pointer/PointerCellMoving.ts
Labels: cla-signed, status: ready for code review, QA, e2e

#3257 fix: spill outlines not drawing
  quadratic-client/src/app/gridGL/cells/tables/Table.ts
  quadratic-client/src/app/gridGL/interaction/pointer/pointerCursor.ts
  quadratic-core/src/a1/a1_context/table_map.rs
  quadratic-core/src/a1/a1_selection/query.rs
  quadratic-core/src/grid/contiguous/contiguous_2d.rs
  quadratic-core/src/grid/sheet/data_tables/cache.rs
Labels: cla-signed, status: ready to merge, QA, e2e

#3266 fix: mixpanel core errors
  quadratic-client/src/app/ai/tools/aiToolsActions.ts
  quadratic-client/src/app/ui/QuadraticApp.tsx
  quadratic-client/src/app/ui/components/FixSpillError.tsx
  quadratic-client/src/app/ui/menus/Toolbar/FormattingBar/FormattingBar.tsx
  quadratic-client/src/app/web-workers/javascriptWebWorker/javascriptWebWorker.ts
  quadratic-client/src/app/web-workers/pythonWebWorker/pythonWebWorker.ts
  quadratic-client/src/app/web-workers/quadraticCore/coreClientMessages.ts
  quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreMultiplayer.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/corePython.ts
  quadratic-client/src/app/web-workers/workers.ts
  quadratic-core/src/grid/js_types.rs
  quadratic-core/src/util.rs
  quadratic-core/src/wasm_bindings/controller/cells.rs
  quadratic-core/src/wasm_bindings/controller/clipboard.rs
  quadratic-core/src/wasm_bindings/controller/code.rs
  quadratic-core/src/wasm_bindings/controller/data_table.rs
  quadratic-core/src/wasm_bindings/controller/formatting.rs
  quadratic-core/src/wasm_bindings/controller/import.rs
  quadratic-core/src/wasm_bindings/controller/render.rs
  quadratic-core/src/wasm_bindings/controller/search.rs
  quadratic-core/src/wasm_bindings/controller/transactions.rs
  quadratic-core/src/wasm_bindings/mod.rs
Labels: cla-signed, status: ready to merge, QA

#3295 fix: inserting columns can create duplicate table column names
  quadratic-core/src/controller/execution/execute_operation/execute_data_table.rs
  quadratic-core/src/grid/data_table/column.rs
  quadratic-core/src/grid/data_table/column_header.rs
Labels: cla-signed, status: ready to merge, QA

#3298 fix: table selection highlighting bug
  quadratic-core/src/a1/table_ref/query.rs
Labels: cla-signed, status: ready to merge, QA

#3296 fix: when deleting many table rows, header UI persists at bottom of table
  quadratic-client/src/app/gridGL/cells/tables/Table.ts
Labels: cla-signed, status: ready to merge, QA, e2e

#3297 fix: when pasting values only for an entire table, convert multi-line cell values to space separated ones
  quadratic-core/src/controller/operations/clipboard.rs
Labels: cla-signed, status: ready to merge, QA

#3231 AI fix spill error
  quadratic-api/src/ai/docs/QuadraticDocs.ts
  quadratic-client/src/app/ai/components/SelectAIModelMenu.tsx
  quadratic-client/src/app/ai/hooks/useTablesContextMessages.tsx
  quadratic-client/src/app/ai/toolCards/AIToolCard.tsx
  quadratic-client/src/app/ai/toolCards/HasCellData.tsx
  quadratic-client/src/app/ai/toolCards/TextSearch.tsx
  quadratic-client/src/app/ai/toolCards/UpdateCodeCell.tsx
  quadratic-client/src/app/ai/tools/aiToolsActions.ts
  quadratic-client/src/app/debugFlags/debugFlagsDefinitions.ts
  quadratic-client/src/app/quadratic-core-types/index.d.ts
  quadratic-client/src/app/web-workers/quadraticCore/coreClientMessages.ts
  quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
  quadratic-core/src/grid/js_types.rs
  quadratic-core/src/grid/sheet.rs
  quadratic-core/src/grid/sheet/ai_context.rs
  quadratic-core/src/grid/sheet/cell_values.rs
  quadratic-core/src/grid/sheet/content.rs
  quadratic-core/src/wasm_bindings/controller/cells.rs
  quadratic-shared/ai/specs/aiToolsSpec.ts
Labels: cla-signed, status: ready for code review

#3255 Ai rerun code tool
  quadratic-api/src/ai/helpers/anthropic.helper.ts
  quadratic-api/src/ai/helpers/bedrock.helper.ts
  quadratic-api/src/ai/helpers/genai.helper.ts
  quadratic-client/src/app/ai/toolCards/AIToolCard.tsx
  quadratic-client/src/app/ai/toolCards/AIToolCardEditable.tsx
  quadratic-client/src/app/ai/toolCards/RerunCode.tsx
  quadratic-client/src/app/ai/tools/aiToolsActions.ts
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystHeader.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/hooks/useAnalystPDFImport.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/hooks/useSubmitAIAnalystPrompt.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/hooks/useSubmitAIAssistantPrompt.tsx
  quadratic-client/src/app/web-workers/quadraticCore/coreClientMessages.ts
  quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
  quadratic-core/src/wasm_bindings/controller/code.rs
  quadratic-shared/ai/specs/aiToolsSpec.ts
Labels: cla-signed, status: ready to merge

#3259 AI tools to resize columns and rows
  quadratic-client/src/app/ai/toolCards/AIToolCard.tsx
  quadratic-client/src/app/ai/toolCards/ColorSheets.tsx
  quadratic-client/src/app/ai/toolCards/GetCellData.tsx
  quadratic-client/src/app/ai/toolCards/GetTextFormats.tsx
  quadratic-client/src/app/ai/toolCards/ResizeColumns.tsx
  quadratic-client/src/app/ai/toolCards/ResizeRows.tsx
  quadratic-client/src/app/ai/tools/aiToolsActions.ts
  quadratic-client/src/app/web-workers/quadraticCore/coreClientMessages.ts
  quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
  quadratic-core/src/wasm_bindings/controller/sheet_offsets.rs
  quadratic-shared/ai/specs/aiToolsSpec.ts
Labels: cla-signed, status: ready to merge

#3290 Ai insert and delete columns and rows
  quadratic-client/src/app/ai/toolCards/AIToolCard.tsx
  quadratic-client/src/app/ai/toolCards/DeleteColumns.tsx
  quadratic-client/src/app/ai/toolCards/DeleteRows.tsx
  quadratic-client/src/app/ai/toolCards/InsertColumns.tsx
  quadratic-client/src/app/ai/toolCards/InsertRows.tsx
  quadratic-client/src/app/ai/tools/aiToolsActions.ts
  quadratic-client/src/app/web-workers/quadraticCore/coreClientMessages.ts
  quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
  quadratic-core/src/wasm_bindings/a1.rs
  quadratic-core/src/wasm_bindings/controller/col_row.rs
  quadratic-shared/ai/specs/aiToolsSpec.ts
Labels: cla-signed, status: ready to merge

#3302 AI Tool: Data Table meta
  quadratic-client/src/app/actions/codeActionsSpec.ts
  quadratic-client/src/app/actions/columnRowSpec.ts
  quadratic-client/src/app/actions/dataTableSpec.ts
  quadratic-client/src/app/ai/toolCards/AIToolCard.tsx
  quadratic-client/src/app/ai/toolCards/SetCodeCellValue.tsx
  quadratic-client/src/app/ai/toolCards/TableColumnSettings.tsx
  quadratic-client/src/app/ai/toolCards/TableMeta.tsx
  quadratic-client/src/app/ai/toolCards/UpdateCodeCell.tsx
  quadratic-client/src/app/ai/tools/aiToolsActions.ts
  quadratic-client/src/app/atoms/editorInteractionStateAtom.ts
  quadratic-client/src/app/events/events.ts
  quadratic-client/src/app/grid/actions/clipboard/clipboard.ts
  quadratic-client/src/app/grid/controller/Sheets.ts
  quadratic-client/src/app/grid/sheet/Sheet.ts
  quadratic-client/src/app/gridGL/HTMLGrid/contextMenus/tableSort/TableSort.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
  quadratic-client/src/app/gridGL/HTMLGrid/validations/HtmlValidationCheckbox.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/validations/HtmlValidationList.tsx
  quadratic-client/src/app/gridGL/UI/UIValidations.ts
  quadratic-client/src/app/gridGL/cells/cellsLabel/CellsTextHashSpecial.ts
  quadratic-client/src/app/gridGL/cells/tables/TableColumnHeaders.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardCell.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerHeading.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerTableResize.ts
  quadratic-client/src/app/ui/components/DateFormat.tsx
  quadratic-client/src/app/ui/helpers/formatCells.ts
  quadratic-client/src/app/ui/hooks/useRenameTableColumnName.tsx
  quadratic-client/src/app/ui/hooks/useRenameTableName.tsx
  quadratic-client/src/app/ui/menus/BottomBar/KernelMenu.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/AIAssistant/CodeSnippet.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorDiffButtons.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/hooks/useSaveAndRunCell.tsx
  quadratic-client/src/app/ui/menus/CommandPalette/commands/Code.tsx
  quadratic-client/src/app/ui/menus/CommandPalette/commands/Sheets.tsx
  quadratic-client/src/app/ui/menus/SheetBar/SheetBarTabDropdownMenu.tsx
  quadratic-client/src/app/ui/menus/Validations/Validation/Validation.tsx
  quadratic-client/src/app/ui/menus/Validations/Validation/useValidationData.ts
  quadratic-client/src/app/ui/menus/Validations/Validations/useValidationsData.tsx
  quadratic-client/src/app/web-workers/quadraticCore/coreClientMessages.ts
  quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
  quadratic-core/src/wasm_bindings/a1.rs
  quadratic-core/src/wasm_bindings/controller/borders.rs
  quadratic-core/src/wasm_bindings/controller/cells.rs
  quadratic-core/src/wasm_bindings/controller/clipboard.rs
  quadratic-core/src/wasm_bindings/controller/code.rs
  quadratic-core/src/wasm_bindings/controller/col_row.rs
  quadratic-core/src/wasm_bindings/controller/data_table.rs
  quadratic-core/src/wasm_bindings/controller/formatting.rs
  quadratic-core/src/wasm_bindings/controller/sheet_offsets.rs
  quadratic-core/src/wasm_bindings/controller/sheets.rs
  quadratic-shared/ai/specs/aiToolsSpec.ts
Labels: cla-signed, status: ready to merge

#3308 AI prefer table names
  quadratic-api/src/ai/docs/QuadraticDocs.ts
  quadratic-client/src/app/ai/hooks/useOtherSheetsContextMessages.tsx
  quadratic-client/src/app/ai/hooks/useTablesContextMessages.tsx
  quadratic-client/src/app/ai/hooks/useVisibleContextMessages.tsx
  quadratic-shared/ai/specs/aiToolsSpec.ts
Labels: status: requested changes, status: ready for user test

#3318 Replace console logs with winston logs + db/winston integration
  infra/package.json
  quadratic-api/package.json
  quadratic-api/src/ai/handler/ai.handler.ts
  quadratic-api/src/ai/helpers/modelRouter.helper.ts
  quadratic-api/src/app.ts
  quadratic-api/src/auth/auth0.ts
  quadratic-api/src/auth/ory.ts
  quadratic-api/src/data/connections.ts
  quadratic-api/src/dbClient.ts
  quadratic-api/src/email/sendEmail.ts
  quadratic-api/src/licenseClient.ts
  quadratic-api/src/middleware/logRequestInfo.ts
  quadratic-api/src/middleware/validateRequestSchema.ts
  quadratic-api/src/routes/v0/ai.chat.POST.ts
  quadratic-api/src/routes/v0/examples.POST.ts
  quadratic-api/src/routes/v0/feedback.POST.ts
  quadratic-api/src/routes/v0/webhooks.stripe.POST.ts
  quadratic-api/src/server.ts
  quadratic-api/src/storage/fileSystem.ts
  quadratic-api/src/stripe/stripe.ts
  quadratic-api/src/utils/crypto.ts
  quadratic-api/src/utils/logger.ts
  quadratic-api/src/utils/permissions.ts
  test/e2e/package.json
Labels: cla-signed, status: ready to merge
