Repository quadratichq/quadratic, pull requests merged in 2025-04, with the labels that each got.

#2604 bugfix: clear GridFileInput value after import
  quadratic-client/src/app/actions/insertActionsSpec.ts
Labels: cla-signed, status: ready to merge

#2625 Fix stuck in rename
  quadratic-client/src/app/ui/menus/SheetBar/SheetBarTab.tsx
Labels: cla-signed, status: ready to merge

#2626 Code peek should not appear on data table
  quadratic-client/src/app/gridGL/interaction/pointer/pointerCursor.ts
Labels: status: ready to merge

#2627 Ignore table edges for tables that are of size 1
  quadratic-core/src/grid/sheet.rs
Labels: status: ready to merge

#2585 chore: remove more mui
  quadratic-client/src/app/theme/colors.ts
  quadratic-client/src/app/ui/components/PermissionOverlay.tsx
  quadratic-client/src/app/ui/components/SheetRange.tsx
  quadratic-client/src/app/ui/components/SnackBar.tsx
  quadratic-client/src/app/ui/icons/index.tsx
  quadratic-client/src/app/ui/menus/BottomBar/BottomBarItem.tsx
  quadratic-client/src/app/ui/menus/BottomBar/KernelMenu.tsx
  quadratic-client/src/app/ui/menus/BottomBar/SelectionSummary.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorEmptyState.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/ReturnTypeInspector.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/SaveChangesAlert.tsx
  quadratic-client/src/app/ui/menus/CommandPalette/commands/Format.tsx
  quadratic-client/src/app/ui/menus/SheetBar/SheetBar.tsx
  quadratic-client/src/app/ui/menus/SheetBar/SheetBarTab.tsx
  quadratic-client/src/dashboard/components/EducationDialog.tsx
  quadratic-client/src/shared/components/Icons.tsx
  quadratic-client/src/shared/components/RenameInput.tsx
  quadratic-client/src/shared/components/icons.css
  quadratic-client/src/shared/shadcn/ui/alert-dialog.tsx
Labels: cla-signed, status: ready for user test

#2629 Ensure shift+enter in the inline editor doesn't add a linebreak
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorKeyboard.ts
Labels: cla-signed, status: ready to merge

#2621 Matplotlib attempts are emerging from AI
  quadratic-api/src/ai/docs/PythonDocs.ts
Labels: cla-signed, status: ready to merge

#2630 No longer shows warning when closing code editor after running code
  quadratic-client/src/app/ui/menus/CodeEditor/hooks/useSaveAndRunCell.tsx
Labels: cla-signed, status: ready to merge

#2652 fix: hotfix for zip2 2.6.0 breaking changes
  .vscode/settings.json
  Cargo.toml
  bump.sh
  quadratic-client/src/app/quadratic-core-types/index.d.ts
  quadratic-connection/Cargo.lock
  quadratic-core/Cargo.lock
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.lock
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.lock
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-client/Cargo.lock
  quadratic-rust-client/Cargo.toml
Labels: cla-signed, status: ready for code review

#2650 Improve formula functions docs output
  quadratic-core/src/bin/docgen.rs
  quadratic-core/src/bin/docs_end.md
  quadratic-core/src/formulas/functions/macros.rs
Labels: cla-signed

#2617 Billing Soft Limit
  .vscode/settings.json
  docker-compose.yml
  infra/aws-cloudformation/quadratic-preview.yml
  quadratic-api/.env.example
  quadratic-api/.env.test
  quadratic-api/src/ai/usage.ts
  quadratic-api/src/billing/AIUsageHelpers.ts
  quadratic-api/src/env-vars.ts
  quadratic-api/src/routes/v0/ai.chat.POST.ts
  quadratic-api/src/routes/v0/teams.$uuid.GET.ts
  quadratic-api/src/routes/v0/teams.$uuid.billing.ai.usage.GET.ts
  quadratic-client/src/app/actions/insertActionsSpec.ts
  quadratic-client/src/app/ai/hooks/useAIRequestToAPI.tsx
  quadratic-client/src/app/atoms/aiAnalystAtom.ts
  quadratic-client/src/app/atoms/codeEditorAtom.ts
  quadratic-client/src/app/grid/actions/openCodeEditor.ts
  quadratic-client/src/app/gridGL/HTMLGrid/hoverCell/HoverCell.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerTable.ts
  quadratic-client/src/app/gridGL/interaction/pointer/doubleClickCell.ts
  quadratic-client/src/app/ui/components/AIUsageExceeded.tsx
  quadratic-client/src/app/ui/components/AIUserMessageForm.tsx
  quadratic-client/src/app/ui/components/AIUserMessageFormDisclaimer.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalyst.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystContext.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystMessages.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystUserMessageForm.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/hooks/useSubmitAIAnalystPrompt.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/AIAssistant/AIAssistant.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/AIAssistant/AIAssistantMessages.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/AIAssistant/AIAssistantUserMessageForm.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/ReturnTypeInspector.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/hooks/useSaveAndRunCell.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/hooks/useSubmitAIAssistantPrompt.tsx
  quadratic-client/src/app/ui/menus/ConnectionsMenu/ConnectionsMenu.tsx
  quadratic-client/src/routes/teams.$teamUuid.settings.tsx
  quadratic-client/src/shared/api/apiClient.ts
  quadratic-shared/typesAndSchemas.ts
Labels: cla-signed, status: ready for code review, QA

#2648 Hotfix wasm call in data tables
  quadratic-core/src/controller/operations/clipboard.rs
  quadratic-core/src/grid/sheet/data_table.rs
Labels: cla-signed, status: ready to merge

#2661 fix: calculationComplete failed to parse response
  .github/workflows/ci.yml
  .gitignore
  quadratic-kernels/python-wasm/quadratic_py/process_output.py
Labels: cla-signed, status: ready to merge, QA

#2662 chore: capture error in mixpanel
  quadratic-client/src/shared/components/Empty.tsx
Labels: cla-signed, status: ready for code review

#2605 Improve date parsing
  quadratic-core/src/date_time.rs
Labels: cla-signed, status: ready to merge

#2672 chore: version 0.6.10
  VERSION
  package-lock.json
  package.json
  quadratic-api/package.json
  quadratic-client/package.json
  quadratic-connection/Cargo.lock
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.lock
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.lock
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.lock
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-client/Cargo.lock
  quadratic-rust-client/Cargo.toml
  quadratic-rust-shared/Cargo.lock
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: cla-signed

#2668 Keep AI from using try-except blocks
  quadratic-api/src/ai/docs/PythonDocs.ts
Labels: cla-signed, status: ready for user test

#2669 chore: switch to gemini 2.5 pro preview
  quadratic-shared/ai/models/AI_MODELS.ts
  quadratic-shared/typesAndSchemasAI.ts
Labels: cla-signed, status: ready for code review, QA

#2677 change order of pointerDown.heading
  quadratic-client/src/app/gridGL/interaction/pointer/Pointer.ts
Labels: cla-signed, status: ready to merge

#2686 Add QA Wolf to PR template
  .github/pull_request_template.md
Labels: cla-signed, status: ready to merge

#2675 fix: build cache
  .github/workflows/preview-build-deploy-images.yml
  .github/workflows/production-deploy.yml
  .github/workflows/production-publish-images.yml
  .github/workflows/qa-deploy.yml
  quadratic-client/Dockerfile
Labels: cla-signed, status: ready for code review, QA

#2615 Pasting in bounds, with multiples of the clipboard size
  quadratic-connection/Cargo.lock
  quadratic-core/Cargo.lock
  quadratic-core/src/a1/cell_ref_range/mod.rs
  quadratic-core/src/controller/execution/execute_operation/execute_move_cells.rs
  quadratic-core/src/controller/operations/clipboard.rs
  quadratic-core/src/controller/user_actions/clipboard.rs
  quadratic-core/src/controller/user_actions/move_col_row.rs
  quadratic-core/src/formulas/parser/mod.rs
  quadratic-core/src/grid/file/mod.rs
  quadratic-core/src/pos.rs
  quadratic-core/src/test_util/gc.rs
  quadratic-core/src/values/cell_values.rs
Labels: cla-signed, status: ready to merge, status: requested changes, QA

#2649 Fix command palette column/row inserts
  quadratic-client/src/app/ui/menus/CommandPalette/CommandPalette.tsx
  quadratic-client/src/app/ui/menus/CommandPalette/commands/ColumnRow.tsx
Labels: cla-signed, status: ready to merge, QA

#2656 Don't close cell type menu and command palette on scrollbar click
  quadratic-client/src/app/ui/menus/CellTypeMenu/CellTypeMenu.tsx
  quadratic-client/src/app/ui/menus/CommandPalette/CommandPalette.tsx
  quadratic-client/src/shared/shadcn/ui/command.tsx
Labels: cla-signed, status: ready to merge, QA

#2689 fix: prevent heroku timeout for pdf import
  quadratic-api/src/ai/handler/anthropic.ts
  quadratic-api/src/ai/handler/bedrock.ts
  quadratic-api/src/ai/handler/openai.ts
  quadratic-api/src/ai/handler/vertexai.ts
  quadratic-api/src/ai/helpers/anthropic.helper.ts
  quadratic-api/src/ai/helpers/bedrock.helper.ts
  quadratic-api/src/ai/helpers/openai.helper.ts
  quadratic-api/src/ai/helpers/vertexai.helper.ts
  quadratic-client/src/app/ai/hooks/useAIRequestToAPI.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/hooks/useAnalystPDFImport.tsx
Labels: cla-signed, QA

#2687 PDF UI
  package-lock.json
  quadratic-client/package.json
  quadratic-client/src/app/gridGL/PixiAppEffects.tsx
  quadratic-client/src/app/ui/components/AIContext.tsx
  quadratic-client/src/app/ui/components/AIUserMessageForm.tsx
  quadratic-client/src/app/ui/components/FileDragDropWrapper.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystUserMessageForm.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/AIAssistant/AIAssistantUserMessageForm.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorHeader.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBarFileNameAndLocationMenu.tsx
  quadratic-client/src/shared/components/Icons.tsx
  quadratic-client/src/shared/shadcn/ui/hover-card.tsx
  quadratic-shared/typesAndSchemasAI.ts
Labels: cla-signed, status: ready to merge, QA

#2696 fix: parsing of numbers with parentheses and/or spaces
  quadratic-core/src/controller/operations/cell_value.rs
  quadratic-core/src/controller/user_actions/import.rs
  quadratic-core/src/values/cellvalue.rs
Labels: cla-signed, status: ready to merge, QA

#2695 add an ab test on ai exceeded copy
  quadratic-client/src/app/ui/components/AIUsageExceeded.tsx
  quadratic-client/src/shared/components/ABTest.tsx
Labels: cla-signed, status: ready for user test, QA

#2636 improved right click on table and table column
  quadratic-client/src/app/actions.ts
  quadratic-client/src/app/actions/actionsSpec.ts
  quadratic-client/src/app/actions/codeActionsSpec.ts
  quadratic-client/src/app/actions/columnRowSpec.ts
  quadratic-client/src/app/actions/dataTableSpec.ts
  quadratic-client/src/app/actions/editActionsSpec.ts
  quadratic-client/src/app/actions/fileActionsSpec.ts
  quadratic-client/src/app/actions/formatActionsSpec.ts
  quadratic-client/src/app/actions/helpActionsSpec.ts
  quadratic-client/src/app/actions/insertActionsSpec.ts
  quadratic-client/src/app/actions/selectionActionsSpec.ts
  quadratic-client/src/app/actions/viewActionsSpec.ts
  quadratic-client/src/app/grid/sheet/SheetCursor.ts
  quadratic-client/src/app/gridGL/HTMLGrid/contextMenus/Base.tsx
  quadratic-client/src/app/gridGL/interaction/pointer/PointerTable.ts
  quadratic-client/src/app/ui/QuadraticSidebar.tsx
  quadratic-client/src/app/ui/components/BorderMenu.tsx
  quadratic-client/src/app/ui/components/Search.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystHeader.tsx
  quadratic-client/src/app/ui/menus/CommandPalette/CommandPalette.tsx
  quadratic-client/src/app/ui/menus/CommandPalette/commands/File.tsx
  quadratic-client/src/app/ui/menus/Toolbar/FormattingBar.tsx
  quadratic-client/src/app/ui/menus/Toolbar/ZoomMenu.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBarMenus/FormatMenubarMenu.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBarMenus/MenubarItemAction.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBarMenus/TopBarMenus.tsx
  quadratic-core/src/a1/a1_selection/query.rs
  quadratic-core/src/a1/js_selection/query.rs
  quadratic-core/src/a1/table_ref/range.rs
Labels: cla-signed, status: ready to merge, QA

#2682 AI docs update
  quadratic-api/src/ai/docs/PythonDocs.ts
  quadratic-api/src/ai/docs/QuadraticDocs.ts
  quadratic-shared/ai/specs/aiToolsSpec.ts
Labels: cla-signed, status: ready to merge, QA

#2703 fix: manage billing button and stripe db sync
  quadratic-api/jest.setup.js
  quadratic-api/src/routes/v0/teams.$uuid.GET.ts
  quadratic-api/src/stripe/stripe.ts
  quadratic-client/src/routes/teams.$teamUuid.settings.tsx
Labels: cla-signed, status: ready for code review, QA

#2698 Scrollbars (div)
  .vscode/settings.json
  quadratic-client/src/app/atoms/gridSettingsAtom.ts
  quadratic-client/src/app/events/events.ts
  quadratic-client/src/app/grid/sheet/Sheet.ts
  quadratic-client/src/app/gridGL/HTMLGrid/htmlCells/HtmlCell.ts
  quadratic-client/src/app/gridGL/HTMLGrid/htmlCells/htmlCellsHandler.ts
  quadratic-client/src/app/gridGL/HTMLGrid/scrollBars/ScrollBars.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/scrollBars/ScrollBarsHandler.ts
  quadratic-client/src/app/gridGL/QuadraticGrid.tsx
  quadratic-client/src/app/gridGL/interaction/pointer/Pointer.ts
  quadratic-client/src/app/gridGL/pixiApp/Update.ts
  quadratic-client/src/app/gridGL/pixiApp/viewport/Viewport.ts
  quadratic-client/src/app/ui/menus/CommandPalette/commands/View.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBarMenus/ViewMenubarMenu.tsx
Labels: cla-signed, status: ready to merge, QA

#2715 Make AI chat aware of PDF capabilities
  quadratic-api/src/ai/docs/PythonDocs.ts
  quadratic-api/src/ai/docs/QuadraticDocs.ts
Labels: cla-signed, status: ready for user test, QA

#2709 fix: finalize transaction on cancel connection
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreConnection.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreJavascript.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/corePython.ts
Labels: cla-signed, status: ready to merge, QA

#2711 fix: rendering of multiplayer transactions
  quadratic-client/src/app/atoms/editorInteractionStateAtom.ts
  quadratic-client/src/app/ui/menus/BottomBar/KernelMenu.tsx
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHash.ts
  quadratic-core/src/controller/active_transactions/pending_transaction.rs
  quadratic-core/src/controller/execution/receive_multiplayer.rs
Labels: cla-signed, status: ready to merge, QA

#2509 feat: application loading state
  quadratic-client/index.html
  quadratic-client/public/images/logo_etching.png
  quadratic-client/public/images/logo_loading.gif
  quadratic-client/src/app/ui/QuadraticApp.tsx
  quadratic-client/src/app/ui/loading/QuadraticLoading.tsx
  quadratic-client/src/app/ui/loading/styles.css
  quadratic-client/src/routes/_root.tsx
Labels: cla-signed, status: ready to merge, QA

#2732 fix: disable flaky multiplayer test
  quadratic-multiplayer/src/server.rs
Labels: cla-signed, status: ready for code review

#2733 fix: loading screen
  quadratic-client/index.html
  quadratic-client/src/app/ui/QuadraticUI.tsx
  quadratic-client/src/router.tsx
  quadratic-client/src/routes/_dashboard.tsx
  quadratic-client/src/routes/_root.tsx
  quadratic-client/src/routes/file.$uuid.duplicate.tsx
  quadratic-client/src/routes/file.$uuid.history.tsx
  quadratic-client/src/shared/components/Empty.tsx
  quadratic-client/src/shared/hooks/useRemoveInitialLoadingUI.ts
Labels: cla-signed, status: ready for code review, QA

#2736 fix: qa docker image tag
  .github/workflows/qa-deploy.yml
Labels: cla-signed, status: ready for code review

#2730 fix: enable mouse edges for autocomplete
  quadratic-client/src/app/gridGL/interaction/pointer/PointerAutoComplete.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerCellMoving.ts
Labels: cla-signed, QA

#2731 fix: clicking sheet references across sheets doesn't get saved
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorFormula.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
  quadratic-client/src/app/gridGL/UI/cellHighlights/CellHighlights.ts
Labels: cla-signed, QA

#2740 chore: add gpt o3 and o4-mini in debug mode
  package-lock.json
  quadratic-api/package.json
  quadratic-shared/ai/models/AI_MODELS.ts
  quadratic-shared/typesAndSchemasAI.ts
Labels: cla-signed

#2719 fix: rendering issues with formatting
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHash.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHashContent.ts
Labels: cla-signed, QA

#2738 chore: add version number to all health endpoints
  .github/workflows/preview-build-deploy-images.yml
  .github/workflows/production-deploy.yml
  .github/workflows/production-publish-images.yml
  .github/workflows/qa-deploy.yml
  quadratic-api/Dockerfile
  quadratic-api/package.json
  quadratic-api/src/app.ts
  quadratic-api/src/env-vars.ts
  quadratic-client/Dockerfile
  quadratic-client/package.json
  quadratic-connection/Cargo.toml
  quadratic-connection/src/header.rs
  quadratic-connection/src/health.rs
  quadratic-connection/src/main.rs
  quadratic-connection/src/server.rs
  quadratic-connection/src/sql/postgres.rs
  quadratic-connection/src/test_util.rs
  quadratic-files/src/health.rs
  quadratic-files/src/main.rs
  quadratic-files/src/server.rs
  quadratic-files/src/test_util.rs
  quadratic-multiplayer/src/health.rs
  quadratic-multiplayer/src/main.rs
  quadratic-multiplayer/src/server.rs
  quadratic-multiplayer/src/state/user.rs
  quadratic-multiplayer/src/test_util.rs
  quadratic-rust-shared/src/quadratic_api.rs
Labels: cla-signed, status: ready for code review

#2746 bugfix: Auto-expand on sorted table causes disappearing data
  quadratic-connection/Cargo.lock
  quadratic-core/src/controller/operations/cell_value.rs
  quadratic-core/src/grid/data_table/column.rs
  quadratic-core/src/grid/data_table/row.rs
Labels: cla-signed, status: ready to merge, QA

#2749 fix: tooltip shortcut label
  quadratic-client/src/app/gridGL/interaction/pointer/PointerLink.ts
Labels: cla-signed

#2747 fix: verify version concurrency
  .github/workflows/production-deploy.yml
  .github/workflows/qa-deploy.yml
  Procfile
  quadratic-api/src/app.ts
Labels: cla-signed

#2750 fix: api version on health endpoint
  .github/workflows/preview-build-deploy-images.yml
  .github/workflows/production-deploy.yml
  .github/workflows/qa-deploy.yml
  Procfile
Labels: cla-signed, status: ready for code review

#2751 fix: add missing backslash
  .github/workflows/preview-build-deploy-images.yml
  .github/workflows/production-deploy.yml
  .github/workflows/qa-deploy.yml
Labels: cla-signed, status: ready for code review

#2755 chore: increment version to 0.6.11
  VERSION
  package-lock.json
  package.json
  quadratic-api/package.json
  quadratic-client/package.json
  quadratic-connection/Cargo.lock
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.lock
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.lock
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.lock
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-client/Cargo.lock
  quadratic-rust-client/Cargo.toml
  quadratic-rust-shared/Cargo.lock
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: cla-signed, status: ready for code review

#2726 Rework date parsing
  quadratic-core/src/date_time.rs
Labels: cla-signed, status: ready for user test

#2757 Logo loading starts empty and fills in
  quadratic-client/public/images/logo_loading.gif
Labels: cla-signed

#2760 chore: use claude on gcp
  docker-compose.yml
  infra/aws-cloudformation/quadratic-preview.yml
  quadratic-api/.env.test
  quadratic-api/src/ai/providers.ts
  quadratic-api/src/env-vars.ts
  quadratic-api/src/routes/v0/ai.chat.POST.test.ts
  quadratic-shared/ai/models/AI_MODELS.ts
Labels: cla-signed, status: ready for code review, status: ready for user test

#2762 Version refresh
  .gitignore
  .vscode/settings.json
  DEVELOPMENT.md
  bump.sh
  quadratic-client/Dockerfile
  quadratic-client/public/version.json
  quadratic-client/src/app/debugFlags.ts
  quadratic-client/src/app/events/events.ts
  quadratic-client/src/app/schemas/compareVersions.test.ts
  quadratic-client/src/app/schemas/compareVersions.ts
  quadratic-client/src/app/shared/types/RefreshType.ts
  quadratic-client/src/app/ui/UpdateAlertVersion.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBar.tsx
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayer.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayerTypes.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/worker/multiplayerServer.ts
  quadratic-multiplayer/Dockerfile
  quadratic-multiplayer/build.rs
  quadratic-multiplayer/src/background_worker.rs
  quadratic-multiplayer/src/error.rs
  quadratic-multiplayer/src/message/handle.rs
  quadratic-multiplayer/src/message/response.rs
  quadratic-multiplayer/src/server.rs
  quadratic-multiplayer/src/state/settings.rs
  updateAlertVersion.json
Labels: cla-signed, status: ready for code review, status: ready for user test

#2771 version refresh cherry pick
  .gitignore
  .vscode/settings.json
  DEVELOPMENT.md
  bump.sh
  quadratic-client/Dockerfile
  quadratic-client/public/version.json
  quadratic-client/src/app/debugFlags.ts
  quadratic-client/src/app/events/events.ts
  quadratic-client/src/app/schemas/compareVersions.test.ts
  quadratic-client/src/app/schemas/compareVersions.ts
  quadratic-client/src/app/shared/types/RefreshType.ts
  quadratic-client/src/app/ui/UpdateAlertVersion.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBar.tsx
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayer.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayerTypes.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/worker/multiplayerServer.ts
  quadratic-multiplayer/Dockerfile
  quadratic-multiplayer/build.rs
  quadratic-multiplayer/src/background_worker.rs
  quadratic-multiplayer/src/error.rs
  quadratic-multiplayer/src/message/handle.rs
  quadratic-multiplayer/src/message/response.rs
  quadratic-multiplayer/src/server.rs
  quadratic-multiplayer/src/state/settings.rs
  updateAlertVersion.json
Labels: cla-signed

#2769 chore: use app version to notify client to refresh on app update
  .gitignore
  .vscode/settings.json
  DEVELOPMENT.md
  VERSION
  bump.sh
  package-lock.json
  package.json
  quadratic-api/package.json
  quadratic-client/Dockerfile
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-client/src/app/debugFlags.ts
  quadratic-client/src/app/events/events.ts
  quadratic-client/src/app/schemas/compareVersions.test.ts
  quadratic-client/src/app/schemas/compareVersions.ts
  quadratic-client/src/app/shared/types/RefreshType.ts
  quadratic-client/src/app/ui/UpdateAlertVersion.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBar.tsx
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayer.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayerTypes.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/worker/multiplayerServer.ts
  quadratic-connection/Cargo.lock
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.lock
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.lock
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.lock
  quadratic-multiplayer/Cargo.toml
  quadratic-multiplayer/Dockerfile
  quadratic-multiplayer/build.rs
  quadratic-multiplayer/src/background_worker.rs
  quadratic-multiplayer/src/error.rs
  quadratic-multiplayer/src/message/handle.rs
  quadratic-multiplayer/src/message/response.rs
  quadratic-multiplayer/src/server.rs
  quadratic-multiplayer/src/state/settings.rs
  quadratic-rust-client/Cargo.lock
  quadratic-rust-client/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
  updateAlertVersion.json
Labels: cla-signed

#2774 Update QA with Main 0.6.12
  .gitignore
  .vscode/settings.json
  DEVELOPMENT.md
  VERSION
  bump.sh
  package-lock.json
  package.json
  quadratic-api/package.json
  quadratic-client/Dockerfile
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-client/src/app/debugFlags.ts
  quadratic-client/src/app/events/events.ts
  quadratic-client/src/app/schemas/compareVersions.test.ts
  quadratic-client/src/app/schemas/compareVersions.ts
  quadratic-client/src/app/shared/types/RefreshType.ts
  quadratic-client/src/app/ui/UpdateAlertVersion.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBar.tsx
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayer.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayerTypes.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/worker/multiplayerServer.ts
  quadratic-connection/Cargo.lock
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.lock
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.lock
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.lock
  quadratic-multiplayer/Cargo.toml
  quadratic-multiplayer/Dockerfile
  quadratic-multiplayer/build.rs
  quadratic-multiplayer/src/background_worker.rs
  quadratic-multiplayer/src/error.rs
  quadratic-multiplayer/src/message/handle.rs
  quadratic-multiplayer/src/message/response.rs
  quadratic-multiplayer/src/server.rs
  quadratic-multiplayer/src/state/settings.rs
  quadratic-rust-shared/Cargo.lock
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
  updateAlertVersion.json
Labels: cla-signed

#2758 Python data table name states
  quadratic-client/src/app/actions/dataTableSpec.ts
  quadratic-core/src/controller/execution/run_code/mod.rs
  quadratic-core/src/grid/data_table/mod.rs
Labels: cla-signed, status: ready to merge

#2780 chore: bump version to 0.6.13
  VERSION
  package-lock.json
  package.json
  quadratic-api/package.json
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-connection/Cargo.lock
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.lock
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.lock
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.lock
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.lock
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: cla-signed, status: ready for code review

#2779 fix: code cell position for "Use Connection"
  quadratic-client/src/app/gridGL/HTMLGrid/EmptyGridMessage.tsx
Labels: cla-signed, status: ready for code review, status: ready for user test

#2778 fix: text paste in ai chat
  .zed/settings.json
  quadratic-client/src/app/ui/components/AIUserMessageForm.tsx
Labels: cla-signed, status: ready for code review, status: ready for user test

#2785 Fix mixpanel event
  quadratic-client/src/app/ui/components/AIUsageExceeded.tsx
  quadratic-client/src/shared/components/ABTest.tsx
Labels: cla-signed

#2795 chore: switch to claude on bedrock
  quadratic-shared/ai/models/AI_MODELS.ts
Labels: cla-signed, status: ready for code review

#2794 fix: text align in inline monaco
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorStyles.scss
  quadratic-client/src/app/gridGL/UI/Cursor.ts
Labels: cla-signed, status: ready for code review

#2796 chore: bump version to 0.6.14
  VERSION
  package-lock.json
  package.json
  quadratic-api/package.json
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-connection/Cargo.lock
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.lock
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.lock
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.lock
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: cla-signed, status: ready for code review

#2798 chore: add github release in ci
  .github/workflows/production-github-release.yml
Labels: cla-signed, status: ready for code review

#2790 fix: sentry source map upload
  package-lock.json
  quadratic-client/package.json
  quadratic-client/vite.config.js
Labels: cla-signed

#2788 QA Apr 22
  .github/workflows/production-github-release.yml
  VERSION
  package-lock.json
  package.json
  quadratic-api/package.json
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorStyles.scss
  quadratic-client/src/app/gridGL/UI/Cursor.ts
  quadratic-client/vite.config.js
  quadratic-connection/Cargo.lock
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.lock
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.lock
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.lock
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/ai/models/AI_MODELS.ts
  quadratic-shared/package.json
Labels: cla-signed

#2820 fix: add write permission to Github Release workflow
  .github/workflows/production-github-release.yml
Labels: cla-signed, status: ready for code review

#2816 AI Paywall
  quadratic-client/src/app/ui/components/AIUsageExceeded.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/hooks/useSubmitAIAnalystPrompt.tsx
  quadratic-client/src/shared/components/ABTest.tsx
Labels: cla-signed

#2817 chore: change ai default, fix thinking state on update
  quadratic-client/src/app/ai/hooks/useAIModel.tsx
  quadratic-shared/ai/models/AI_MODELS.ts
Labels: cla-signed, status: ready for code review, QA

#2824 fix: 1.8 show column migration
  quadratic-core/src/grid/file/v1_8/upgrade.rs
Labels: cla-signed, status: ready for code review, status: ready for user test

#2827 chore: bump version to 0.7.0
  VERSION
  package-lock.json
  package.json
  quadratic-api/package.json
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-connection/Cargo.lock
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.lock
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.lock
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.lock
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.lock
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: cla-signed, status: ready for code review, status: ready for user test

#2761 Ensure checkboxes properly rerender hash
  quadratic-client/src/app/gridGL/cells/cellsLabel/CellsLabels.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHash.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHashContent.test.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHashSpecial.ts
  quadratic-core/src/grid/sheet/validations/validation_rules/validation_logical.rs
Labels: cla-signed, status: ready to merge

#2737 fix: fetching users from auth0
  quadratic-api/src/auth/auth0.test.ts
  quadratic-api/src/auth/auth0.ts
  quadratic-api/src/middleware/getTeam.test.ts
  quadratic-api/src/middleware/user.test.ts
  quadratic-api/src/routes/v0/files.$uuid.invites.POST.test.ts
  quadratic-api/src/routes/v0/files.$uuid.sharing.GET.test.ts
  quadratic-api/src/routes/v0/teams.$uuid.GET.test.ts
  quadratic-api/src/routes/v0/teams.$uuid.GET.ts
  quadratic-api/src/routes/v0/teams.$uuid.invites.POST.test.ts
  quadratic-api/src/routes/v0/teams.$uuid.invites.POST.ts
  quadratic-api/src/tests/auth0Mock.ts
Labels: cla-signed, status: ready to merge

#2756 Allow move column and row
  quadratic-client/src/app/grid/sheet/SheetCursor.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerHeading.ts
Labels: cla-signed, status: ready to merge

#2710 fix: replace browser confirm dialog with one from the app
  quadratic-client/src/app/actions.ts
  quadratic-client/src/app/ui/menus/CommandPalette/commands/File.tsx
  quadratic-client/src/app/ui/menus/CommandPalette/commands/Sheets.tsx
  quadratic-client/src/app/ui/menus/SheetBar/SheetBarTabDropdownMenu.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBarMenus/FileMenubarMenu.tsx
  quadratic-client/src/dashboard/components/FilesListItem.tsx
  quadratic-client/src/routes/_root.tsx
  quadratic-client/src/shared/components/ConfirmProvider.tsx
  quadratic-client/src/shared/components/ShareDialog.tsx
  quadratic-client/src/shared/components/connections/ConnectionFormActions.tsx
Labels: cla-signed, status: ready to merge

#2754 fix: auto row resize on setting format wrap in data tables
  .env.docker
  quadratic-core/src/controller/execution/auto_resize_row_heights.rs
  quadratic-core/src/controller/execution/execute_operation/execute_data_table.rs
  quadratic-core/src/grid/data_table/send_render.rs
  quadratic-core/src/grid/sheet/col_row/columns_delete_table.rs
  quadratic-core/src/grid/sheet/col_row/rows_delete_table.rs
  quadratic-core/src/grid/sheet_formatting/sheet_formatting_query.rs
  quadratic-core/src/rect.rs
Labels: cla-signed, status: ready to merge

#2834 Hotfix index out of bounds issue
  VERSION
  package-lock.json
  package.json
  quadratic-api/package.json
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-client/src/router.tsx
  quadratic-connection/Cargo.lock
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.lock
  quadratic-core/Cargo.toml
  quadratic-core/src/controller/execution/run_code/mod.rs
  quadratic-files/Cargo.lock
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.lock
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.lock
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: cla-signed

#2832 Fixes flashing cursor at 0,0 when double clicking inside a data table
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
Labels: status: ready to merge

#2841 Main
  VERSION
  package-lock.json
  package.json
  quadratic-api/package.json
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-client/src/router.tsx
  quadratic-connection/Cargo.lock
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.lock
  quadratic-core/Cargo.toml
  quadratic-core/src/controller/execution/run_code/mod.rs
  quadratic-files/Cargo.lock
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.lock
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.lock
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: cla-signed

#2840 feat: add forum link
  quadratic-client/src/app/actions/helpActionsSpec.ts
  quadratic-client/src/dashboard/components/DashboardSidebar.tsx
  quadratic-client/src/shared/constants/urls.ts
Labels: cla-signed
