Repository quadratichq/quadratic, pull requests merged in 2025-06, with the labels that each got.

#3016 AI prompt improvements
  quadratic-api/src/ai/helpers/context.helper.ts
  quadratic-shared/ai/specs/aiToolsSpec.ts
Labels: cla-signed, status: ready for user test, QA

#3013 improving A1Context serialization/deserialization speeds
  .vscode/settings.json
  quadratic-client/src/app/actions/codeActionsSpec.ts
  quadratic-client/src/app/actions/editActionsSpec.ts
  quadratic-client/src/app/ai/hooks/useVisibleContextMessages.tsx
  quadratic-client/src/app/ai/toolCards/SetCodeCellValue.tsx
  quadratic-client/src/app/ai/tools/aiToolsActions.ts
  quadratic-client/src/app/atoms/tableInfoAtom.ts
  quadratic-client/src/app/grid/actions/openCodeEditor.ts
  quadratic-client/src/app/grid/controller/Sheets.ts
  quadratic-client/src/app/grid/sheet/Sheet.ts
  quadratic-client/src/app/grid/sheet/SheetCursor.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorFormula.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
  quadratic-client/src/app/gridGL/UI/UIMultiplayerCursor.ts
  quadratic-client/src/app/gridGL/UI/UIValidations.ts
  quadratic-client/src/app/gridGL/UI/cellHighlights/CellHighlights.ts
  quadratic-client/src/app/gridGL/cells/tables/Tables.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardCell.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerDown.ts
  quadratic-client/src/app/gridGL/interaction/pointer/doubleClickCell.ts
  quadratic-client/src/app/gridGL/pixiApp/Update.ts
  quadratic-client/src/app/gridGL/pixiApp/viewport/Viewport.ts
  quadratic-client/src/app/quadratic-core-types/index.d.ts
  quadratic-client/src/app/ui/components/AIContext.tsx
  quadratic-client/src/app/ui/components/SheetRange.tsx
  quadratic-client/src/app/ui/hooks/useRenameTableColumnName.tsx
  quadratic-client/src/app/ui/hooks/useRenameTableName.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorHeaderLabel.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/hooks/useEditorCellHighlights.ts
  quadratic-client/src/app/ui/menus/GoTo/GoTo.tsx
  quadratic-client/src/app/ui/menus/SheetBar/SheetBarTab.tsx
  quadratic-client/src/app/ui/menus/Toolbar/Toolbar.tsx
  quadratic-client/src/app/ui/menus/Validations/Validations/ValidationEntry.tsx
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayer.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsLabels.ts
  quadratic-core/Cargo.toml
  quadratic-core/src/a1/a1_context/mod.rs
  quadratic-core/src/a1/a1_context/sheet_map.rs
  quadratic-core/src/a1/a1_context/table_map.rs
  quadratic-core/src/a1/js_selection/create.rs
  quadratic-core/src/a1/js_selection/mod.rs
  quadratic-core/src/a1/js_selection/query.rs
  quadratic-core/src/a1/js_selection/select.rs
  quadratic-core/src/a1/js_selection/validate_name.rs
  quadratic-core/src/controller/send_render.rs
  quadratic-core/src/formulas/parse_formula.rs
  quadratic-core/src/formulas/wasm.rs
  quadratic-core/src/util.rs
  quadratic-core/src/wasm_bindings/a1.rs
  quadratic-core/src/wasm_bindings/js.rs
  quadratic-core/src/wasm_bindings/js_a1_context.rs
  quadratic-core/src/wasm_bindings/mod.rs
Labels: cla-signed

#3019 fix: remove console error for extra ai response content
  quadratic-api/src/ai/handler/ai.handler.ts
  quadratic-api/src/ai/helpers/anthropic.helper.ts
  quadratic-api/src/ai/helpers/bedrock.helper.ts
  quadratic-api/src/ai/helpers/openai.helper.ts
  quadratic-api/src/ai/helpers/vertexai.helper.ts
Labels: cla-signed, status: ready for code review, status: ready for user test, QA

#3020 fix: add empty component to file/create route
  quadratic-client/src/routes/files.create.tsx
Labels: cla-signed, status: ready to merge, QA

#3022 bump to 0.10.0
  Cargo.toml
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: cla-signed

#3031 chore: revert prod to claude 3.5
  Cargo.toml
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/ai/models/AI_MODELS.ts
  quadratic-shared/package.json
Labels: cla-signed, status: ready for code review

#3035 Main
  Cargo.toml
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/ai/models/AI_MODELS.ts
  quadratic-shared/package.json
Labels: cla-signed

#2864 feat: provide users a demo connection by default
  CONTRIBUTING.md
  infra/aws-cloudformation/quadratic-preview.yml
  infra/package.json
  quadratic-api/.env.example
  quadratic-api/.env.test
  quadratic-api/package.json
  quadratic-api/prisma/migrations/20250604192605_add_connection_demo/migration.sql
  quadratic-api/prisma/schema.prisma
  quadratic-api/src/data/connections.ts
  quadratic-api/src/env-vars.ts
  quadratic-api/src/middleware/getTeamConnectionsList.ts
  quadratic-api/src/routes/v0/files.$uuid.GET.ts
  quadratic-api/src/routes/v0/internal.user.$auth0Id.teams.$uuid.connections.$connectionUuid.GET.ts
  quadratic-api/src/routes/v0/teams.$uuid.GET.test.ts
  quadratic-api/src/routes/v0/teams.$uuid.GET.ts
  quadratic-api/src/routes/v0/teams.$uuid.PATCH.ts
  quadratic-api/src/routes/v0/teams.$uuid.connections.GET.test.ts
  quadratic-api/src/routes/v0/teams.$uuid.connections.GET.ts
  quadratic-api/src/utils/teams.ts
  quadratic-client/src/app/actions/viewActionsSpec.ts
  quadratic-client/src/app/gridGL/HTMLGrid/EmptyGridMessage.tsx
  quadratic-client/src/app/ui/hooks/useConnectionsFetcher.tsx
  quadratic-client/src/app/ui/menus/CellTypeMenu/CellTypeMenu.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorHeaderLabel.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/hooks/useSaveAndRunCell.tsx
  quadratic-client/src/app/ui/menus/CommandPalette/commands/Connections.tsx
  quadratic-client/src/app/ui/menus/ConnectionsMenu/ConnectionsMenu.tsx
  quadratic-client/src/dashboard/components/NewFileButton.tsx
  quadratic-client/src/routes/api.connections.tsx
  quadratic-client/src/shared/components/ConfirmProvider.tsx
  quadratic-client/src/shared/components/connections/Connections.tsx
  quadratic-client/src/shared/components/connections/ConnectionsList.tsx
  quadratic-shared/typesAndSchemas.ts
  quadratic-shared/typesAndSchemasConnections.ts
  test/e2e/package.json
Labels: cla-signed, status: ready to merge, QA

#3036 chore: mixpanel event for empty grid message widget
  quadratic-client/src/app/gridGL/HTMLGrid/EmptyGridMessage.tsx
Labels: cla-signed, status: ready to merge, QA

#3018 Use content cache from core
  quadratic-client/src/app/events/events.ts
  quadratic-client/src/app/grid/controller/Sheets.ts
  quadratic-client/src/app/grid/sheet/Sheet.ts
  quadratic-client/src/app/gridGL/UI/UIValidations.ts
  quadratic-client/src/app/gridGL/cells/cellsLabel/CellsLabels.ts
  quadratic-client/src/app/gridGL/cells/cellsLabel/CellsTextHash.ts
  quadratic-client/src/app/quadratic-core-types/index.d.ts
  quadratic-client/src/app/web-workers/quadraticCore/coreClientMessages.ts
  quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/rustCallbacks.ts
  quadratic-client/src/app/web-workers/renderWebWorker/renderClientMessages.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHash.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHashContent.test.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHashContent.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/renderClient.ts
  quadratic-client/src/routes/file.$uuid.tsx
  quadratic-core/src/a1/a1_context/table_map.rs
  quadratic-core/src/bin/export_types.rs
  quadratic-core/src/controller/active_transactions/pending_transaction.rs
  quadratic-core/src/controller/execution/execute_operation/execute_sheets.rs
  quadratic-core/src/controller/send_render.rs
  quadratic-core/src/grid/data_table/empty_check.rs
  quadratic-core/src/grid/sheet/columns.rs
  quadratic-core/src/grid/sheet/data_tables/cache.rs
  quadratic-core/src/grid/sheet/data_tables/mod.rs
  quadratic-core/src/grid/sheet/rendering/cache.rs
  quadratic-core/src/grid/sheet/rendering/mod.rs
  quadratic-core/src/input/has_content.rs
  quadratic-core/src/input/jump.rs
  quadratic-core/src/input/mod.rs
  quadratic-core/src/input/move_cursor.rs
  quadratic-core/src/input/traverse.rs
  quadratic-core/src/lib.rs
  quadratic-core/src/values/array.rs
  quadratic-core/src/values/empty_values_cache.rs
  quadratic-core/src/values/mod.rs
  quadratic-core/src/wasm_bindings/controller/mod.rs
  quadratic-core/src/wasm_bindings/input.rs
  quadratic-core/src/wasm_bindings/js.rs
  quadratic-core/src/wasm_bindings/mod.rs
  quadratic-core/src/wasm_bindings/sheet_content_cache.rs
  quadratic-core/src/wasm_bindings/sheet_data_tables_cache.rs
Labels: cla-signed, prototype

#3044 Fix chart size bug
  quadratic-client/src/app/gridGL/HTMLGrid/htmlCells/HtmlCellResizing.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerImages.ts
  quadratic-client/src/app/web-workers/quadraticCore/coreClientMessages.ts
  quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
  quadratic-core/src/controller/execution/run_code/mod.rs
  quadratic-core/src/controller/operations/cell_value.rs
  quadratic-core/src/controller/operations/clipboard.rs
  quadratic-core/src/wasm_bindings/controller/formatting.rs
Labels: cla-signed, status: ready to merge, QA, e2e

#3034 fix: retry ai request with backup model
  quadratic-api/package.json
  quadratic-api/src/ai/handler/ai.handler.ts
  quadratic-api/src/ai/handler/anthropic.handler.ts
  quadratic-api/src/ai/handler/bedrock.handler.ts
  quadratic-api/src/ai/handler/openai.handler.ts
  quadratic-api/src/ai/handler/vertexai.handler.ts
  quadratic-api/src/ai/helpers/modelRouter.helper.ts
  quadratic-api/src/env-vars.ts
  quadratic-shared/ai/models/AI_MODELS.ts
Labels: cla-signed, status: ready for code review, status: ready for user test, QA

#3047 Temporary router changes
  Cargo.toml
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-api/src/ai/helpers/modelRouter.helper.ts
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/ai/models/AI_MODELS.ts
  quadratic-shared/ai/specs/aiToolsSpec.ts
  quadratic-shared/package.json
  quadratic-shared/typesAndSchemasAI.ts
Labels: cla-signed

#3049 chore: add shimmer animation to web search loading state
  quadratic-client/src/app/ai/toolCards/ToolCardQuery.tsx
  quadratic-client/src/app/ai/toolCards/WebSearch.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystMessages.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/AIAssistant/AIAssistantMessages.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/AIAssistant/GoogleSearchSources.tsx
  quadratic-shared/ai/models/AI_MODELS.ts
  quadratic-shared/typesAndSchemasAI.ts
Labels: cla-signed, status: ready for code review, status: ready for user test

#3075 fix: pin genai to 1.4
  Cargo.toml
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: cla-signed

#3076 Main
  Cargo.toml
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: cla-signed

#3066 chore: migrate radixui to selectable imports
  quadratic-client/package.json
  quadratic-client/src/app/ui/components/BorderMenu.tsx
  quadratic-client/src/app/ui/menus/Toolbar/FormattingBar.tsx
  quadratic-client/src/shared/shadcn/ui/accordion.tsx
  quadratic-client/src/shared/shadcn/ui/alert-dialog.tsx
  quadratic-client/src/shared/shadcn/ui/button.tsx
  quadratic-client/src/shared/shadcn/ui/checkbox.tsx
  quadratic-client/src/shared/shadcn/ui/collapsible.tsx
  quadratic-client/src/shared/shadcn/ui/command.tsx
  quadratic-client/src/shared/shadcn/ui/dialog.tsx
  quadratic-client/src/shared/shadcn/ui/dropdown-menu.tsx
  quadratic-client/src/shared/shadcn/ui/form.tsx
  quadratic-client/src/shared/shadcn/ui/hover-card.tsx
  quadratic-client/src/shared/shadcn/ui/label.tsx
  quadratic-client/src/shared/shadcn/ui/menubar.tsx
  quadratic-client/src/shared/shadcn/ui/popover.tsx
  quadratic-client/src/shared/shadcn/ui/progress.tsx
  quadratic-client/src/shared/shadcn/ui/radio-group.tsx
  quadratic-client/src/shared/shadcn/ui/select.tsx
  quadratic-client/src/shared/shadcn/ui/separator.tsx
  quadratic-client/src/shared/shadcn/ui/sheet.tsx
  quadratic-client/src/shared/shadcn/ui/slider.tsx
  quadratic-client/src/shared/shadcn/ui/switch.tsx
  quadratic-client/src/shared/shadcn/ui/tabs.tsx
  quadratic-client/src/shared/shadcn/ui/toggle.tsx
  quadratic-client/src/shared/shadcn/ui/tooltip.tsx
Labels: cla-signed, status: ready to merge

#3059 Limits text rendering to 1000 characters
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts
Labels: cla-signed, status: ready to merge

#3055 Less aggressive clean up for AI
  quadratic-shared/ai/helpers/message.helper.ts
  quadratic-shared/ai/specs/aiToolsSpec.ts
Labels: status: ready to merge

#3080 fix: memory leak / execessive rendering
  quadratic-client/src/app/ai/hooks/useVisibleContextMessages.tsx
  quadratic-client/src/app/ai/toolCards/SetCodeCellValue.tsx
  quadratic-client/src/app/grid/sheet/Sheet.ts
  quadratic-client/src/app/grid/sheet/SheetCursor.ts
  quadratic-client/src/app/grid/sheet/selection.ts
  quadratic-client/src/app/gridGL/UI/UIValidations.ts
  quadratic-client/src/app/ui/components/SheetRange.tsx
  quadratic-client/src/app/ui/menus/Validations/Validations/ValidationEntry.tsx
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsLabels.ts
Labels: cla-signed, status: ready to merge

#3069 chore: add thinking support for genai sdk
  quadratic-api/package.json
  quadratic-api/src/ai/handler/ai.handler.ts
  quadratic-api/src/ai/handler/genai.handler.ts
  quadratic-api/src/ai/helpers/genai.helper.ts
  quadratic-api/src/ai/helpers/modelRouter.helper.ts
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystMessages.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/AIAssistant/AIAssistantMessages.tsx
  quadratic-shared/ai/helpers/model.helper.ts
  quadratic-shared/ai/models/AI_MODELS.ts
  quadratic-shared/ai/models/AI_RATES.ts
  quadratic-shared/ai/specs/aiToolsSpec.ts
  quadratic-shared/typesAndSchemasAI.ts
Labels: cla-signed, status: ready to merge, QA

#3058 Allows hyphens in table names and columns
  quadratic-core/src/controller/operations/csv.rs
  quadratic-core/src/controller/operations/import.rs
  quadratic-core/src/controller/user_actions/import.rs
  quadratic-core/src/grid/data_table/column_header.rs
  quadratic-core/src/grid/data_table/fix_names.rs
  quadratic-core/src/grid/data_table/mod.rs
  quadratic-core/src/input/has_content.rs
  quadratic-core/src/input/jump.rs
  quadratic-rust-shared/data/csv/encoding_issue.csv
  quadratic-rust-shared/data/csv/test-special-character$.csv
Labels: cla-signed, status: ready to merge, QA

#2922 Properly handle absolute rows and absolute columns
  quadratic-core/src/a1/a1_selection/exclude.rs
  quadratic-core/src/a1/a1_selection/select.rs
  quadratic-core/src/a1/cell_ref_coord.rs
  quadratic-core/src/a1/cell_ref_end.rs
  quadratic-core/src/a1/cell_ref_range/mutate.rs
  quadratic-core/src/a1/ref_range_bounds/create.rs
  quadratic-core/src/a1/ref_range_bounds/translate.rs
  quadratic-core/src/controller/formula.rs
  quadratic-core/src/controller/user_actions/auto_complete.rs
  quadratic-core/src/grid/code_cell.rs
  quadratic-core/src/test_util/print_sheet.rs
  quadratic-core/src/util.rs
Labels: cla-signed, status: ready to merge, QA, e2e

#3079 Adds debug option to show viewport coordinates
  quadratic-client/src/app/debugFlags/debugFlagsDefinitions.ts
  quadratic-client/src/app/ui/menus/BottomBar/BottomBar.tsx
  quadratic-client/src/app/ui/menus/BottomBar/Coordinates.tsx
Labels: cla-signed, status: ready to merge, QA

#3068 Run selection code cells buttons
  quadratic-client/src/app/actions/codeActionsSpec.ts
  quadratic-client/src/app/gridGL/HTMLGrid/contextMenus/GridContextMenuCell.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/contextMenus/GridContextMenuCodeTable.tsx
  quadratic-client/src/app/gridGL/cells/CellsSheets.ts
  quadratic-client/src/app/gridGL/cells/tables/Tables.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
  quadratic-client/src/app/ui/menus/BottomBar/KernelMenu.tsx
  quadratic-client/src/app/ui/menus/CommandPalette/commands/Code.tsx
  quadratic-client/src/app/web-workers/quadraticCore/coreClientMessages.ts
  quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
  quadratic-core/src/controller/execution/execute_operation/execute_col_rows.rs
  quadratic-core/src/controller/operations/code_cell.rs
  quadratic-core/src/controller/user_actions/code.rs
  quadratic-core/src/grid/sheet/data_tables/cache.rs
  quadratic-core/src/wasm_bindings/controller/code.rs
  quadratic-core/src/wasm_bindings/js_selection/mod.rs
  quadratic-core/src/wasm_bindings/sheet_data_tables_cache.rs
Labels: cla-signed, status: ready to merge, QA

#2808 dev: UI for turning debugging on/off
  quadratic-client/src/app/ai/components/SelectAIModelMenu.tsx
  quadratic-client/src/app/ai/hooks/useAIModel.tsx
  quadratic-client/src/app/atoms/gridSettingsAtom.ts
  quadratic-client/src/app/debugFlags.ts
  quadratic-client/src/app/debugFlags/debugFlags.ts
  quadratic-client/src/app/debugFlags/debugFlagsDefinitions.ts
  quadratic-client/src/app/debugFlags/useDebugFlags.ts
  quadratic-client/src/app/events/events.ts
  quadratic-client/src/app/gridGL/cells/CellsSheets.ts
  quadratic-client/src/app/gridGL/cells/cellsLabel/CellsLabels.ts
  quadratic-client/src/app/gridGL/helpers/debugPerformance.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardViewport.ts
  quadratic-client/src/app/gridGL/loadAssets.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
  quadratic-client/src/app/gridGL/pixiApp/Update.ts
  quadratic-client/src/app/gridGL/pixiApp/thumbnail.ts
  quadratic-client/src/app/gridGL/pixiApp/urlParams/urlParams.ts
  quadratic-client/src/app/ui/QuadraticAppDebugSettings.tsx
  quadratic-client/src/app/ui/components/AIUserMessageForm.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystMessages.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/hooks/useSubmitAIAnalystPrompt.tsx
  quadratic-client/src/app/ui/menus/BottomBar/BottomBar.tsx
  quadratic-client/src/app/ui/menus/BottomBar/Coordinates.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/AIAssistant/AIAssistantMessages.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorBody.tsx
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascriptClient.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascriptCore.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayer.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/worker/multiplayer.worker.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/worker/multiplayerClient.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/worker/multiplayerCore.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/worker/multiplayerServer.ts
  quadratic-client/src/app/web-workers/pythonLanguageServer/worker.ts
  quadratic-client/src/app/web-workers/pythonWebWorker/worker/python.ts
  quadratic-client/src/app/web-workers/pythonWebWorker/worker/pythonClient.ts
  quadratic-client/src/app/web-workers/pythonWebWorker/worker/pythonCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.worker.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreConnection.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreJavascript.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreMultiplayer.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/corePython.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreRender.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/offline.ts
  quadratic-client/src/app/web-workers/renderWebWorker/renderWebWorker.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsLabels.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHash.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/LabelMeshEntry.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/render.worker.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/renderClient.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/renderCore.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/renderText.ts
  quadratic-client/src/routes/file.$uuid.tsx
  quadratic-client/src/routes/files.shared-with-me.tsx
  quadratic-client/src/routes/teams.$teamUuid.files.private.tsx
  quadratic-client/src/shared/hooks/useRemoveInitialLoadingUI.ts
  quadratic-client/src/shared/shadcn/ui/sheet.tsx
  quadratic-client/src/shared/utils/analytics.ts
Labels: cla-signed, status: ready to merge, QA

#3096 fix: example files with prompt in query param
  quadratic-client/src/app/ui/hooks/useFileImport.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBarMenus/FileMenubarMenu.tsx
  quadratic-client/src/dashboard/components/FilesListItem.tsx
  quadratic-client/src/dashboard/components/ImportProgressList.tsx
  quadratic-client/src/routes/api.files.$uuid.ts
  quadratic-client/src/routes/examples.tsx
  quadratic-client/src/routes/file.$uuid.duplicate.tsx
  quadratic-client/src/routes/file.$uuid.history.tsx
  quadratic-client/src/routes/files.create.tsx
  quadratic-client/src/routes/teams.$teamUuid.files.create.tsx
  quadratic-client/src/shared/components/ShareDialog.tsx
  quadratic-client/src/shared/constants/routes.ts
Labels: cla-signed, status: ready to merge, QA

#3102 Revert router
  quadratic-api/src/ai/helpers/modelRouter.helper.ts
  quadratic-shared/ai/specs/aiToolsSpec.ts
Labels: cla-signed

#3103 chore: bump version 0.11.3
  Cargo.toml
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: cla-signed

#3110 fix: launch template name conflict
  infra/api/api.ts
  infra/connection/connection.ts
  quadratic-core/Cargo.toml
Labels: cla-signed, status: ready for code review

#3112 revert: api to aws
  .github/workflows/production-deploy.yml
  .github/workflows/qa-deploy.yml
  docker-compose.yml
  infra/api/api.ts
  infra/api/api_network.ts
  infra/connection/connection.ts
  infra/connection/connection_network.ts
  infra/files/files.ts
  infra/index.ts
  infra/multiplayer/multiplayer.ts
  infra/package.json
  quadratic-api/Dockerfile
  quadratic-api/package.json
  quadratic-api/src/app.ts
Labels: cla-signed, status: ready for code review

#3113 infra: api to aws
  .github/workflows/production-deploy.yml
  .github/workflows/qa-deploy.yml
  docker-compose.yml
  infra/api/api.ts
  infra/api/api_network.ts
  infra/connection/connection.ts
  infra/connection/connection_network.ts
  infra/files/files.ts
  infra/index.ts
  infra/multiplayer/multiplayer.ts
  infra/package.json
  quadratic-api/Dockerfile
  quadratic-api/package.json
  quadratic-api/src/app.ts
Labels: cla-signed

#3116 fix: revert rename pulumi assets
  infra/api/api_network.ts
  infra/connection/connection_network.ts
Labels: cla-signed

#3118 fix: revert mp nlb rename
  infra/multiplayer/multiplayer.ts
Labels: cla-signed

#3120 revert: api to aws
  .github/workflows/production-deploy.yml
  .github/workflows/qa-deploy.yml
  docker-compose.yml
  infra/api/api.ts
  infra/api/api_network.ts
  infra/connection/connection.ts
  infra/connection/connection_network.ts
  infra/files/files.ts
  infra/index.ts
  infra/multiplayer/multiplayer.ts
  infra/package.json
  quadratic-api/Dockerfile
  quadratic-api/package.json
  quadratic-api/src/app.ts
Labels: cla-signed

#3121 infra: api to aws
  .github/workflows/production-deploy.yml
  .github/workflows/qa-deploy.yml
  docker-compose.yml
  infra/api/api.ts
  infra/api/api_network.ts
  infra/connection/connection.ts
  infra/connection/connection_network.ts
  infra/files/files.ts
  infra/index.ts
  infra/multiplayer/multiplayer.ts
  infra/package.json
  quadratic-api/Dockerfile
  quadratic-api/package.json
  quadratic-api/src/app.ts
Labels: cla-signed

#3123 fix: sed quote removal for pulumi env
  .github/workflows/production-deploy.yml
  .github/workflows/qa-deploy.yml
  infra/helpers/runDockerImageBashScript.ts
Labels: cla-signed, status: ready for code review

#3125 fix: demo connection env parsing
  quadratic-api/src/data/connections.ts
Labels: cla-signed

#3128 infra: make api warm pool size a pulumi env
  Cargo.toml
  VERSION
  infra/api/api.ts
  package.json
  quadratic-api/package.json
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: cla-signed, status: ready for code review

#3067 Animate viewport
  quadratic-client/src/app/gridGL/UI/gridHeadings/GridHeadings.ts
  quadratic-client/src/app/gridGL/cells/tables/Tables.ts
  quadratic-client/src/app/gridGL/interaction/viewportHelper.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
  quadratic-client/src/app/gridGL/pixiApp/Viewport.ts.deprecated
Labels: cla-signed, status: ready to merge

#3098 Support xls, xlsx, xla, xlsm, xlam, xlsb, and ods in core
  quadratic-core/src/controller/operations/import.rs
  quadratic-core/test-files/simple.xls
  quadratic-rust-shared/data/excel/problem.xls
  quadratic-rust-shared/data/excel/simple.xls
Labels: cla-signed, status: ready to merge

#3030 dev: use growable SharedArrayBuffer for getCells
  .vscode/settings.json
  quadratic-client/src/app/gridGL/HTMLGrid/htmlCells/HtmlCell.ts
  quadratic-client/src/app/gridGL/HTMLGrid/htmlCells/HtmlCellResizing.ts
  quadratic-client/src/app/gridGL/cells/cellsLabel/LabelMeshEntry.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
  quadratic-client/src/app/gridGL/pixiApp/Update.ts
  quadratic-client/src/app/gridGL/pixiApp/thumbnail.ts
  quadratic-client/src/app/ui/hooks/useFileImport.tsx
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascript.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascriptRunnerMessages.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/generateJavascriptForRunner.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/generatedJavascriptForEditor.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/javascriptLibrary.ts
  quadratic-client/src/app/web-workers/pythonWebWorker/pythonCoreMessages.ts
  quadratic-client/src/app/web-workers/pythonWebWorker/worker/pythonCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/coreClientMessages.ts
  quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/corePython.ts
  quadratic-core/src/controller/execution/execute_operation/execute_borders.rs
  quadratic-core/src/controller/execution/execute_operation/execute_code.rs
  quadratic-core/src/controller/execution/execute_operation/execute_data_table.rs
  quadratic-core/src/controller/execution/execute_operation/execute_formats.rs
  quadratic-core/src/controller/execution/execute_operation/execute_offsets.rs
  quadratic-core/src/controller/execution/execute_operation/execute_sheets.rs
  quadratic-core/src/controller/execution/execute_operation/execute_values.rs
  quadratic-core/src/wasm_bindings/controller/mod.rs
  quadratic-core/src/wasm_bindings/controller/render.rs
  quadratic-core/src/wasm_bindings/controller/sheet_offsets.rs
  quadratic-core/src/wasm_bindings/controller/worker.rs
Labels: cla-signed, type: dev

#3101 feat: cross domain file transfer using iframe
  .github/workflows/preview-build-deploy-test.yml
  .github/workflows/production-deploy.yml
  .github/workflows/qa-deploy.yml
  .vscode/settings.json
  quadratic-client/src/app/ai/components/SelectAIModelMenu.tsx
  quadratic-client/src/app/ai/iframeAiChatFiles/FilesFromIframe.ts
  quadratic-client/src/app/ai/iframeAiChatFiles/IframeAiChatFiles.ts
  quadratic-client/src/app/ai/iframeAiChatFiles/IframeMessages.ts
  quadratic-client/src/app/events/events.ts
  quadratic-client/src/app/gridGL/PixiAppEffects.tsx
  quadratic-client/src/app/gridGL/pixiApp/PixiAppSettings.ts
  quadratic-client/src/app/gridGL/pixiApp/urlParams/UrlParamsUser.ts
  quadratic-client/src/app/helpers/files.ts
  quadratic-client/src/app/ui/components/AIContext.tsx
  quadratic-client/src/app/ui/components/AIUserMessageForm.tsx
  quadratic-client/src/app/ui/components/AIUserMessageFormAttachFileButton.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalyst.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystGetChatName.tsx
  quadratic-client/src/app/web-workers/quadraticCore/coreClientMessages.ts
  quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/rustCallbacks.ts
  quadratic-client/src/dashboard/atoms/filesImportProgressAtom.ts
  quadratic-client/src/router.tsx
  quadratic-client/src/routes/files.create.tsx
  quadratic-client/src/routes/iframe-indexeddb.tsx
  quadratic-client/src/routes/teams.$teamUuid.files.create.tsx
  quadratic-client/src/shared/constants/routes.ts
  quadratic-core/src/controller/send_render.rs
  quadratic-core/src/wasm_bindings/js.rs
  test/e2e/playwright.config.ts
Labels: cla-signed, status: ready for user test, QA

#3092 Current date in context
  quadratic-api/src/ai/handler/ai.handler.ts
  quadratic-api/src/ai/helpers/context.helper.ts
  quadratic-client/src/app/ui/menus/AIAnalyst/hooks/useSubmitAIAnalystPrompt.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/hooks/useSubmitAIAssistantPrompt.tsx
  quadratic-shared/typesAndSchemasAI.ts
Labels: cla-signed, status: ready to merge

#3135 chore: version bump 0.11.6
  Cargo.toml
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: cla-signed

#3105 Rerun pasted code cells when cells accessed are affected
  quadratic-core/src/a1/a1_selection/query.rs
  quadratic-core/src/controller/operations/clipboard.rs
  quadratic-core/src/grid/data_table/mod.rs
Labels: cla-signed, status: ready to merge

#3142 Implement arrays in postgres connector
  docker/postgres-connection/scripts/setup.sql
  quadratic-connection/Cargo.toml
  quadratic-connection/src/sql/postgres.rs
  quadratic-rust-shared/src/sql/mod.rs
  quadratic-rust-shared/src/sql/postgres_connection.rs
Labels: cla-signed
