Repository quadratichq/quadratic, pull requests merged in 2025-10, with the labels that each got.

#3492 Create playbook with deploying and modifying environment variables
  DEVELOPMENT.md
  PLAYBOOK.md
Labels: cla-signed, QA

#3494 feat: turn on sentry replay
  quadratic-client/src/shared/utils/sentry.ts
Labels: cla-signed, status: ready to merge, QA

#3495 Errors not getting caught on Max model (Vertex)
  quadratic-api/src/ai/handler/ai.handler.ts
Labels: cla-signed, status: ready for code review, status: ready for user test, QA

#3498 Remove magic code login method
  quadratic-api/src/auth/middleware/authRateLimiter.ts
  quadratic-api/src/auth/providers/auth.ts
  quadratic-api/src/auth/providers/workos.ts
  quadratic-api/src/auth/router/authRouter.ts
  quadratic-api/src/auth/routes/authenticate-with-magic-code.POST.ts
  quadratic-api/src/auth/routes/send-magic-auth-code.POST.ts
  quadratic-client/src/auth/auth.ts
  quadratic-client/src/auth/ory.ts
  quadratic-client/src/auth/workos.ts
  quadratic-client/src/router.tsx
  quadratic-client/src/routes/magic-auth-code.tsx
  quadratic-client/src/routes/send-magic-auth-code.tsx
  quadratic-client/src/shared/api/apiClient.ts
  quadratic-client/src/shared/components/auth/LoginForm.tsx
  quadratic-client/src/shared/components/auth/SendMagicAuthCode.tsx
  quadratic-client/src/shared/constants/routes.ts
  quadratic-shared/typesAndSchemas.ts
Labels: cla-signed, status: ready for user test

#3490 QA Sept 30th
  Cargo.toml
  DEVELOPMENT.md
  PLAYBOOK.md
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-api/src/ai/handler/ai.handler.ts
  quadratic-api/src/ai/handler/openai.chatCompletions.handler.ts
  quadratic-api/src/ai/handler/openai.responses.handler.ts
  quadratic-api/src/ai/helpers/anthropic.helper.ts
  quadratic-api/src/auth/middleware/authRateLimiter.ts
  quadratic-api/src/auth/providers/auth.ts
  quadratic-api/src/auth/providers/workos.ts
  quadratic-api/src/auth/router/authRouter.ts
  quadratic-api/src/auth/routes/authenticate-with-magic-code.POST.ts
  quadratic-api/src/auth/routes/send-magic-auth-code.POST.ts
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-client/src/auth/auth.ts
  quadratic-client/src/auth/ory.ts
  quadratic-client/src/auth/workos.ts
  quadratic-client/src/router.tsx
  quadratic-client/src/routes/magic-auth-code.tsx
  quadratic-client/src/routes/send-magic-auth-code.tsx
  quadratic-client/src/shared/api/apiClient.ts
  quadratic-client/src/shared/components/auth/LoginForm.tsx
  quadratic-client/src/shared/components/auth/SendMagicAuthCode.tsx
  quadratic-client/src/shared/components/connections/ConnectionFormSemantic.tsx
  quadratic-client/src/shared/constants/routes.ts
  quadratic-client/src/shared/utils/sentry.ts
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
  quadratic-shared/typesAndSchemas.ts
Labels: cla-signed

#3503 fix: update sentry replays to exclude iframe
  quadratic-client/src/shared/utils/sentry.ts
Labels: cla-signed, status: ready for code review, status: ready for user test

#3481 Fix various bugs in Find
  quadratic-client/src/app/ui/components/Search.tsx
  quadratic-client/src/app/ui/menus/SheetBar/SheetBarTab.tsx
  test/e2e/data/Airports distance (example).grid
  test/e2e/src/helpers/sheet.helper.ts
  test/e2e/src/spreadsheetFind.spec.ts
  test/e2e/src/spreadsheetFind.spec.ts-snapshots/search-viewport-updates-when-reverse-searching-0-chromium.png
  test/e2e/src/spreadsheetFind.spec.ts-snapshots/search-viewport-updates-when-reverse-searching-1-chromium.png
  test/e2e/src/spreadsheetFind.spec.ts-snapshots/search-viewport-updates-when-reverse-searching-2-chromium.png
  test/e2e/src/spreadsheetFind.spec.ts-snapshots/search-viewport-updates-when-reverse-searching-3-chromium.png
  test/e2e/src/spreadsheetFind.spec.ts-snapshots/search-viewport-updates-when-reverse-searching-4-chromium.png
  test/e2e/src/spreadsheetInteraction.spec.ts-snapshots/Case-Sensitive-Search-Match-chromium.png
  test/e2e/src/spreadsheetInteraction.spec.ts-snapshots/Match-Entire-Cell-Contents-Complete-Search-chromium.png
Labels: cla-signed, status: ready to merge

#3505 Attempted fix for localhost auth errors
  quadratic-api/src/auth/providers/workos.ts
  quadratic-client/src/auth/workos.ts
Labels: cla-signed, status: ready to merge, QA
