Repository quadratichq/quadratic, pull requests merged in 2025-03, with the labels that each got.

#2365 chore: remove mui avatars
  quadratic-client/src/routes/teams.$teamUuid.index.tsx
  quadratic-client/src/shared/components/Avatar.tsx
Labels: cla-signed, status: ready for code review, status: ready for user test

#2362 Fix floating column headers height
  quadratic-client/src/app/gridGL/cells/tables/TableColumnHeaders.ts
Labels: cla-signed, status: ready for user test

#2349 Allow mouse selection when scrolling the viewport at the edges
  quadratic-client/src/app/gridGL/interaction/pointer/PointerDown.ts
  quadratic-client/src/app/gridGL/interaction/viewportHelper.ts
  quadratic-client/src/app/gridGL/pixiApp/viewport/Viewport.ts
Labels: cla-signed, status: ready for code review

#2363 Revert Sheet 1 to Sheet1
  quadratic-api/src/data/current_blank.grid
  quadratic-core/src/a1/a1_context/mod.rs
  quadratic-core/src/a1/a1_selection/parse.rs
  quadratic-core/src/a1/a1_selection/query.rs
  quadratic-core/src/a1/a1_selection/select.rs
  quadratic-core/src/a1/cell_ref_range/create.rs
  quadratic-core/src/a1/cell_ref_range/to_table_ref.rs
  quadratic-core/src/a1/sheet_cell_ref_range.rs
  quadratic-core/src/a1/sheet_name.rs
  quadratic-core/src/controller/active_transactions/pending_transaction.rs
  quadratic-core/src/controller/execution/execute_operation/execute_sheets.rs
  quadratic-core/src/controller/execution/receive_multiplayer.rs
  quadratic-core/src/controller/execution/run_code/run_connection.rs
  quadratic-core/src/controller/operations/clipboard.rs
  quadratic-core/src/controller/operations/code_cell.rs
  quadratic-core/src/controller/operations/sheets.rs
  quadratic-core/src/controller/sheets.rs
  quadratic-core/src/controller/user_actions/sheets.rs
  quadratic-core/src/formulas/lexer.rs
  quadratic-core/src/grid/code_cell.rs
  quadratic-core/src/grid/data_table/mod.rs
  quadratic-core/src/grid/file/migrate_code_cell_references.rs
  quadratic-core/src/grid/file/mod.rs
  quadratic-core/src/grid/file/v1_3/file.rs
  quadratic-core/src/grid/selection.rs
  quadratic-core/src/grid/sheet.rs
  quadratic-core/src/grid/sheets.rs
  quadratic-core/src/util.rs
  quadratic-rust-shared/data/grid/current_blank.grid
Labels: cla-signed

#2359 fix: make "copy link" correct from the dashboard
  quadratic-client/src/shared/components/ShareDialog.tsx
Labels: cla-signed, status: ready for code review, status: ready for user test

#2250 fix: save active sheet state in URL
  quadratic-client/src/app/grid/controller/Sheets.ts
  quadratic-client/src/app/ui/menus/SheetBar/SheetBar.tsx
  quadratic-client/src/shared/constants/routes.ts
Labels: cla-signed, status: ready for code review, status: ready for user test, QA

#2357 fix: add csp header to allow iframe embed
  amplify.yml
  docker/client/config/default.conf
Labels: cla-signed, status: ready for code review, QA

#2350 fix: update sheet name in cell ref on duplicate sheet
  quadratic-core/src/controller/execution/execute_operation/execute_sheets.rs
  quadratic-core/src/controller/operations/sheets.rs
Labels: cla-signed, QA

#2376 Fixes resizing grid column when mouse moves over table UI
  quadratic-client/src/app/gridGL/interaction/pointer/Pointer.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerHeading.ts
Labels: cla-signed, QA

#2361 Fix table selection
  quadratic-client/src/app/actions/selectionActionsSpec.ts
  quadratic-client/src/app/grid/sheet/SheetCursor.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorKeyboard.ts
  quadratic-client/src/app/gridGL/HTMLGrid/validations/HtmlValidationList.tsx
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardPosition.ts
  quadratic-client/src/app/gridGL/interaction/pointer/Pointer.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerDown.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerTable.ts
  quadratic-client/src/app/gridGL/interaction/pointer/doubleClickCell.ts
  quadratic-client/src/app/gridGL/interaction/viewportHelper.ts
  quadratic-client/src/app/gridGL/pixiApp/urlParams/UrlParamsUser.ts
  quadratic-client/src/app/ui/menus/GoTo/GoTo.tsx
  quadratic-core/src/a1/a1_selection/query.rs
  quadratic-core/src/a1/a1_selection/select.rs
  quadratic-core/src/a1/a1_selection/select_table.rs
  quadratic-core/src/a1/js_selection/select.rs
  quadratic-core/src/a1/table_ref/convert.rs
  quadratic-core/src/a1/table_ref/query.rs
  quadratic-core/src/controller/execution/execute_operation/execute_move_cells.rs
Labels: cla-signed, status: ready for code review, status: ready for user test, QA

#2373 feat: add function call to code chat (fix with ai flow)
  .github/workflows/ci.yml
  .github/workflows/preview-build-deploy-images.yml
  quadratic-api/src/ai/helpers/anthropic.helper.ts
  quadratic-api/src/ai/helpers/bedrock.helper.ts
  quadratic-api/src/ai/helpers/context.helper.ts
  quadratic-api/src/ai/helpers/openai.helper.ts
  quadratic-api/src/routes/v0/ai.chat.POST.test.ts
  quadratic-api/src/routes/v0/ai.chat.POST.ts
  quadratic-client/src/app/actions/insertActionsSpec.ts
  quadratic-client/src/app/ai/components/SelectAIModelMenu.tsx
  quadratic-client/src/app/ai/hooks/useAIModel.tsx
  quadratic-client/src/app/ai/hooks/useAIRequestToAPI.tsx
  quadratic-client/src/app/ai/hooks/useCodeCellContextMessages.tsx
  quadratic-client/src/app/ai/hooks/useGetChatName.tsx
  quadratic-client/src/app/ai/toolCards/AddDataTable.tsx
  quadratic-client/src/app/ai/toolCards/DeleteCells.tsx
  quadratic-client/src/app/ai/toolCards/MoveCells.tsx
  quadratic-client/src/app/ai/toolCards/SetCellValues.tsx
  quadratic-client/src/app/ai/toolCards/SetCodeCellValue.tsx
  quadratic-client/src/app/ai/toolCards/ToolCard.tsx
  quadratic-client/src/app/ai/toolCards/UpdateCodeCell.tsx
  quadratic-client/src/app/ai/tools/aiToolsActions.ts
  quadratic-client/src/app/atoms/codeEditorAtom.ts
  quadratic-client/src/app/grid/actions/openCodeEditor.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
  quadratic-client/src/app/gridGL/PixiAppEffects.tsx
  quadratic-client/src/app/gridGL/interaction/pointer/PointerTable.ts
  quadratic-client/src/app/gridGL/interaction/pointer/doubleClickCell.ts
  quadratic-client/src/app/ui/components/AIUserMessageForm.tsx
  quadratic-client/src/app/ui/components/Markdown.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalyst.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystChatHistory.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystContext.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystEffects.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystHeader.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystMessages.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystSelectContextMenu.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystToolCard.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystUserMessageForm.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIThinkingBlock.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/hooks/useSubmitAIAnalystPrompt.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/AIAssistant/AIAssistant.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/AIAssistant/AIAssistantMessages.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/AIAssistant/AIAssistantUserMessageForm.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/AIAssistant/AICodeBlockParser.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/AIAssistant/CodeSnippet.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorBody.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorEffects.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/hooks/useSubmitAIAssistantPrompt.tsx
  quadratic-client/src/shared/components/Icons.tsx
  quadratic-client/src/shared/hooks/useThemeAccentColor.tsx
  quadratic-client/src/shared/hooks/useThemeAppearanceMode.tsx
  quadratic-client/src/shared/shadcn/ui/textarea.tsx
  quadratic-shared/ai/helpers/model.helper.ts
  quadratic-shared/ai/models/AI_MODELS.ts
  quadratic-shared/ai/specs/aiToolsSpec.ts
  quadratic-shared/typesAndSchemasAI.ts
Labels: cla-signed, status: ready for user test, QA

#2393 bump version
  Cargo.toml
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-client/package.json
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-client/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: cla-signed

#2388 Fix AI docs tables mistake
  quadratic-api/src/ai/docs/PythonDocs.ts
Labels: cla-signed, status: ready for code review

#2391 Docs update for AI to not try to stick formulas/code into tables
  quadratic-api/src/ai/docs/QuadraticDocs.ts
  quadratic-shared/ai/specs/aiToolsSpec.ts
Labels: cla-signed

#2390 AI can set values in a data table + refactors
  Cargo.lock
  package-lock.json
  quadratic-client/src/app/gridGL/interaction/pointer/PointerDown.ts
  quadratic-core/src/controller/execution/auto_resize_row_heights.rs
  quadratic-core/src/controller/execution/execute_operation/execute_data_table.rs
  quadratic-core/src/controller/operations/cell_value.rs
  quadratic-core/src/controller/operations/clipboard.rs
  quadratic-core/src/controller/operations/code_cell.rs
  quadratic-core/src/controller/user_actions/cells.rs
  quadratic-core/src/grid/data_table/mod.rs
  quadratic-core/src/grid/sheet.rs
  quadratic-core/src/grid/sheet/code.rs
  quadratic-core/src/values/cell_values.rs
  quadratic-core/src/wasm_bindings/controller/cells.rs
Labels: cla-signed, status: ready for user test, QA

#2399 Fix phantom click
  quadratic-client/src/app/gridGL/interaction/pointer/PointerDown.ts
Labels: cla-signed

#2397 AI shouldn't try to explain the data or code its generating in the chat
  quadratic-api/src/ai/docs/QuadraticDocs.ts
Labels: cla-signed, status: ready for user test

#2411 Temp disable auto expansion
  quadratic-core/src/controller/operations/cell_value.rs
  quadratic-core/src/controller/user_actions/cells.rs
Labels: cla-signed

#2410 fix: empty edit cell
  quadratic-core/src/controller/execution/execute_operation/execute_data_table.rs
  quadratic-core/src/grid/sheet/cell_array.rs
Labels: cla-signed

#2424 fix: font loading
  quadratic-client/index.html
  quadratic-client/src/app/ui/components/InitialPageLoadError.tsx
  quadratic-client/src/shared/components/Icons.tsx
  quadratic-client/src/shared/components/icons.css
Labels: cla-signed, status: ready for code review, status: ready for user test

#2425 chore: remove unused code
  quadratic-client/src/app/ui/components/LinkNewTab.tsx
  quadratic-client/src/app/ui/menus/CellTypeMenu/CellTypeMenu.tsx
Labels: cla-signed, status: ready for code review, status: ready for user test

#2392 infra: use docker build action
  .github/workflows/preview-build-deploy-images.yml
  quadratic-client/Dockerfile
  quadratic-client/src/app/web-workers/pythonWebWorker/worker/python.test.ts
Labels: cla-signed, status: ready for code review

#2443 Fixes marching ants luminosity
  quadratic-client/src/app/gridGL/UI/UICopy.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
Labels: cla-signed, status: ready for code review, status: ready for user test

#2442 fix: avatar spacing
  quadratic-client/src/shared/components/Avatar.tsx
Labels: status: open question, cla-signed, status: ready for code review, status: ready for user test

#2457 Add issue templates & PR template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: cla-signed, status: ready to merge

#2460 Fix code peek
  quadratic-client/src/app/gridGL/HTMLGrid/hoverCell/HoverCell.tsx
  quadratic-client/src/app/gridGL/cells/tables/Tables.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiAppSettings.ts
Labels: cla-signed, status: ready to merge

#2464 infra: disable global accelerator for previews
  infra/aws-cloudformation/quadratic-preview.yml
Labels: cla-signed

#2416 Programmatically set sheet name
  quadratic-api/src/data/current_blank.grid
  quadratic-core/src/constants.rs
  quadratic-core/src/controller/execution/execute_operation/execute_sheets.rs
  quadratic-core/src/controller/execution/run_code/run_connection.rs
  quadratic-core/src/controller/operations/code_cell.rs
  quadratic-core/src/controller/operations/sheets.rs
  quadratic-core/src/controller/sheets.rs
  quadratic-core/src/controller/user_actions/sheets.rs
  quadratic-core/src/grid/selection.rs
  quadratic-core/src/grid/sheet.rs
  quadratic-core/src/grid/sheets.rs
  quadratic-core/src/lib.rs
  quadratic-rust-shared/data/grid/current_blank.grid
Labels: status: ready for user test, QA

#2447 Fixes column placement when toggling name
  quadratic-client/src/app/gridGL/cells/tables/TableColumnHeader.ts
  quadratic-client/src/app/gridGL/cells/tables/TableColumnHeaders.ts
Labels: cla-signed, status: ready to merge

#2461 Remove copy as png from HTML chart & fix chart image
  quadratic-client/public/images/chart-placeholder.png
  quadratic-client/src/app/gridGL/HTMLGrid/contextMenus/GridContextMenuCodeTableChart.tsx
  quadratic-client/src/app/gridGL/UI/HtmlPlaceholders.ts
  quadratic-client/src/app/gridGL/loadAssets.ts
  quadratic-client/src/app/gridGL/pixiApp/thumbnail.ts
  quadratic-client/src/app/theme/colors.ts
Labels: cla-signed, status: ready to merge

#2340 feat: move theme options out of labs
  quadratic-client/src/app/gridGL/HTMLGrid/EmptyGridMessage.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/HTMLGridContainer.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/SuggestionDropdown.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/htmlCells/HtmlCell.ts
  quadratic-client/src/app/gridGL/HTMLGrid/htmlCells/HtmlCells.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/InlineEditor.tsx
  quadratic-client/src/app/gridGL/QuadraticGrid.tsx
  quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
  quadratic-client/src/app/ui/components/Following.tsx
  quadratic-client/src/app/ui/components/ImportProgress.tsx
  quadratic-client/src/app/ui/components/ThemePickerMenu.tsx
  quadratic-client/src/dashboard/components/DashboardSidebar.tsx
  quadratic-client/src/dashboard/components/FileDragDrop.tsx
  quadratic-client/src/routes/account.tsx
  quadratic-client/src/routes/labs.tsx
  quadratic-client/src/shared/components/ThemeAccentColors.tsx
  quadratic-client/src/shared/components/ThemeAppearanceModes.tsx
  quadratic-client/src/shared/hooks/useFeatureFlag.tsx
  quadratic-client/src/shared/hooks/useThemeAccentColor.tsx
  quadratic-client/src/shared/hooks/useThemeAppearanceMode.tsx
  quadratic-client/src/shared/shadcn/styles.css
Labels: cla-signed, status: requested changes, QA

#2445 Allow renaming of Sheet names, tables, and columns w/only changes to case
  quadratic-client/src/app/gridGL/HTMLGrid/contextMenus/TableColumnHeaderRename.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/contextMenus/TableRename.tsx
  quadratic-client/src/app/ui/hooks/useRenameTableColumnName.tsx
  quadratic-client/src/app/ui/hooks/useRenameTableName.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorHeaderLabel.tsx
  quadratic-client/src/app/ui/menus/SheetBar/SheetBarTab.tsx
  quadratic-core/src/a1/a1_context/table_map.rs
  quadratic-core/src/a1/js_selection/validate_name.rs
  quadratic-core/src/controller/execution/execute_operation/execute_data_table.rs
  quadratic-core/src/controller/execution/execute_operation/execute_sheets.rs
  quadratic-core/src/grid/data_table/mod.rs
  quadratic-core/src/grid/sheet.rs
Labels: cla-signed, status: ready to merge

#2414 AI refs docs update
  quadratic-api/src/ai/docs/JavascriptDocs.ts
  quadratic-api/src/ai/docs/PythonDocs.ts
  quadratic-api/src/ai/docs/QuadraticDocs.ts
Labels: cla-signed, status: ready for user test, QA

#2446 Ensure that chart refs for formulas return blanks
  quadratic-core/src/a1/table_ref/convert.rs
  quadratic-core/src/grid/data_table/mod.rs
  quadratic-core/src/grid/sheet.rs
Labels: cla-signed, status: ready to merge

#2254 fix: update file updated date when a new checkpoint is made
  quadratic-api/src/routes/internal/checkpoint.$fileUuid.PUT.ts
Labels: cla-signed, status: requested changes, QA

#2270 Reintroduce Billing
  infra/aws-cloudformation/quadratic-preview.yml
  package-lock.json
  quadratic-api/package.json
  quadratic-api/prisma/migrations/20250211191943_optional_analytics_and_token_usage_and_message_type/migration.sql
  quadratic-api/prisma/schema.prisma
  quadratic-api/src/ai/handler/anthropic.ts
  quadratic-api/src/ai/handler/bedrock.ts
  quadratic-api/src/ai/handler/openai.ts
  quadratic-api/src/ai/helpers/anthropic.helper.ts
  quadratic-api/src/ai/helpers/bedrock.helper.ts
  quadratic-api/src/ai/helpers/openai.helper.ts
  quadratic-api/src/ai/usage.ts
  quadratic-api/src/internal/addUserToTeam.ts
  quadratic-api/src/internal/removeUserFromTeam.ts
  quadratic-api/src/routes/v0/ai.chat.POST.test.ts
  quadratic-api/src/routes/v0/ai.chat.POST.ts
  quadratic-api/src/routes/v0/teams.$uuid.GET.ts
  quadratic-api/src/routes/v0/teams.$uuid.PATCH.ts
  quadratic-api/src/routes/v0/teams.$uuid.billing.checkout.session.GET.ts
  quadratic-api/src/stripe/stripe.ts
  quadratic-client/src/app/ai/hooks/useAIRequestToAPI.tsx
  quadratic-client/src/app/ui/components/AIUserMessageForm.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystMessages.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/hooks/useSubmitAIAnalystPrompt.tsx
  quadratic-client/src/dashboard/components/DashboardSidebar.tsx
  quadratic-client/src/routes/teams.$teamUuid.settings.tsx
  quadratic-client/src/shared/constants/urls.ts
  quadratic-shared/ai/helpers/message.helper.ts
  quadratic-shared/ai/models/AI_MODELS.ts
  quadratic-shared/typesAndSchemas.ts
  quadratic-shared/typesAndSchemasAI.ts
Labels: cla-signed, status: ready for user test, QA

#2476 fix: table column wrap
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts
  quadratic-core/src/grid/sheet/rendering/cells.rs
Labels: cla-signed, status: ready to merge

#2486 remove legacy database tables
  quadratic-api/prisma/migrations/20250312165630_remove_unused_tables/migration.sql
  quadratic-api/prisma/schema.prisma
Labels: cla-signed, status: ready to merge, QA

#2488 better capture sentry errors
  quadratic-client/src/dashboard/components/BrowserCompatibilityLayoutRoute.tsx
  quadratic-client/src/dashboard/components/Empty.tsx
  quadratic-client/src/index.tsx
  quadratic-client/src/routes/_dashboard.tsx
  quadratic-client/src/routes/_root.tsx
  quadratic-client/src/routes/file.$uuid.tsx
  quadratic-client/src/routes/files.shared-with-me.tsx
  quadratic-client/src/routes/teams.$teamUuid.files.private.tsx
  quadratic-client/src/routes/teams.$teamUuid.tsx
Labels: cla-signed, status: ready to merge, QA

#2484 fix: table sort menu doesn't work when it is selected while cell is highlighted
  quadratic-client/src/app/atoms/contextMenuAtom.ts
  quadratic-client/src/app/events/events.ts
  quadratic-client/src/app/gridGL/HTMLGrid/contextMenus/tableSort/TableSort.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
  quadratic-client/src/app/gridGL/cells/tables/Tables.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiAppSettings.ts
Labels: cla-signed, status: ready to merge, QA

#2481 fix: - should go before $
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/convertNumber.test.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/convertNumber.ts
Labels: cla-signed, status: ready to merge, QA

#2480 Single cell code output has no table name
  Cargo.lock
  quadratic-client/src/app/actions/dataTableSpec.ts
  quadratic-core/src/controller/execution/auto_resize_row_heights.rs
  quadratic-core/src/controller/execution/receive_multiplayer.rs
  quadratic-core/src/controller/execution/run_code/mod.rs
  quadratic-core/src/controller/execution/run_code/run_formula.rs
  quadratic-core/src/controller/execution/run_code/run_javascript.rs
  quadratic-core/src/controller/execution/run_code/run_python.rs
  quadratic-core/src/grid/data_table/mod.rs
Labels: cla-signed, status: ready to merge, QA

#2470 fix: AddDataTable and GridToDataTable op
  quadratic-core/src/controller/execution/execute_operation/execute_data_table.rs
  quadratic-core/src/controller/execution/execute_operation/mod.rs
  quadratic-core/src/controller/user_actions/data_table.rs
Labels: cla-signed, status: ready to merge, QA

#2482 fix: resizing a grid column/row does not properly reset when pressing escape
  quadratic-client/src/app/gridGL/interaction/pointer/PointerHeading.ts
  quadratic-core/src/sheet_offsets/resize_transient.rs
Labels: cla-signed, status: ready to merge, QA

#2427 Combine data table operations in set cell values
  quadratic-client/src/app/ui/components/AIUserMessageForm.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalyst.tsx
  quadratic-core/src/controller/execution/auto_resize_row_heights.rs
  quadratic-core/src/controller/execution/execute_operation/execute_data_table.rs
  quadratic-core/src/controller/execution/execute_operation/mod.rs
  quadratic-core/src/controller/operations/cell_value.rs
  quadratic-core/src/controller/operations/code_cell.rs
  quadratic-core/src/controller/operations/operation.rs
  quadratic-core/src/controller/user_actions/cells.rs
  quadratic-core/src/controller/user_actions/data_table.rs
  quadratic-core/src/grid/data_table/column.rs
  quadratic-core/src/grid/sheet/data_table.rs
  quadratic-core/src/test_util.rs
  quadratic-core/src/values/cell_values.rs
  quadratic-core/src/values/cellvalue.rs
Labels: cla-signed, status: ready to merge, QA

#2493 Single finger mobile drag
  quadratic-client/src/app/gridGL/pixiApp/viewport/Viewport.ts
Labels: cla-signed, status: ready to merge, QA

#2496 improve the starting prompts
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystExamplePrompts.tsx
Labels: cla-signed, status: ready to merge, QA

#2503 Cleans up chart icons after thumbnail
  quadratic-client/src/app/gridGL/UI/HtmlPlaceholders.ts
Labels: status: ready to merge

#2501 infra: enable global accelerator for previews
  .github/workflows/preview-build-deploy-images.yml
  infra/aws-cloudformation/quadratic-preview.yml
Labels: cla-signed

#2502 Nit: Fix Hover Error + Click Cell, Error Disappears
  quadratic-client/src/app/gridGL/HTMLGrid/hoverCell/HoverCell.tsx
Labels: cla-signed, status: ready for code review, QA

#2491 Data missing when changing dataframe code cell to a single value
  quadratic-client/src/app/gridGL/cells/CellsMarkers.ts
  quadratic-client/src/app/gridGL/cells/tables/Table.ts
  quadratic-core/src/controller/execution/run_code/mod.rs
  quadratic-core/src/grid/data_table/mod.rs
Labels: cla-signed, status: requested changes

#2506 chore: version bump
  Cargo.lock
  Cargo.toml
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-client/package.json
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-client/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: cla-signed

#2430 infra: improve qa deployment
  .github/workflows/qa-close.yml
  .github/workflows/qa-deploy.yml
  .github/workflows/qa-wolf-notify.yml
  amplify.yml
  package-lock.json
  quadratic-client/Dockerfile
  vercel.json
Labels: cla-signed, status: ready for code review

#2512 fix: matrix build
  .github/workflows/qa-deploy.yml
Labels: cla-signed

#2513 fix: matri build again
  .github/workflows/qa-deploy.yml
Labels: cla-signed

#2500 infra: move production client to s3 + cloudflare
  .github/workflows/production-deploy.yml
  .github/workflows/production-publish-images.yml
  .github/workflows/qa-deploy.yml
Labels: cla-signed, status: ready for code review

#2517 chore: bump version
  Cargo.lock
  Cargo.toml
  VERSION
  package-lock.json
  package.json
  quadratic-api/package.json
  quadratic-client/package.json
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-client/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: cla-signed

#2508 QA: March 14th - Reserved for Client to Cloudflare Migration
  .github/workflows/production-deploy.yml
  .github/workflows/production-publish-images.yml
  .github/workflows/qa-close.yml
  .github/workflows/qa-deploy.yml
  .github/workflows/qa-wolf-notify.yml
  Cargo.lock
  Cargo.toml
  VERSION
  amplify.yml
  package-lock.json
  package.json
  quadratic-api/package.json
  quadratic-client/Dockerfile
  quadratic-client/package.json
  quadratic-client/src/app/ui/menus/BottomBar/BottomBar.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBar.tsx
  quadratic-client/src/shared/constants/appConstants.ts
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-client/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
  vercel.json
Labels: cla-signed

#2518 chore: add 5 min delay to qa wolf notify
  .github/workflows/qa-deploy.yml
Labels: cla-signed

#2511 Fix intermittent multiplayer test timeout
  quadratic-connection/package.json
  quadratic-files/package.json
  quadratic-multiplayer/package.json
  quadratic-multiplayer/src/server.rs
  quadratic-rust-shared/package.json
Labels: cla-signed, status: ready to merge

#2527 Billing Settings for Non Team Owner
  quadratic-client/src/dashboard/components/DashboardSidebar.tsx
  quadratic-client/src/routes/teams.$teamUuid.settings.tsx
Labels: cla-signed, status: ready for code review, status: ready for user test, QA

#2529 chore: upgrade to node 23
  .github/workflows/ci.yml
  .github/workflows/production-deploy.yml
  .github/workflows/qa-deploy.yml
  .nvmrc
  DEVELOPMENT.md
  Dockerfile.dev
  infra/package.json
  package-lock.json
  package.json
  quadratic-api/Dockerfile
  quadratic-api/package.json
  quadratic-client/Dockerfile
  quadratic-client/package.json
  quadratic-shared/package.json
Labels: cla-signed

#2515 Fix display of python dataframes, lists, and series as well as charts
  quadratic-core/src/controller/execution/run_code/mod.rs
  quadratic-core/src/grid/data_table/mod.rs
Labels: cla-signed

#2533 fix: update pulumi lock file
  infra/package-lock.json
Labels: cla-signed, status: ready to merge

#2504 feat: add GCP support - claude + gemini
  .env.docker
  docker-compose.yml
  infra/aws-cloudformation/quadratic-preview.yml
  package-lock.json
  quadratic-api/.env.test
  quadratic-api/package.json
  quadratic-api/src/ai/handler/anthropic.ts
  quadratic-api/src/ai/handler/bedrock.ts
  quadratic-api/src/ai/handler/openai.ts
  quadratic-api/src/ai/handler/vertexai.ts
  quadratic-api/src/ai/helpers/anthropic.helper.ts
  quadratic-api/src/ai/helpers/bedrock.helper.ts
  quadratic-api/src/ai/helpers/openai.helper.ts
  quadratic-api/src/ai/helpers/vertexai.helper.ts
  quadratic-api/src/ai/providers.ts
  quadratic-api/src/env-vars.ts
  quadratic-api/src/routes/v0/ai.chat.POST.ts
  quadratic-client/src/app/atoms/editorInteractionStateAtom.ts
  quadratic-client/src/app/grid/controller/Sheets.ts
  quadratic-client/src/app/gridGL/cells/tables/TableName.ts
  quadratic-client/src/shared/shadcn/utils.ts
  quadratic-shared/ai/helpers/model.helper.ts
  quadratic-shared/ai/models/AI_MODELS.ts
  quadratic-shared/ai/specs/aiToolsSpec.ts
  quadratic-shared/typesAndSchemasAI.ts
Labels: cla-signed, status: ready to merge

#2522 feat: add file support to ai chat
  quadratic-api/src/ai/handler/anthropic.ts
  quadratic-api/src/ai/handler/bedrock.ts
  quadratic-api/src/ai/handler/openai.ts
  quadratic-api/src/ai/handler/vertexai.ts
  quadratic-api/src/ai/helpers/anthropic.helper.ts
  quadratic-api/src/ai/helpers/bedrock.helper.ts
  quadratic-api/src/ai/helpers/context.helper.ts
  quadratic-api/src/ai/helpers/openai.helper.ts
  quadratic-api/src/ai/helpers/vertexai.helper.ts
  quadratic-api/src/ai/providers.ts
  quadratic-api/src/env-vars.ts
  quadratic-api/src/routes/v0/ai.chat.POST.test.ts
  quadratic-api/src/routes/v0/ai.chat.POST.ts
  quadratic-client/src/app/ai/hooks/useCodeCellContextMessages.tsx
  quadratic-client/src/app/ai/hooks/useCurrentSheetContextMessages.tsx
  quadratic-client/src/app/ai/hooks/useGetChatName.tsx
  quadratic-client/src/app/ai/hooks/useOtherSheetsContextMessages.tsx
  quadratic-client/src/app/ai/hooks/useSelectionContextMessages.tsx
  quadratic-client/src/app/ai/hooks/useTablesContextMessages.tsx
  quadratic-client/src/app/ai/hooks/useVisibleContextMessages.tsx
  quadratic-client/src/app/ai/offline/aiAnalystChats.test.ts
  quadratic-client/src/app/ai/offline/aiAnalystChats.ts
  quadratic-client/src/app/gridGL/HTMLGrid/hoverCell/HoverCell.tsx
  quadratic-client/src/app/gridGL/pixiApp/urlParams/UrlParamsUser.ts
  quadratic-client/src/app/ui/components/AIUserMessageForm.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystContext.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystExamplePrompts.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystMessages.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystUserMessageForm.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIThinkingBlock.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/hooks/useSubmitAIAnalystPrompt.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/AIAssistant/AIAssistantMessages.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/AIAssistant/AIAssistantUserMessageForm.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/ReturnTypeInspector.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/hooks/useSubmitAIAssistantPrompt.tsx
  quadratic-shared/ai/helpers/files.helper.ts
  quadratic-shared/ai/helpers/message.helper.ts
  quadratic-shared/typesAndSchemasAI.ts
Labels: cla-signed, status: ready to merge

#2534 Instruct Python (and JS) to not attempt to import/export files in code
  quadratic-api/src/ai/docs/JavascriptDocs.ts
  quadratic-api/src/ai/docs/PythonDocs.ts
Labels: cla-signed

#2538 fix: upgrade sentry
  .github/workflows/preview-build-deploy-images.yml
  package-lock.json
  quadratic-api/package.json
  quadratic-api/src/app.ts
  quadratic-api/src/instrument.ts
  quadratic-api/src/server.ts
  quadratic-client/package.json
  quadratic-client/src/index.tsx
Labels: cla-signed

#2530 fix: sync transaction status with client and render worker
  quadratic-client/src/app/ai/hooks/useCodeCellContextMessages.tsx
  quadratic-client/src/app/ai/tools/aiToolsActions.ts
  quadratic-client/src/app/atoms/codeEditorAtom.ts
  quadratic-client/src/app/atoms/editorInteractionStateAtom.ts
  quadratic-client/src/app/events/events.ts
  quadratic-client/src/app/gridGL/HTMLGrid/hoverCell/HoverCell.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorFormula.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
  quadratic-client/src/app/gridGL/HTMLGrid/multiplayerInput/MultiplayerCellEdits.tsx
  quadratic-client/src/app/gridGL/UI/gridHeadings/GridHeadings.ts
  quadratic-client/src/app/gridGL/cells/CellsSearch.ts
  quadratic-client/src/app/gridGL/cells/cellsLabel/CellsDrawRects.ts
  quadratic-client/src/app/gridGL/cells/cellsLabel/CellsLabels.ts
  quadratic-client/src/app/gridGL/cells/cellsLabel/CellsTextHash.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/useKeyboard.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerLink.ts
  quadratic-client/src/app/shared/types/codeCell.ts
  quadratic-client/src/app/shared/types/links.ts
  quadratic-client/src/app/shared/types/size.ts
  quadratic-client/src/app/shared/types/transactionInfo.ts
  quadratic-client/src/app/ui/components/FixSpillError.tsx
  quadratic-client/src/app/ui/menus/BottomBar/KernelMenu.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorBody.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/hooks/useSubmitAIAssistantPrompt.tsx
  quadratic-client/src/app/web-workers/CodeRun.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayer.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayerTypes.ts
  quadratic-client/src/app/web-workers/quadraticCore/coreClientMessages.ts
  quadratic-client/src/app/web-workers/quadraticCore/coreRenderMessages.ts
  quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreRender.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/rustCallbacks.ts
  quadratic-client/src/app/web-workers/renderWebWorker/renderClientMessages.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsLabels.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellsTextHash.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/renderClient.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/renderCore.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/renderText.ts
  quadratic-client/src/dashboard/atoms/filesImportProgressAtom.ts
  quadratic-core/src/controller/execution/control_transaction.rs
  quadratic-core/src/controller/user_actions/clipboard.rs
  quadratic-core/src/controller/user_actions/code.rs
  quadratic-core/src/wasm_bindings/controller/code.rs
  quadratic-core/src/wasm_bindings/js.rs
Labels: cla-signed, status: ready to merge

#2374 feat: add code editor ai completions
  quadratic-api/prisma/migrations/20250302073129_code_editor_completions/migration.sql
  quadratic-api/prisma/schema.prisma
  quadratic-client/src/app/ai/tools/aiToolsActions.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorMonaco.ts
  quadratic-client/src/app/shared/types/SuggestController.ts
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorBody.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/hooks/useCodeEditorCompletions.tsx
  quadratic-shared/ai/models/AI_MODELS.ts
  quadratic-shared/ai/specs/aiToolsSpec.ts
  quadratic-shared/typesAndSchemasAI.ts
Labels: cla-signed, status: ready to merge

#2378 feat: analyst ai prompt suggestions
  quadratic-api/prisma/migrations/20250303124640_user_prompt_suggestions/migration.sql
  quadratic-api/prisma/schema.prisma
  quadratic-client/src/app/ai/hooks/useGetChatName.tsx
  quadratic-client/src/app/ai/hooks/useGetUserPromptSuggestions.tsx
  quadratic-client/src/app/ai/toolCards/UserPromptSuggestions.tsx
  quadratic-client/src/app/ai/tools/aiToolsActions.ts
  quadratic-client/src/app/atoms/aiAnalystAtom.ts
  quadratic-client/src/app/ui/QuadraticSidebar.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystEffects.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystMessages.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystToolCard.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/hooks/useSubmitAIAnalystPrompt.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/hooks/useSubmitAIAssistantPrompt.tsx
  quadratic-shared/ai/models/AI_MODELS.ts
  quadratic-shared/ai/specs/aiToolsSpec.ts
  quadratic-shared/typesAndSchemasAI.ts
Labels: cla-signed, status: ready to merge

#2540 Viewport Improvements
  quadratic-client/src/app/gridGL/UI/gridHeadings/GridHeadings.ts
  quadratic-client/src/app/gridGL/pixiApp/viewport/Viewport.ts
  quadratic-client/src/app/gridGL/pixiApp/viewport/Wheel.ts
Labels: cla-signed, status: ready for user test

#2381 Move column and row
  quadratic-client/src/app/actions/columnRowSpec.ts
  quadratic-client/src/app/actions/dataTableSpec.ts
  quadratic-client/src/app/ai/tools/aiToolsActions.ts
  quadratic-client/src/app/grid/sheet/SheetCursor.ts
  quadratic-client/src/app/gridGL/UI/Cursor.ts
  quadratic-client/src/app/gridGL/UI/UICellMoving.ts
  quadratic-client/src/app/gridGL/UI/drawCursor.ts
  quadratic-client/src/app/gridGL/interaction/pointer/Pointer.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerCellMoving.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerHeading.ts
  quadratic-client/src/app/gridGL/pixiApp/viewport/Viewport.ts
  quadratic-client/src/app/web-workers/quadraticCore/coreClientMessages.ts
  quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
  quadratic-core/package.json
  quadratic-core/src/a1/a1_selection/create.rs
  quadratic-core/src/a1/a1_selection/query.rs
  quadratic-core/src/a1/js_selection/query.rs
  quadratic-core/src/controller/execution/execute_operation/execute_col_rows.rs
  quadratic-core/src/controller/execution/execute_operation/execute_data_table.rs
  quadratic-core/src/controller/execution/execute_operation/execute_move_cells.rs
  quadratic-core/src/controller/execution/execute_operation/mod.rs
  quadratic-core/src/controller/operations/clipboard.rs
  quadratic-core/src/controller/operations/operation.rs
  quadratic-core/src/controller/user_actions/clipboard.rs
  quadratic-core/src/controller/user_actions/col_row.rs
  quadratic-core/src/controller/user_actions/mod.rs
  quadratic-core/src/controller/user_actions/move_col_row.rs
  quadratic-core/src/grid/sheet/borders/borders_clipboard.rs
  quadratic-core/src/grid/sheet/col_row/column.rs
  quadratic-core/src/grid/sheet/col_row/delete.rs
  quadratic-core/src/grid/sheet/col_row/mod.rs
  quadratic-core/src/grid/sheet_formatting/mod.rs
  quadratic-core/src/grid/sheet_formatting/sheet_formatting_clipboard.rs
  quadratic-core/src/sheet_offsets/offsets.rs
  quadratic-core/src/test_util/gc.rs
  quadratic-core/src/test_util/mod.rs
  quadratic-core/src/test_util/sheet.rs
  quadratic-core/src/wasm_bindings/controller/clipboard.rs
  quadratic-core/src/wasm_bindings/controller/col_row.rs
Labels: cla-signed, status: ready to merge, status: ready for user test

#2354 Rework code/formula translation & name-updating
  quadratic-core/src/a1/a1_context/mod.rs
  quadratic-core/src/a1/a1_context/sheet_map.rs
  quadratic-core/src/a1/a1_selection/create.rs
  quadratic-core/src/a1/a1_selection/display.rs
  quadratic-core/src/a1/a1_selection/intersects.rs
  quadratic-core/src/a1/a1_selection/mutate.rs
  quadratic-core/src/a1/a1_selection/parse.rs
  quadratic-core/src/a1/cell_ref_coord.rs
  quadratic-core/src/a1/cell_ref_end.rs
  quadratic-core/src/a1/cell_ref_range/mutate.rs
  quadratic-core/src/a1/js_selection/create.rs
  quadratic-core/src/a1/ref_range_bounds/translate.rs
  quadratic-core/src/a1/sheet_cell_ref_range.rs
  quadratic-core/src/a1/sheet_name.rs
  quadratic-core/src/a1/table_ref/mod.rs
  quadratic-core/src/a1/table_ref/range.rs
  quadratic-core/src/controller/execution/execute_operation/execute_col_rows.rs
  quadratic-core/src/controller/execution/execute_operation/execute_sheets.rs
  quadratic-core/src/controller/execution/execute_operation/execute_validation.rs
  quadratic-core/src/controller/execution/execute_operation/mod.rs
  quadratic-core/src/controller/execution/run_code/get_cells.rs
  quadratic-core/src/controller/execution/run_code/run_connection.rs
  quadratic-core/src/controller/formula.rs
  quadratic-core/src/controller/operations/autocomplete.rs
  quadratic-core/src/controller/operations/clipboard.rs
  quadratic-core/src/controller/operations/code_cell.rs
  quadratic-core/src/controller/operations/sheets.rs
  quadratic-core/src/controller/thumbnail.rs
  quadratic-core/src/controller/user_actions/auto_complete.rs
  quadratic-core/src/controller/user_actions/clipboard.rs
  quadratic-core/src/controller/user_actions/formats.rs
  quadratic-core/src/controller/user_actions/validations.rs
  quadratic-core/src/formulas/ast.rs
  quadratic-core/src/formulas/functions/lookup.rs
  quadratic-core/src/formulas/parser/mod.rs
  quadratic-core/src/formulas/parser/rules/atoms.rs
  quadratic-core/src/formulas/parser/rules/table_ref.rs
  quadratic-core/src/formulas/tests.rs
  quadratic-core/src/grid/a1_context.rs
  quadratic-core/src/grid/code_cell.rs
  quadratic-core/src/grid/code_run.rs
  quadratic-core/src/grid/data_table/formats.rs
  quadratic-core/src/grid/file/shift_negative_offsets.rs
  quadratic-core/src/grid/selection.rs
  quadratic-core/src/grid/sheet.rs
  quadratic-core/src/grid/sheet/a1_context.rs
  quadratic-core/src/grid/sheet/bounds/mod.rs
  quadratic-core/src/grid/sheet/cell_values.rs
  quadratic-core/src/grid/sheet/clipboard.rs
  quadratic-core/src/grid/sheet/data_table.rs
  quadratic-core/src/grid/sheet/rendering/fills.rs
  quadratic-core/src/grid/sheet/validations/validation_col_row.rs
  quadratic-core/src/grid/sheet/validations/validations_clipboard.rs
  quadratic-core/src/grid/sheets.rs
  quadratic-core/src/lib.rs
  quadratic-core/src/pos.rs
  quadratic-core/src/util.rs
Labels: cla-signed

#2541 fix: use presigned urls for file-storage
  quadratic-api/src/storage/storage.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
Labels: cla-signed, status: ready to merge

#2560 Improve debug formatting for `Contiguous2D`
  quadratic-core/src/grid/contiguous/contiguous_2d.rs
Labels: cla-signed, status: ready to merge

#2552 chore: upgrade to pixi.js v7
  package-lock.json
  quadratic-client/package.json
  quadratic-client/src/app/gridGL/HTMLGrid/htmlCells/HtmlCell.ts
  quadratic-client/src/app/gridGL/UI/Cursor.ts
  quadratic-client/src/app/gridGL/cells/CellsMarkers.ts
  quadratic-client/src/app/gridGL/cells/cellsLabel/LabelMeshEntry.ts
  quadratic-client/src/app/gridGL/cells/cellsLabel/drawSpecial.ts
  quadratic-client/src/app/gridGL/cells/tables/TableName.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardLink.ts
  quadratic-client/src/app/gridGL/interaction/pointer/Pointer.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerCellMoving.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerDown.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerHeading.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerHtmlCells.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerLink.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerTable.ts
  quadratic-client/src/app/gridGL/interaction/pointer/pointerCursor.ts
  quadratic-client/src/app/gridGL/loadAssets.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
  quadratic-client/src/app/gridGL/pixiApp/copyAsPNG.ts
  quadratic-client/src/app/gridGL/pixiApp/thumbnail.ts
  quadratic-client/src/app/gridGL/pixiApp/viewport/Drag.ts
  quadratic-client/src/app/gridGL/pixiApp/viewport/Viewport.ts
  quadratic-client/src/app/gridGL/pixiApp/viewport/Wheel.ts
  quadratic-client/src/app/helpers/keyboardShortcuts.ts
  quadratic-client/src/setupPixiTests.ts
Labels: cla-signed, status: ready for user test

#2546 perf: improve getCells
  quadratic-client/src/app/quadratic-core-types/index.d.ts
  quadratic-client/src/app/shared/utils/toUint8Array.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/javascriptCoreMessages.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascript.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascriptAPI.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascriptOutput.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascriptResults.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascriptRunnerMessages.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/generateJavascriptForRunner.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/generatedJavascriptForEditor.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/javascriptLibrary.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascriptCore.ts
  quadratic-client/src/app/web-workers/pythonWebWorker/pythonCoreMessages.ts
  quadratic-client/src/app/web-workers/pythonWebWorker/pythonTypes.ts
  quadratic-client/src/app/web-workers/pythonWebWorker/worker/python.test.ts
  quadratic-client/src/app/web-workers/pythonWebWorker/worker/python.ts
  quadratic-client/src/app/web-workers/pythonWebWorker/worker/pythonCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreJavascript.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/corePython.ts
  quadratic-core/src/bin/export_types.rs
  quadratic-core/src/wasm_bindings/controller/code.rs
  quadratic-kernels/python-wasm/quadratic_py/quadratic_api/quadratic.py
  quadratic-kernels/python-wasm/quadratic_py/utils.py
  quadratic-kernels/python-wasm/tests/test.py
Labels: cla-signed, status: ready to merge

#2526 feat: tweaks to connections flow
  quadratic-client/src/app/ui/QuadraticSidebar.tsx
  quadratic-client/src/app/ui/menus/ConnectionsMenu/ConnectionsMenu.tsx
  quadratic-client/src/routes/teams.$teamUuid.connections.tsx
  quadratic-client/src/shared/components/connections/Connections.tsx
  quadratic-client/src/shared/components/connections/ConnectionsSidebar.tsx
  quadratic-client/src/shared/shadcn/ui/toggle.tsx
  quadratic-shared/typesAndSchemasConnections.ts
Labels: cla-signed, status: ready for code review

#2563 bugreport
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: cla-signed

#2551 chore: use u8 type in code response types
  quadratic-client/src/app/quadratic-core-types/index.d.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascriptOutput.test.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascriptOutput.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascriptResults.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/generateJavascriptForRunner.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/generatedJavascriptForEditor.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/javascriptLibrary.ts
  quadratic-client/src/app/web-workers/pythonWebWorker/worker/python.ts
  quadratic-core/src/bin/export_types.rs
  quadratic-core/src/controller/execution/auto_resize_row_heights.rs
  quadratic-core/src/controller/execution/control_transaction.rs
  quadratic-core/src/controller/execution/receive_multiplayer.rs
  quadratic-core/src/controller/execution/run_code/get_cells.rs
  quadratic-core/src/controller/execution/run_code/mod.rs
  quadratic-core/src/controller/execution/run_code/run_formula.rs
  quadratic-core/src/controller/execution/run_code/run_javascript.rs
  quadratic-core/src/controller/execution/run_code/run_python.rs
  quadratic-core/src/controller/execution/spills.rs
  quadratic-core/src/controller/send_render.rs
  quadratic-core/src/controller/transaction_types.rs
  quadratic-core/src/controller/user_actions/data_table.rs
  quadratic-core/src/grid/data_table/display_value.rs
  quadratic-core/src/grid/sheet/cell_array.rs
  quadratic-core/src/grid/sheet/rendering/code.rs
  quadratic-core/src/values/array.rs
  quadratic-core/src/values/cellvalue.rs
  quadratic-core/src/values/from_js.rs
  quadratic-kernels/python-wasm/quadratic_py/quadratic_api/quadratic.py
  quadratic-kernels/python-wasm/quadratic_py/utils.py
  quadratic-kernels/python-wasm/tests/process_output_test.py
  quadratic-kernels/python-wasm/tests/test.py
Labels: cla-signed, status: ready for code review, status: ready for user test

#2539 feat: version history
  quadratic-api/jest.setup.js
  quadratic-api/src/routes/v0/files.$uuid.checkpoints.$checkpointId.GET.test.ts
  quadratic-api/src/routes/v0/files.$uuid.checkpoints.$checkpointId.GET.ts
  quadratic-api/src/routes/v0/files.$uuid.checkpoints.GET.test.ts
  quadratic-api/src/routes/v0/files.$uuid.checkpoints.GET.ts
  quadratic-client/src/app/actions.ts
  quadratic-client/src/app/actions/actions.ts
  quadratic-client/src/app/actions/fileActionsSpec.ts
  quadratic-client/src/app/gridGL/HTMLGrid/hoverCell/HoverCell.tsx
  quadratic-client/src/app/ui/QuadraticApp.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/ReturnTypeInspector.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/panels/useCodeEditorPanelData.ts
  quadratic-client/src/app/ui/menus/CommandPalette/commands/File.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBar.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBarMenus/FileMenubarMenu.tsx
  quadratic-client/src/dashboard/components/FilesList.tsx
  quadratic-client/src/dashboard/components/FilesListItem.tsx
  quadratic-client/src/router.tsx
  quadratic-client/src/routes/api.files.$uuid.ts
  quadratic-client/src/routes/file.$uuid.history.tsx
  quadratic-client/src/routes/file.$uuid.tsx
  quadratic-client/src/shared/api/apiClient.ts
  quadratic-client/src/shared/components/Icons.tsx
  quadratic-client/src/shared/constants/routes.ts
  quadratic-client/src/shared/shadcn/ui/tooltip.tsx
  quadratic-shared/typesAndSchemas.ts
Labels: cla-signed, status: ready to merge

#2570 Add Insert->Table to the toolbar menu, disable for single cells
  quadratic-client/src/app/actions/actions.ts
  quadratic-client/src/app/actions/actionsSpec.ts
  quadratic-client/src/app/actions/dataTableSpec.ts
  quadratic-client/src/app/actions/insertActionsSpec.ts
  quadratic-client/src/app/ui/menus/TopBar/TopBarMenus/InsertMenubarMenu.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBarMenus/MenubarItemAction.tsx
Labels: cla-signed, status: ready for code review, status: ready for user test

#2561 Preserve data table name across re-runs
  quadratic-core/src/controller/execution/run_code/mod.rs
  quadratic-core/src/controller/user_actions/data_table.rs
Labels: cla-signed, status: ready to merge

#2568 Enforce no-data-table-in-data-table rule
  quadratic-core/src/controller/execution/execute_operation/execute_data_table.rs
  quadratic-core/src/controller/operations/data_table.rs
  quadratic-core/src/grid/code_cell.rs
  quadratic-core/src/grid/sheet/data_table.rs
Labels: cla-signed, status: ready to merge

#2550 Remove AI output rect width/height from tool call
  Cargo.lock
  quadratic-client/src/app/ai/tools/aiToolsActions.ts
  quadratic-core/Cargo.toml
  quadratic-shared/ai/specs/aiToolsSpec.ts
Labels: cla-signed, status: ready to merge

#2577 fixes a bug with delete col/row and fills
  quadratic-core/src/grid/sheet/col_row/column.rs
  quadratic-core/src/grid/sheet/col_row/row.rs
Labels: cla-signed, status: ready for user test

#2547 Optimize copying values from Contiguous2D
  quadratic-core/src/controller/operations/clipboard.rs
  quadratic-core/src/grid/contiguous/contiguous_2d.rs
  quadratic-core/src/grid/contiguous/contiguous_blocks.rs
  quadratic-core/src/grid/sheet/borders/borders_clipboard.rs
  quadratic-core/src/grid/sheet/clipboard.rs
  quadratic-core/src/grid/sheet_formatting/sheet_formatting_clipboard.rs
Labels: status: open question, cla-signed, status: ready for user test

#2580 Add `is_all_default_in_range()` and `unique_values_in_range()` for `Contiguous2D`
  quadratic-core/src/grid/contiguous/contiguous_2d.rs
  quadratic-core/src/grid/contiguous/contiguous_blocks.rs
Labels: cla-signed, status: ready to merge

#2582 Fixes firefox pointer issue
  quadratic-client/src/app/gridGL/interaction/pointer/Pointer.ts
Labels: cla-signed, status: ready to merge

#2583 fix: running py transactionId
  Cargo.lock
  package-lock.json
  quadratic-client/src/app/web-workers/pythonWebWorker/worker/python.ts
Labels: cla-signed, status: ready for code review, status: ready for user test

#2573 chore: use grid controller in formula ctx
  quadratic-core/src/controller/execution/run_code/run_formula.rs
  quadratic-core/src/controller/formula.rs
  quadratic-core/src/formulas/ast.rs
  quadratic-core/src/formulas/ctx.rs
  quadratic-core/src/formulas/functions/array.rs
  quadratic-core/src/formulas/functions/datetime.rs
  quadratic-core/src/formulas/functions/financial.rs
  quadratic-core/src/formulas/functions/logic.rs
  quadratic-core/src/formulas/functions/lookup.rs
  quadratic-core/src/formulas/functions/mathematics.rs
  quadratic-core/src/formulas/functions/operators.rs
  quadratic-core/src/formulas/functions/statistics.rs
  quadratic-core/src/formulas/functions/string.rs
  quadratic-core/src/formulas/functions/tests.rs
  quadratic-core/src/formulas/functions/trigonometry.rs
  quadratic-core/src/formulas/parser/mod.rs
  quadratic-core/src/formulas/tests.rs
  quadratic-core/src/values/mod.rs
Labels: cla-signed, status: ready to merge

#2589 Main
  Cargo.toml
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-client/package.json
  quadratic-client/src/app/ai/components/SelectAIModelMenu.tsx
  quadratic-client/src/app/ai/hooks/useAIModel.tsx
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-client/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/ai/models/AI_MODELS.ts
  quadratic-shared/package.json
Labels: cla-signed

#2581 Add `Contiguous2D::is_all_default_in_rect()`
  quadratic-core/src/grid/contiguous/contiguous_2d.rs
Labels: cla-signed, status: ready to merge

#2596 Check for out of bounds on the display buffer when inserting a row
  Cargo.lock
  quadratic-core/src/grid/data_table/row.rs
Labels: cla-signed, status: ready to merge

#2601 Add `Contiguous2D::nondefault_rects_in_rect()`
  quadratic-core/src/grid/contiguous/contiguous_2d.rs
Labels: cla-signed, status: ready for code review

#2602 Remove panic from setCodeCell (merge to main)
  quadratic-core/src/wasm_bindings/controller/code.rs
Labels: cla-signed

#2607 fix: duplicate sheet name on excel import shows app crashed screen
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-core/src/wasm_bindings/controller/import.rs
Labels: cla-signed, status: ready for code review, status: ready for user test

#2611 fix: render on excel import
  quadratic-core/src/controller/execution/control_transaction.rs
  quadratic-core/src/controller/execution/receive_multiplayer.rs
  quadratic-core/src/controller/user_actions/import.rs
  quadratic-core/src/wasm_bindings/controller/import.rs
Labels: cla-signed, status: ready to merge

#2608 main: 0.6.9
  Cargo.lock
  Cargo.toml
  VERSION
  package-lock.json
  package.json
  quadratic-api/package.json
  quadratic-client/package.json
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-core/src/controller/execution/control_transaction.rs
  quadratic-core/src/controller/execution/receive_multiplayer.rs
  quadratic-core/src/controller/user_actions/import.rs
  quadratic-core/src/wasm_bindings/controller/code.rs
  quadratic-core/src/wasm_bindings/controller/import.rs
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-client/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: cla-signed

#2613 chore: merge 0.6.9 main to qa
  Cargo.lock
  Cargo.toml
  VERSION
  package-lock.json
  package.json
  quadratic-api/package.json
  quadratic-client/package.json
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-core/src/controller/execution/control_transaction.rs
  quadratic-core/src/controller/execution/receive_multiplayer.rs
  quadratic-core/src/controller/user_actions/import.rs
  quadratic-core/src/wasm_bindings/controller/code.rs
  quadratic-core/src/wasm_bindings/controller/import.rs
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-client/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: cla-signed, status: ready to merge
