Repository quadratichq/quadratic, pull requests merged in 2025-09, with the labels that each got.

#3406 Tool description improvements for getcodecellvalue and resize rows
  quadratic-shared/ai/specs/aiToolsSpec.ts
Labels: cla-signed, status: ready to merge, status: ready for user test

#3400 Clicking top-left corner of canvas properly selects all (again)
  quadratic-client/src/app/grid/sheet/SheetCursor.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerHeading.ts
  test/e2e/src/spreadsheetKeyboard.spec.ts
  test/e2e/src/spreadsheetMouse.spec.ts
Labels: status: ready to merge

#3413 Fix column row selection
  Cargo.toml
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-client/src/app/gridGL/interaction/pointer/PointerHeading.ts
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: cla-signed, status: ready to merge

#3427 fix: login redirect to file url
  quadratic-client/src/routes/file.$uuid.tsx
  quadratic-client/src/shared/constants/routes.ts
Labels: cla-signed

#3393 Improve Load Time
  .github/workflows/production-deploy.yml
  .github/workflows/qa-deploy.yml
  .vscode/settings.json
  quadratic-client/index.html
  quadratic-client/src/app/debugFlags/debugFlags.ts
  quadratic-client/src/app/debugFlags/debugFlagsDefinitions.ts
  quadratic-client/src/app/events/events.ts
  quadratic-client/src/app/gridGL/helpers/debugPerformance.ts
  quadratic-client/src/app/gridGL/helpers/startupTimer.ts
  quadratic-client/src/app/gridGL/loadAssets.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
  quadratic-client/src/app/gridGL/pixiApp/Update.ts
  quadratic-client/src/app/ui/QuadraticApp.tsx
  quadratic-client/src/app/ui/QuadraticAppDebugSettings.tsx
  quadratic-client/src/app/ui/components/FileProvider.tsx
  quadratic-client/src/app/web-workers/quadraticCore/coreClientMessages.ts
  quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
  quadratic-client/src/routes/file.$uuid.tsx
  quadratic-client/src/shared/api/fetchFromApi.ts
  quadratic-client/src/shared/hooks/useRemoveInitialLoadingUI.ts
  quadratic-client/src/shared/utils/analytics.ts
  quadratic-client/src/shared/utils/analyticsEvents.ts
Labels: cla-signed, status: ready to merge, status: ready for user test, QA

#3433 fix: cleanup cache changes
  .github/workflows/production-deploy.yml
  .github/workflows/qa-deploy.yml
  docker/client/config/default.conf
  quadratic-client/src/app/gridGL/loadAssets.ts
Labels: cla-signed

#3432 Discourage multiple charts in one cell
  quadratic-api/src/ai/docs/PythonDocs.ts
Labels: cla-signed, status: ready to merge, status: ready for user test, QA

#3435 fix: go to menu sheet selection closes menu
  quadratic-client/src/app/ui/menus/GoTo/GoTo.tsx
  test/e2e/src/spreadsheetTables.spec.ts
Labels: cla-signed, status: ready for user test

#3437 chore: add kid to jwt error warnings
  quadratic-rust-shared/src/auth/jwt.rs
Labels: cla-signed, status: ready to merge, QA

#3438 chore: version bump 0.18.1
  Cargo.toml
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: cla-signed, status: ready to merge, QA

#3420 Feedback for empty single cell output
  quadratic-client/src/app/ai/tools/aiToolsActions.ts
Labels: cla-signed, status: ready to merge, QA

#3422 infra: use selfhosted sentry
  infra/sentry-selfhost/setup.sh
  quadratic-api/package.json
  quadratic-api/src/instrument.ts
  quadratic-client/package.json
  quadratic-client/src/index.tsx
  quadratic-client/src/shared/utils/sentry.ts
  quadratic-client/vite.config.js
Labels: cla-signed, status: ready to merge, QA

#3416 Fix screen to sheet offsets perf
  quadratic-core/src/grid/file/mod.rs
  quadratic-core/src/grid/file/v1_6/file.rs
  quadratic-core/src/grid/mod.rs
  quadratic-core/src/sheet_offsets/mod.rs
  quadratic-core/src/sheet_offsets/offsets.rs
  quadratic-core/src/wasm_bindings/controller/mod.rs
Labels: cla-signed, status: ready to merge, QA

#3445 fix: datadog prisma upsert error
  quadratic-client/src/app/ai/hooks/useCodeCellContextMessages.tsx
  quadratic-client/src/app/ai/utils/codeCellToMarkdown.ts
  quadratic-client/src/app/atoms/codeEditorAtom.ts
  quadratic-client/src/app/ui/menus/CodeEditor/hooks/useAlertOnUnsavedChanges.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/hooks/useEditorCellHighlights.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/hooks/useEditorDiagnostics.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/hooks/useEditorReturn.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/hooks/useSubmitAIAssistantPrompt.tsx
Labels: cla-signed, QA

#3452 fix: characterSize undefined in GridHeadings
  quadratic-client/src/app/gridGL/UI/gridHeadings/GridHeadings.ts
Labels: cla-signed, status: ready to merge, QA

#3456 chore: version bump 0.19.1
  Cargo.toml
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: cla-signed, QA

#3450 kimi-k2-0905
  quadratic-api/src/ai/docs/PythonDocs.ts
  quadratic-shared/ai/models/AI_MODELS.ts
  quadratic-shared/typesAndSchemasAI.ts
Labels: cla-signed, QA

#3457 chore: add input tokens to raindrop
  quadratic-api/src/routes/v0/ai.chat.POST.ts
Labels: cla-signed, status: ready to merge, QA

#3460 chore: add mixpanel event for user created from api
  quadratic-api/src/middleware/user.ts
Labels: cla-signed, status: ready to merge, QA

#3463 chore: version bump 0.19.2
  Cargo.toml
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: cla-signed

#3459 QA Sept 18th
  Cargo.toml
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-api/src/middleware/user.ts
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-client/src/app/gridGL/UI/gridHeadings/GridHeadings.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: cla-signed

#3466 fix: semantic description & snowflake connection
  quadratic-api/src/routes/v0/teams.$uuid.connections.$connectionUuid.PUT.test.ts
  quadratic-api/src/routes/v0/teams.$uuid.connections.$connectionUuid.PUT.ts
  quadratic-client/src/shared/components/connections/ConnectionFormSemantic.tsx
  quadratic-client/src/shared/components/connections/ConnectionFormSnowflake.tsx
Labels: cla-signed, status: ready to merge

#3468 Fix heading auto resize
  quadratic-client/src/app/gridGL/interaction/pointer/PointerHeading.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/cellsLabel/CellLabel.ts
Labels: cla-signed, status: ready to merge, QA

#3472 GPT-5 --> GPT-5-codex
  .github/workflows/ci.yml
  Cargo.toml
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-api/src/ai/handler/ai.handler.ts
  quadratic-api/src/ai/handler/openai.responses.handler.ts
  quadratic-api/src/ai/helpers/anthropic.helper.ts
  quadratic-api/src/ai/helpers/bedrock.helper.ts
  quadratic-api/src/ai/helpers/genai.helper.ts
  quadratic-api/src/ai/helpers/openai.chatCompletions.helper.ts
  quadratic-api/src/ai/helpers/openai.responses.helper.ts
  quadratic-api/src/ai/providers.ts
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-client/src/app/quadratic-core-types/index.d.ts
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/ai/models/AI_MODELS.ts
  quadratic-shared/package.json
  quadratic-shared/typesAndSchemasAI.ts
Labels: cla-signed, status: ready to merge

#3479 Copy as png closes context menu
  quadratic-client/src/app/actions/editActionsSpec.ts
  test/e2e/src/spreadsheetUI.spec.ts
  test/e2e/src/spreadsheetUI.spec.ts-snapshots/right-click-copy-as-png-chromium.png
Labels: cla-signed, status: ready to merge

#3488 chore: update sonnet 4.5 backup model chain
  quadratic-api/src/routes/v0/ai.chat.POST.test.ts
  quadratic-shared/ai/models/AI_MODELS.ts
  quadratic-shared/typesAndSchemasAI.ts
Labels: cla-signed, status: ready for code review, status: ready for user test, QA
