Repository quadratichq/quadratic, pull requests merged in 2025-05, with the labels that each got.

#2775 Improve delete tables
  quadratic-core/src/a1/a1_selection/query.rs
  quadratic-core/src/a1/js_selection/query.rs
  quadratic-core/src/a1/ref_range_bounds/query.rs
  quadratic-core/src/controller/execution/execute_operation/execute_values.rs
  quadratic-core/src/controller/operations/cell_value.rs
  quadratic-core/src/grid/sheet/data_table.rs
  quadratic-core/src/rect.rs
  quadratic-core/src/test_util/assert.rs
  quadratic-core/src/test_util/create_data_table.rs
  quadratic-core/src/test_util/mod.rs
Labels: cla-signed, status: ready to merge

#2707 Add `RegionMap`
  quadratic-core/Cargo.lock
  quadratic-core/Cargo.toml
  quadratic-core/src/grid/mod.rs
  quadratic-core/src/grid/region_map.rs
  quadratic-core/src/util.rs
  quadratic-core/src/wasm_bindings/controller/import.rs
Labels: cla-signed, prototype, status: ready to merge

#2836 ai uses the current sheet when request was made
  quadratic-client/src/app/ai/tools/aiToolsActions.ts
  quadratic-client/src/app/gridGL/interaction/viewportHelper.ts
  quadratic-client/src/app/ui/components/FixSpillError.tsx
  quadratic-shared/ai/specs/aiToolsSpec.ts
Labels: cla-signed, QA

#2853 fix: swap out more icon componentry related to MUI
  quadratic-client/src/app/ai/toolCards/SetCodeCellValue.tsx
  quadratic-client/src/app/ai/toolCards/UpdateCodeCell.tsx
  quadratic-client/src/app/ui/components/LanguageIcon.tsx
  quadratic-client/src/app/ui/icons/index.tsx
  quadratic-client/src/app/ui/menus/CellTypeMenu/CellTypeMenu.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorEmptyState.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorHeader.tsx
  quadratic-client/src/app/ui/menus/GoTo/GoTo.tsx
  quadratic-client/src/dashboard/components/NewFileButton.tsx
  quadratic-client/src/dashboard/components/OnboardingBanner.tsx
  quadratic-client/src/shared/components/Icons.tsx
  quadratic-client/src/shared/components/LanguageIcon.tsx
  quadratic-client/src/shared/components/connections/ConnectionSchemaBrowser.tsx
  quadratic-client/src/shared/components/connections/ConnectionsList.tsx
  quadratic-client/src/shared/shadcn/ui/command.tsx
Labels: cla-signed, QA

#2847 Combine sheet and data table formats when copying
  quadratic-core/src/controller/operations/clipboard.rs
  quadratic-core/src/grid/data_table/formats.rs
  quadratic-core/src/grid/formats/sheet_format_updates.rs
  quadratic-core/src/grid/sheet/clipboard.rs
  quadratic-core/src/grid/sheet_formatting/sheet_formatting_clipboard.rs
Labels: cla-signed, QA

#2810 Handle nulls of all types for postgres and mysql
  docker-compose.yml
  docker/mysql-connection/scripts/setup.sql
  docker/postgres-connection/scripts/setup.sql
  quadratic-connection/package.json
  quadratic-connection/src/sql/mysql.rs
  quadratic-connection/src/sql/postgres.rs
  quadratic-connection/src/test_util.rs
  quadratic-rust-shared/Cargo.lock
  quadratic-rust-shared/package.json
  quadratic-rust-shared/src/arrow/arrow_type.rs
  quadratic-rust-shared/src/sql/mod.rs
  quadratic-rust-shared/src/sql/mysql_connection.rs
  quadratic-rust-shared/src/sql/postgres_connection.rs
Labels: cla-signed, status: ready to merge, QA

#2763 Fix cells accessed for Python table references
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorFormula.ts
  quadratic-client/src/app/gridGL/UI/cellHighlights/CellHighlights.ts
  quadratic-client/src/app/ui/menus/CodeEditor/hooks/useEditorCellHighlights.ts
  quadratic-core/src/a1/js_selection/create.rs
  quadratic-core/src/a1/ref_range_bounds/mod.rs
  quadratic-core/src/a1/table_ref/convert.rs
  quadratic-files/Cargo.lock
  quadratic-multiplayer/Cargo.lock
Labels: cla-signed, status: ready to merge, QA

#2870 AI keeps trying to recompute cells with dependencies when it updates the data
  quadratic-api/src/ai/docs/PythonDocs.ts
Labels: cla-signed, status: ready to merge

#2804 Resize multiple columns and rows
  quadratic-client/src/app/grid/controller/Sheets.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerHeading.ts
  quadratic-client/src/app/quadratic-core-types/index.d.ts
  quadratic-client/src/app/web-workers/quadraticCore/coreClientMessages.ts
  quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
  quadratic-core/src/bin/export_types.rs
  quadratic-core/src/controller/active_transactions/pending_transaction.rs
  quadratic-core/src/controller/active_transactions/transaction_name.rs
  quadratic-core/src/controller/execution/execute_operation/execute_col_rows.rs
  quadratic-core/src/controller/execution/execute_operation/execute_offsets.rs
  quadratic-core/src/controller/execution/execute_operation/mod.rs
  quadratic-core/src/controller/operations/operation.rs
  quadratic-core/src/controller/user_actions/mod.rs
  quadratic-core/src/controller/user_actions/offsets.rs
  quadratic-core/src/grid/js_types.rs
  quadratic-core/src/grid/sheet/col_row/columns_insert.rs
  quadratic-core/src/grid/sheet/col_row/rows_insert.rs
  quadratic-core/src/sheet_offsets/mod.rs
  quadratic-core/src/sheet_offsets/offsets.rs
  quadratic-core/src/wasm_bindings/controller/sheet_offsets.rs
Labels: cla-signed, status: ready to merge, QA

#2856 feat: suggest users start a new chat
  quadratic-client/src/app/atoms/aiAnalystAtom.ts
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystHeader.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystUserMessageForm.tsx
  quadratic-client/src/routes/_root.tsx
Labels: cla-signed, status: ready to merge, QA

#2701 fix: change ai usage calculation to team > user
  quadratic-api/.env.test
  quadratic-api/prisma/migrations/20250410220404_add_indexes_for_ai_usage_query/migration.sql
  quadratic-api/prisma/schema.prisma
  quadratic-api/src/billing/AIUsageHelpers.ts
  quadratic-api/src/routes/v0/ai.codeRunError.PATCH.test.ts
  quadratic-api/src/routes/v0/ai.feedback.PATCH.test.ts
  quadratic-api/src/routes/v0/teams.$uuid.GET.ts
  quadratic-api/src/routes/v0/teams.$uuid.billing.ai.usage.GET.test.ts
  quadratic-api/src/routes/v0/teams.$uuid.billing.ai.usage.GET.ts
  quadratic-api/src/tests/testDataGenerator.ts
Labels: cla-signed, status: ready for code review, QA

#2878 Implement autocomplete within a data table, expanding beyond the table
  quadratic-client/src/app/gridGL/UI/Cursor.ts
  quadratic-core/src/controller/operations/autocomplete.rs
  quadratic-core/src/controller/operations/cell_value.rs
  quadratic-core/src/controller/operations/clipboard.rs
  quadratic-core/src/controller/user_actions/auto_complete.rs
  quadratic-core/src/grid/sheet/data_table.rs
  quadratic-core/src/test_util/print_sheet.rs
  quadratic-core/src/wasm_bindings/controller/auto_complete.rs
  quadratic-core/src/wasm_bindings/error.rs
  quadratic-core/src/wasm_bindings/mod.rs
Labels: cla-signed, status: ready to merge, QA

#2890 Hide cursor on full table selection
  quadratic-client/src/app/gridGL/UI/Cursor.ts
  quadratic-client/src/app/gridGL/cells/tables/Tables.ts
Labels: cla-signed, status: ready to merge, QA

#2895 Decrypt team
  quadratic-api/src/routes/v0/internal.user.$auth0Id.teams.$uuid.GET.ts
Labels: cla-signed, status: ready to merge

#2896 fix: language icons
  quadratic-client/src/shared/components/LanguageIcon.tsx
Labels: cla-signed

#2897 Fix bug with flattening one-cell formula
  quadratic-core/src/grid/data_table/display_value.rs
  quadratic-core/src/test_util/create_code_table.rs
  quadratic-core/src/values/array.rs
  quadratic-files/Cargo.lock
Labels: cla-signed, status: ready for user test, QA

#2892 Fixes bug with multiple col/rows resizing
  quadratic-client/src/app/actions/columnRowSpec.ts
  quadratic-client/src/app/actions/dataTableSpec.ts
  quadratic-client/src/app/grid/sheet/SheetCursor.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerHeading.ts
  quadratic-client/src/app/ui/menus/BottomBar/KernelMenu.tsx
  quadratic-core/src/a1/a1_selection/query.rs
  quadratic-core/src/a1/js_selection/query.rs
Labels: cla-signed, status: ready for code review, QA

#2913 Version 0.8.0
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: cla-signed

#2916 update versions
  package-lock.json
  quadratic-client/public/version.json
  quadratic-connection/Cargo.lock
  quadratic-core/Cargo.lock
  quadratic-files/Cargo.lock
  quadratic-multiplayer/Cargo.lock
  quadratic-rust-shared/Cargo.lock
Labels: cla-signed

#2919 Reduce webhook feedback message limit
  quadratic-api/src/routes/v0/feedback.POST.ts
Labels: cla-signed, status: ready to merge

#2907 Fixes bug with rename table name
  quadratic-client/src/app/gridGL/HTMLGrid/contextMenus/PixiRename.tsx
Labels: status: ready to merge

#2893 Adds a minimum size for the scrollbar
  quadratic-client/src/app/gridGL/HTMLGrid/scrollBars/ScrollBarsHandler.ts
Labels: cla-signed, status: ready to merge

#2721 feat: require valid connection to create/update
  quadratic-client/src/shared/components/Icons.tsx
  quadratic-client/src/shared/components/connections/ConnectionForm.tsx
  quadratic-client/src/shared/components/connections/ConnectionFormActions.tsx
  quadratic-client/src/shared/components/connections/ConnectionsSidebar.tsx
  quadratic-client/src/shared/components/connections/connectionsByType.ts
  quadratic-client/src/shared/shadcn/ui/alert.tsx
Labels: cla-signed, status: ready to merge

#2928 chore: upgrade to node 24
  .github/workflows/ci.yml
  .github/workflows/production-deploy.yml
  .github/workflows/qa-deploy.yml
  .nvmrc
  Dockerfile.dev
  infra/package.json
  package.json
  quadratic-api/Dockerfile
  quadratic-api/package.json
  quadratic-client/Dockerfile
  quadratic-client/package.json
  quadratic-shared/package.json
Labels: cla-signed, status: ready to merge

#2933 fix: qa / prod ci deployment
  .github/workflows/ci.yml
  .github/workflows/production-deploy.yml
  .github/workflows/qa-deploy.yml
  quadratic-core/Cargo.toml
  quadratic-core/src/controller/execution/execute_operation/execute_data_table.rs
  quadratic-core/src/controller/formula.rs
  quadratic-core/src/grid/file/v1_7_1/sheet_offsets/mod.rs
  quadratic-core/src/grid/formats/sheet_format_updates.rs
  quadratic-core/src/grid/sheet.rs
  quadratic-core/src/grid/sheet/cell_array.rs
  quadratic-core/src/grid/sheet/validations/rules/validation_date_time.rs
  quadratic-core/src/grid/sheet/validations/rules/validation_number.rs
Labels: cla-signed, status: ready to merge

#2679 Send and receive binary transactions to/from multiplayer
  .github/workflows/ci.yml
  .vscode/settings.json
  Cargo.lock
  package.json
  quadratic-client/.eslintignore
  quadratic-client/Dockerfile
  quadratic-client/package.json
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayerCoreMessages.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayerTypes.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/proto/transaction.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/worker/multiplayerCore.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/worker/multiplayerServer.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreMultiplayer.ts
  quadratic-connection/Cargo.toml
  quadratic-connection/Dockerfile
  quadratic-core/Cargo.toml
  quadratic-core/package.json
  quadratic-core/src/compression.rs
  quadratic-core/src/controller/execution/receive_multiplayer.rs
  quadratic-core/src/controller/transaction.rs
  quadratic-core/src/wasm_bindings/controller/transactions.rs
  quadratic-files/Cargo.toml
  quadratic-files/Dockerfile
  quadratic-files/src/file.rs
  quadratic-multiplayer/Cargo.toml
  quadratic-multiplayer/Dockerfile
  quadratic-multiplayer/src/background_worker.rs
  quadratic-multiplayer/src/error.rs
  quadratic-multiplayer/src/message/handle.rs
  quadratic-multiplayer/src/message/mod.rs
  quadratic-multiplayer/src/message/proto/mod.rs
  quadratic-multiplayer/src/message/proto/request.rs
  quadratic-multiplayer/src/message/proto/response.rs
  quadratic-multiplayer/src/message/request.rs
  quadratic-multiplayer/src/message/response.rs
  quadratic-multiplayer/src/server.rs
  quadratic-multiplayer/src/state/pubsub.rs
  quadratic-rust-shared/Cargo.toml
  quadratic-rust-shared/build.rs
  quadratic-rust-shared/src/arrow/error.rs
  quadratic-rust-shared/src/auth/error.rs
  quadratic-rust-shared/src/error.rs
  quadratic-rust-shared/src/lib.rs
  quadratic-rust-shared/src/protobuf/mod.rs
  quadratic-rust-shared/src/protobuf/proto/transaction.proto
  quadratic-rust-shared/src/pubsub/error.rs
  quadratic-rust-shared/src/pubsub/mod.rs
  quadratic-rust-shared/src/sql/error.rs
  quadratic-rust-shared/src/sql/snowflake_connection.rs
Labels: cla-signed

#2938 Revert "Send and receive binary transactions to/from multiplayer"
  .github/workflows/ci.yml
  .vscode/settings.json
  Cargo.lock
  package.json
  quadratic-client/.eslintignore
  quadratic-client/Dockerfile
  quadratic-client/package.json
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayerCoreMessages.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayerTypes.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/proto/transaction.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/worker/multiplayerCore.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/worker/multiplayerServer.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreMultiplayer.ts
  quadratic-connection/Cargo.toml
  quadratic-connection/Dockerfile
  quadratic-core/Cargo.toml
  quadratic-core/package.json
  quadratic-core/src/compression.rs
  quadratic-core/src/controller/execution/receive_multiplayer.rs
  quadratic-core/src/controller/transaction.rs
  quadratic-core/src/wasm_bindings/controller/transactions.rs
  quadratic-files/Cargo.toml
  quadratic-files/Dockerfile
  quadratic-files/src/file.rs
  quadratic-multiplayer/Cargo.toml
  quadratic-multiplayer/Dockerfile
  quadratic-multiplayer/src/background_worker.rs
  quadratic-multiplayer/src/error.rs
  quadratic-multiplayer/src/message/handle.rs
  quadratic-multiplayer/src/message/mod.rs
  quadratic-multiplayer/src/message/proto/mod.rs
  quadratic-multiplayer/src/message/proto/request.rs
  quadratic-multiplayer/src/message/proto/response.rs
  quadratic-multiplayer/src/message/request.rs
  quadratic-multiplayer/src/message/response.rs
  quadratic-multiplayer/src/server.rs
  quadratic-multiplayer/src/state/pubsub.rs
  quadratic-rust-shared/Cargo.toml
  quadratic-rust-shared/build.rs
  quadratic-rust-shared/src/arrow/error.rs
  quadratic-rust-shared/src/auth/error.rs
  quadratic-rust-shared/src/error.rs
  quadratic-rust-shared/src/lib.rs
  quadratic-rust-shared/src/protobuf/mod.rs
  quadratic-rust-shared/src/protobuf/proto/transaction.proto
  quadratic-rust-shared/src/pubsub/error.rs
  quadratic-rust-shared/src/pubsub/mod.rs
  quadratic-rust-shared/src/sql/error.rs
  quadratic-rust-shared/src/sql/snowflake_connection.rs
Labels: cla-signed

#2940 Revert "Revert "Send and receive binary transactions to/from multiplayer""
  .github/workflows/ci.yml
  .vscode/settings.json
  Cargo.lock
  VERSION
  package.json
  quadratic-api/Dockerfile
  quadratic-api/package.json
  quadratic-api/src/utils/teams.ts
  quadratic-api/tsconfig.production.json
  quadratic-client/.eslintignore
  quadratic-client/Dockerfile
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayerCoreMessages.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayerTypes.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/proto/transaction.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/worker/multiplayerCore.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/worker/multiplayerServer.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreMultiplayer.ts
  quadratic-connection/Cargo.toml
  quadratic-connection/Dockerfile
  quadratic-core/Cargo.toml
  quadratic-core/package.json
  quadratic-core/src/compression.rs
  quadratic-core/src/controller/execution/receive_multiplayer.rs
  quadratic-core/src/controller/transaction.rs
  quadratic-core/src/wasm_bindings/controller/transactions.rs
  quadratic-files/Cargo.toml
  quadratic-files/Dockerfile
  quadratic-files/src/file.rs
  quadratic-multiplayer/Cargo.toml
  quadratic-multiplayer/Dockerfile
  quadratic-multiplayer/package.json
  quadratic-multiplayer/src/background_worker.rs
  quadratic-multiplayer/src/error.rs
  quadratic-multiplayer/src/message/handle.rs
  quadratic-multiplayer/src/message/mod.rs
  quadratic-multiplayer/src/message/proto/mod.rs
  quadratic-multiplayer/src/message/proto/request.rs
  quadratic-multiplayer/src/message/proto/response.rs
  quadratic-multiplayer/src/message/request.rs
  quadratic-multiplayer/src/message/response.rs
  quadratic-multiplayer/src/server.rs
  quadratic-multiplayer/src/state/pubsub.rs
  quadratic-multiplayer/src/test_util.rs
  quadratic-rust-shared/Cargo.toml
  quadratic-rust-shared/build.rs
  quadratic-rust-shared/src/arrow/error.rs
  quadratic-rust-shared/src/auth/error.rs
  quadratic-rust-shared/src/error.rs
  quadratic-rust-shared/src/lib.rs
  quadratic-rust-shared/src/net/ssh_tunnel.rs
  quadratic-rust-shared/src/protobuf/mod.rs
  quadratic-rust-shared/src/protobuf/proto/transaction.proto
  quadratic-rust-shared/src/pubsub/error.rs
  quadratic-rust-shared/src/pubsub/mod.rs
  quadratic-rust-shared/src/sql/error.rs
  quadratic-rust-shared/src/sql/snowflake_connection.rs
  quadratic-shared/package.json
Labels: cla-signed, status: ready for code review

#2961 More mp tests and logs
  quadratic-core/src/controller/transaction.rs
  quadratic-multiplayer/src/message/handle.rs
Labels: cla-signed

#2951 Adds back /cargo.toml
  .github/workflows/ci.yml
  Cargo.toml
  bump.sh
  quadratic-api/src/utils/teams.ts
  quadratic-client/package.json
  quadratic-client/src/app/quadratic-core-types/index.d.ts
  quadratic-connection/src/connection.rs
  quadratic-rust-shared/src/net/ssh_tunnel.rs
  quadratic-rust-shared/src/sql/mssql_connection.rs
  quadratic-rust-shared/src/sql/mysql_connection.rs
  quadratic-rust-shared/src/sql/postgres_connection.rs
Labels: cla-signed, status: ready to merge

#2943 Provides proper parsing for (15)%
  quadratic-core/src/values/cellvalue.rs
Labels: cla-signed, status: ready to merge

#2920 F4 toggles cell ref types (eg, A1 to $A$1) when editing a formula
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorFormula.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorKeyboard.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorMonaco.ts
  quadratic-core/src/a1/a1_context/mod.rs
  quadratic-core/src/a1/cell_ref_end.rs
  quadratic-core/src/wasm_bindings/a1.rs
  quadratic-core/src/wasm_bindings/controller/bounds.rs
  quadratic-core/src/wasm_bindings/mod.rs
Labels: cla-signed, status: ready to merge

#2909 Minor tweaks to attempt to fix the freezing viewport
  quadratic-client/src/app/debugFlags.ts
  quadratic-client/src/app/gridGL/pixiApp/PixiApp.ts
  quadratic-client/src/app/gridGL/pixiApp/Update.ts
  quadratic-client/src/app/gridGL/pixiApp/copyAsPNG.ts
  quadratic-client/src/app/gridGL/pixiApp/thumbnail.ts
  quadratic-client/src/app/gridGL/pixiApp/viewport/Wheel.ts
Labels: cla-signed, status: ready to merge

#2908 Fixes moving a negative selection
  quadratic-client/src/app/gridGL/UI/Cursor.ts
  quadratic-client/src/app/gridGL/helpers/intersects.test.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerCellMoving.ts
Labels: cla-signed, status: ready to merge

#2954 Fix copy chart
  quadratic-core/src/a1/table_ref/convert.rs
  quadratic-core/src/controller/operations/clipboard.rs
  quadratic-core/src/controller/user_actions/clipboard.rs
  quadratic-core/src/test_util/create_chart.rs
Labels: cla-signed, status: ready to merge

#2967 Binary Transactions
  .github/workflows/ci.yml
  .vscode/settings.json
  Cargo.toml
  VERSION
  package.json
  quadratic-api/Dockerfile
  quadratic-api/package.json
  quadratic-client/.eslintignore
  quadratic-client/Dockerfile
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayerCoreMessages.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayerTypes.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/proto/transaction.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/worker/multiplayerCore.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/worker/multiplayerServer.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreMultiplayer.ts
  quadratic-connection/Cargo.toml
  quadratic-connection/Dockerfile
  quadratic-core/Cargo.toml
  quadratic-core/package.json
  quadratic-core/src/compression.rs
  quadratic-core/src/controller/execution/receive_multiplayer.rs
  quadratic-core/src/controller/transaction.rs
  quadratic-core/src/wasm_bindings/controller/transactions.rs
  quadratic-files/Cargo.toml
  quadratic-files/Dockerfile
  quadratic-files/src/file.rs
  quadratic-multiplayer/Cargo.toml
  quadratic-multiplayer/Dockerfile
  quadratic-multiplayer/package.json
  quadratic-multiplayer/src/background_worker.rs
  quadratic-multiplayer/src/error.rs
  quadratic-multiplayer/src/message/handle.rs
  quadratic-multiplayer/src/message/mod.rs
  quadratic-multiplayer/src/message/proto/mod.rs
  quadratic-multiplayer/src/message/proto/request.rs
  quadratic-multiplayer/src/message/proto/response.rs
  quadratic-multiplayer/src/message/request.rs
  quadratic-multiplayer/src/message/response.rs
  quadratic-multiplayer/src/server.rs
  quadratic-multiplayer/src/state/pubsub.rs
  quadratic-multiplayer/src/test_util.rs
  quadratic-rust-shared/Cargo.toml
  quadratic-rust-shared/build.rs
  quadratic-rust-shared/src/arrow/error.rs
  quadratic-rust-shared/src/auth/error.rs
  quadratic-rust-shared/src/error.rs
  quadratic-rust-shared/src/lib.rs
  quadratic-rust-shared/src/protobuf/mod.rs
  quadratic-rust-shared/src/protobuf/proto/transaction.proto
  quadratic-rust-shared/src/pubsub/error.rs
  quadratic-rust-shared/src/pubsub/mod.rs
  quadratic-rust-shared/src/sql/error.rs
  quadratic-rust-shared/src/sql/snowflake_connection.rs
  quadratic-rust-shared/src/test/benchmark.rs
  quadratic-rust-shared/src/test/mod.rs
  quadratic-shared/package.json
Labels: cla-signed

#2953 Fix resizing
  quadratic-client/src/app/gridGL/interaction/pointer/PointerHeading.ts
  quadratic-core/src/a1/a1_selection/query.rs
  quadratic-core/src/sheet_offsets/sheet_offsets_wasm.rs
Labels: cla-signed, status: ready to merge, e2e

#2952 Insert mulitple columns/rows
  quadratic-client/src/app/actions/columnRowSpec.ts
  quadratic-client/src/app/actions/insertActionsSpec.ts
  quadratic-client/src/app/grid/sheet/SheetCursor.ts
  quadratic-client/src/app/gridGL/HTMLGrid/contextMenus/GridContextMenuCell.tsx
  quadratic-client/src/app/web-workers/quadraticCore/coreClientMessages.ts
  quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
  quadratic-core/src/a1/a1_selection/query.rs
  quadratic-core/src/a1/js_selection/query.rs
  quadratic-core/src/controller/execution/execute_operation/execute_col_rows.rs
  quadratic-core/src/controller/user_actions/col_row.rs
  quadratic-core/src/grid/sheet/borders/borders_col_row.rs
  quadratic-core/src/grid/sheet/col_row/columns_insert_table.rs
  quadratic-core/src/grid/sheet/col_row/rows_insert_table.rs
  quadratic-core/src/wasm_bindings/controller/col_row.rs
Labels: cla-signed, status: ready to merge, e2e

#2900 refactor: UI tweaks
  quadratic-client/src/app/atoms/editorInteractionStateAtom.ts
  quadratic-client/src/app/ui/QuadraticSidebar.tsx
  quadratic-client/src/app/ui/components/AIUserMessageForm.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystHeader.tsx
  quadratic-client/src/app/ui/menus/CellTypeMenu/CellTypeMenu.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorHeaderLabel.tsx
  quadratic-client/src/app/ui/menus/ConnectionsMenu/ConnectionsMenu.tsx
  quadratic-client/src/shared/components/Icons.tsx
  quadratic-client/src/shared/components/connections/Connections.tsx
  quadratic-client/src/shared/components/connections/ConnectionsList.tsx
Labels: cla-signed, status: requested changes, QA

#2803 [WIP] Fine-tuned 4.1
  .gitignore
  quadratic-api/package.json
  quadratic-api/prisma/migrations/20250520104549_add_model_router_source/migration.sql
  quadratic-api/prisma/schema.prisma
  quadratic-api/src/ai/docs/FormulaDocs.ts
  quadratic-api/src/ai/docs/PythonDocs.ts
  quadratic-api/src/ai/handler/ai.handler.ts
  quadratic-api/src/ai/handler/anthropic.handler.ts
  quadratic-api/src/ai/handler/bedrock.handler.ts
  quadratic-api/src/ai/handler/openai.handler.ts
  quadratic-api/src/ai/handler/vertexai.handler.ts
  quadratic-api/src/ai/helpers/anthropic.helper.ts
  quadratic-api/src/ai/helpers/bedrock.helper.ts
  quadratic-api/src/ai/helpers/fineTuning.helper.ts
  quadratic-api/src/ai/helpers/modelRouter.helper.ts
  quadratic-api/src/ai/helpers/openai.helper.ts
  quadratic-api/src/ai/helpers/vertexai.helper.ts
  quadratic-api/src/routes/v0/ai.chat.POST.test.ts
  quadratic-api/src/routes/v0/ai.chat.POST.ts
  quadratic-client/src/app/ai/hooks/useAIRequestToAPI.tsx
  quadratic-client/src/app/ai/offline/aiAnalystChats.test.ts
  quadratic-client/src/app/ai/tools/aiToolsActions.ts
  quadratic-client/src/app/debugFlags.ts
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystEffects.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystMessages.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/hooks/useSubmitAIAnalystPrompt.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/hooks/useSubmitAIAssistantPrompt.tsx
  quadratic-core/Cargo.toml
  quadratic-shared/ai/helpers/message.helper.ts
  quadratic-shared/ai/helpers/model.helper.ts
  quadratic-shared/ai/models/AI_MODELS.ts
  quadratic-shared/ai/specs/aiToolsSpec.ts
  quadratic-shared/typesAndSchemasAI.ts
Labels: cla-signed, prototype

#2969 Turn off extra MP logging
  quadratic-multiplayer/src/message/handle.rs
Labels: cla-signed, status: ready to merge

#2985 chore: try claude 4 models
  quadratic-api/package.json
  quadratic-api/src/ai/docs/ConnectionDocs.ts
  quadratic-api/src/ai/docs/FormulaDocs.ts
  quadratic-api/src/ai/docs/PythonDocs.ts
  quadratic-api/src/ai/docs/QuadraticDocs.ts
  quadratic-client/src/app/ai/toolCards/SetCodeCellValue.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/hooks/useSubmitAIAnalystPrompt.tsx
  quadratic-multiplayer/src/message/handle.rs
  quadratic-shared/ai/helpers/model.helper.ts
  quadratic-shared/ai/models/AI_MODELS.ts
  quadratic-shared/ai/specs/aiToolsSpec.ts
  quadratic-shared/typesAndSchemasAI.ts
Labels: cla-signed, prototype

#2683 Document `SheetMap` and use bi-directional map
  quadratic-core/src/a1/a1_context/mod.rs
  quadratic-core/src/a1/a1_context/sheet_map.rs
  quadratic-core/src/a1/js_selection/validate_name.rs
  quadratic-core/src/controller/execution/auto_resize_row_heights.rs
  quadratic-core/src/controller/execution/execute_operation/execute_col_rows.rs
  quadratic-core/src/controller/execution/execute_operation/execute_sheets.rs
  quadratic-core/src/controller/execution/receive_multiplayer.rs
  quadratic-core/src/controller/operations/code_cell.rs
  quadratic-core/src/controller/operations/import.rs
  quadratic-core/src/controller/operations/sheets.rs
  quadratic-core/src/controller/sheet_offsets.rs
  quadratic-core/src/controller/sheets.rs
  quadratic-core/src/grid/a1_context.rs
  quadratic-core/src/grid/cells_accessed_cache.rs
  quadratic-core/src/grid/code_cell.rs
  quadratic-core/src/grid/data_table/mod.rs
  quadratic-core/src/grid/file/migrate_code_cell_references.rs
  quadratic-core/src/grid/file/migrate_data_table_spills.rs
  quadratic-core/src/grid/file/serialize/mod.rs
  quadratic-core/src/grid/file/shift_negative_offsets.rs
  quadratic-core/src/grid/mod.rs
  quadratic-core/src/grid/search.rs
  quadratic-core/src/grid/sheet.rs
  quadratic-core/src/grid/sheets.rs
  quadratic-core/src/wasm_bindings/controller/ai_context.rs
  quadratic-core/src/wasm_bindings/controller/bounds.rs
  quadratic-core/src/wasm_bindings/controller/cells.rs
  quadratic-core/src/wasm_bindings/controller/code.rs
  quadratic-core/src/wasm_bindings/controller/formatting.rs
  quadratic-core/src/wasm_bindings/controller/render.rs
  quadratic-core/src/wasm_bindings/controller/search.rs
  quadratic-core/src/wasm_bindings/controller/sheet_offsets.rs
  quadratic-core/src/wasm_bindings/controller/sheets.rs
Labels: cla-signed, status: ready to merge, type: perf

#2955 Fix csv error
  .vscode/settings.json
  quadratic-client/src/app/ui/QuadraticUI.tsx
  quadratic-client/src/app/ui/components/CSVImportSettings.tsx
  quadratic-client/src/app/ui/hooks/useFileImport.tsx
  quadratic-client/src/app/ui/hooks/useGetCSVImportSettings.tsx
  quadratic-client/src/app/web-workers/quadraticCore/coreClientMessages.ts
  quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
  quadratic-client/src/dashboard/atoms/filesImportSettingsAtom.ts
  quadratic-client/src/routes/_dashboard.tsx
  quadratic-core/Cargo.toml
  quadratic-core/src/controller/operations/csv.rs
  quadratic-core/src/controller/operations/import.rs
  quadratic-core/src/controller/operations/mod.rs
  quadratic-core/src/controller/user_actions/import.rs
  quadratic-core/src/wasm_bindings/controller/import.rs
  quadratic-rust-shared/data/csv/kaggle_top_100_dataset.csv
Labels: cla-signed, status: ready to merge

#2993 Fix formula short-circuiting
  quadratic-core/src/formulas/ast.rs
  quadratic-core/src/formulas/functions/logic.rs
  quadratic-core/src/formulas/tests.rs
Labels: cla-signed, status: ready to merge

#2988 Show when code was last run
  quadratic-client/src/app/actions/insertActionsSpec.ts
  quadratic-client/src/app/ai/toolCards/SetCodeCellValue.tsx
  quadratic-client/src/app/atoms/codeEditorAtom.ts
  quadratic-client/src/app/grid/actions/openCodeEditor.ts
  quadratic-client/src/app/gridGL/HTMLGrid/hoverCell/HoverCell.tsx
  quadratic-client/src/app/gridGL/HTMLGrid/htmlCells/HtmlCell.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorHandler.ts
  quadratic-client/src/app/gridGL/HTMLGrid/inlineEditor/inlineEditorKeyboard.ts
  quadratic-client/src/app/gridGL/cells/tables/TableName.ts
  quadratic-client/src/app/gridGL/cells/tables/Tables.ts
  quadratic-client/src/app/gridGL/interaction/pointer/PointerTable.ts
  quadratic-client/src/app/gridGL/interaction/pointer/doubleClickCell.ts
  quadratic-client/src/app/gridGL/pixiApp/urlParams/UrlParamsDev.ts
  quadratic-client/src/app/gridGL/pixiApp/urlParams/UrlParamsUser.ts
  quadratic-client/src/app/quadratic-core-types/index.d.ts
  quadratic-client/src/app/shared/types/codeCell.ts
  quadratic-client/src/app/ui/menus/CodeEditor/ReturnTypeInspector.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/hooks/useSaveAndRunCell.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/hooks/useUpdateCodeEditor.tsx
  quadratic-client/src/shared/utils/timeAgo.test.ts
  quadratic-client/src/shared/utils/timeAgo.ts
  quadratic-core/src/grid/js_types.rs
  quadratic-core/src/grid/sheet/ai_context.rs
  quadratic-core/src/grid/sheet/code.rs
  quadratic-core/src/grid/sheet/rendering/code.rs
  quadratic-shared/typesAndSchemasAI.ts
Labels: cla-signed, status: ready to merge, QA

#3002 fix: infinite formatting bounds handling in selection, core stuck
  quadratic-client/src/app/web-workers/quadraticCore/coreClientMessages.ts
  quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
  quadratic-core/src/a1/a1_selection/query.rs
  quadratic-core/src/controller/execution/execute_operation/execute_validation.rs
  quadratic-core/src/controller/execution/run_code/get_cells.rs
  quadratic-core/src/controller/export.rs
  quadratic-core/src/controller/operations/cell_value.rs
  quadratic-core/src/controller/operations/csv.rs
  quadratic-core/src/formulas/ast.rs
  quadratic-core/src/formulas/ctx.rs
  quadratic-core/src/formulas/functions/lookup.rs
  quadratic-core/src/grid/sheet.rs
  quadratic-core/src/grid/sheet/a1_selection.rs
  quadratic-core/src/grid/sheet/ai_context.rs
  quadratic-core/src/grid/sheet/bounds/mod.rs
  quadratic-core/src/grid/sheet/clipboard.rs
  quadratic-core/src/grid/sheet/summarize.rs
  quadratic-core/src/grid/sheet/validations/rules/validation_list.rs
  quadratic-core/src/wasm_bindings/controller/bounds.rs
Labels: cla-signed, status: ready to merge, QA

#2945 feat: onboarding questionnaire
  quadratic-api/prisma/migrations/20250522195705_add_user_onboarding_responses/migration.sql
  quadratic-api/prisma/schema.prisma
  quadratic-api/src/routes/v0/user.POST.test.ts
  quadratic-api/src/routes/v0/user.POST.ts
  quadratic-api/src/routes/v0/user.acknowledge.GET.ts
  quadratic-api/src/routes/v0/users.acknowledge.GET.ts
  quadratic-client/src/app/ai/toolCards/AddDataTable.tsx
  quadratic-client/src/app/ai/toolCards/ToolCard.tsx
  quadratic-client/src/dashboard/onboarding/Controls.tsx
  quadratic-client/src/dashboard/onboarding/Questions.tsx
  quadratic-client/src/dashboard/onboarding/getPrompt.test.ts
  quadratic-client/src/dashboard/onboarding/getPrompt.ts
  quadratic-client/src/router.tsx
  quadratic-client/src/routes/login-result.tsx
  quadratic-client/src/routes/onboarding.tsx
  quadratic-client/src/shared/api/apiClient.ts
  quadratic-client/src/shared/components/Icons.tsx
  quadratic-client/src/shared/components/LanguageIcon.tsx
  quadratic-client/src/shared/components/icons.css
  quadratic-shared/typesAndSchemas.ts
Labels: cla-signed, status: ready to merge, QA

#3009 Fix positioning of table's modified date
  quadratic-client/src/app/gridGL/cells/tables/TableName.ts
Labels: status: ready for code review, status: ready for user test
