Repository quadratichq/quadratic, pull requests merged in 2025-08, with the labels that each got.

#3327 fix: use dexie for IndexedDb
  .vscode/settings.json
  quadratic-client/package.json
  quadratic-client/src/app/actions/editActionsSpec.ts
  quadratic-client/src/app/ai/iframeAiChatFiles/IframeAiChatFiles.ts
  quadratic-client/src/app/ai/offline/aiAnalystChats.ts
  quadratic-client/src/app/grid/actions/clipboard/clipboard.ts
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardClipboard.ts
  quadratic-client/src/app/helpers/convertColor.ts
  quadratic-client/src/app/ui/hooks/useFileImport.tsx
  quadratic-client/src/app/ui/menus/CommandPalette/commands/Edit.tsx
  quadratic-client/src/app/web-workers/multiplayerWebWorker/multiplayer.ts
  quadratic-client/src/app/web-workers/multiplayerWebWorker/worker/multiplayerServer.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/offline.test.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/offline.ts
  quadratic-client/src/shared/components/EmptyPage.tsx
  quadratic-client/src/shared/utils/error.ts
Labels: cla-signed, status: ready to merge, QA

#3335 fix: offline syncing state
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
Labels: cla-signed, QA

#3339 fix: auto correct ai args types
  quadratic-shared/ai/specs/aiToolsSpec.ts
Labels: cla-signed, status: ready for user test, QA

#3342 fix: onboarding hang
  quadratic-client/src/routes/logout.tsx
  quadratic-client/src/routes/onboarding.tsx
  quadratic-client/src/shared/utils/analyticsEvents.ts
Labels: cla-signed, status: ready to merge, QA

#3210 feat: did you know tooltip (for model picker)
  quadratic-api/prisma/migrations/20250710215644_add_user_client_data_kv/migration.sql
  quadratic-api/prisma/schema.prisma
  quadratic-api/src/routes/v0/files.$uuid.GET.ts
  quadratic-api/src/routes/v0/user.client-data-kv.POST.test.ts
  quadratic-api/src/routes/v0/user.client-data-kv.POST.ts
  quadratic-api/src/utils/userClientData.ts
  quadratic-client/src/app/ai/components/SelectAIModelMenu.tsx
  quadratic-client/src/app/ai/hooks/useUserDataKv.tsx
  quadratic-client/src/app/ui/components/AIUserMessageForm.tsx
  quadratic-client/src/app/ui/components/DidYouKnowPopover.tsx
  quadratic-client/src/shared/api/apiClient.ts
  quadratic-client/src/shared/components/Icons.tsx
  quadratic-shared/typesAndSchemas.ts
Labels: cla-signed, status: ready to merge, QA

#3344 QA Aug 7th
  Cargo.toml
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-api/prisma/migrations/20250710215644_add_user_client_data_kv/migration.sql
  quadratic-api/prisma/schema.prisma
  quadratic-api/src/ai/handler/ai.handler.ts
  quadratic-api/src/ai/handler/openai.chatCompletions.handler.ts
  quadratic-api/src/ai/handler/openai.responses.handler.ts
  quadratic-api/src/ai/helpers/anthropic.helper.ts
  quadratic-api/src/ai/helpers/fineTuning.helper.ts
  quadratic-api/src/ai/helpers/modelRouter.helper.ts
  quadratic-api/src/ai/helpers/openai.chatCompletions.helper.ts
  quadratic-api/src/ai/helpers/openai.responses.helper.ts
  quadratic-api/src/routes/v0/ai.chat.POST.test.ts
  quadratic-api/src/routes/v0/files.$uuid.GET.ts
  quadratic-api/src/routes/v0/teams.$uuid.billing.ai.usage.GET.test.ts
  quadratic-api/src/routes/v0/user.client-data-kv.POST.test.ts
  quadratic-api/src/routes/v0/user.client-data-kv.POST.ts
  quadratic-api/src/tests/testDataGenerator.ts
  quadratic-api/src/utils/userClientData.ts
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-client/src/app/ai/components/SelectAIModelMenu.tsx
  quadratic-client/src/app/ai/hooks/useAIModel.tsx
  quadratic-client/src/app/ai/hooks/useUserDataKv.tsx
  quadratic-client/src/app/ui/components/AIUserMessageForm.tsx
  quadratic-client/src/app/ui/components/AIUserMessageFormDisclaimer.tsx
  quadratic-client/src/app/ui/components/DidYouKnowPopover.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystMessages.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/AIAssistant/AIAssistantMessages.tsx
  quadratic-client/src/dashboard/components/OnboardingBanner.tsx
  quadratic-client/src/dashboard/onboarding/Questions.tsx
  quadratic-client/src/shared/api/apiClient.ts
  quadratic-client/src/shared/components/Icons.tsx
  quadratic-client/src/shared/components/connections/ConnectionSchemaBrowser.tsx
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/ai/helpers/message.helper.ts
  quadratic-shared/ai/models/AI_MODELS.ts
  quadratic-shared/package.json
  quadratic-shared/typesAndSchemas.ts
  quadratic-shared/typesAndSchemasAI.ts
Labels: cla-signed

#3353 Alert users in members page that adding members while on Pro costs per seat
  quadratic-client/src/routes/teams.$teamUuid.members.tsx
Labels: cla-signed, status: ready for code review, status: ready for user test

#3349 chore: lock rust version
  .github/workflows/ci.yml
  .vscode/settings.json
  quadratic-connection/rust-toolchain.toml
  quadratic-core/rust-toolchain.toml
  quadratic-files/rust-toolchain.toml
  quadratic-multiplayer/rust-toolchain.toml
  quadratic-rust-shared/rust-toolchain.toml
  rust-toolchain.toml
  update-rust-toolchain.sh
Labels: cla-signed, status: ready to merge

#3352 fix: docker vulnerability, use ubuntu as base image
  Dockerfile.dev
  Procfile
  app.json
  docker-compose.yml
  infra/client/build-client-ci.sh
  package.json
  quadratic-api/Dockerfile
  quadratic-client/Dockerfile
  quadratic-connection/Dockerfile
  quadratic-files/Dockerfile
  quadratic-multiplayer/Dockerfile
Labels: cla-signed, status: ready for user test

#3356 chore: add openai service tier, use priority for gpt-5
  Cargo.toml
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-api/src/ai/handler/openai.responses.handler.ts
  quadratic-api/src/routes/v0/ai.chat.POST.ts
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-client/src/app/ai/hooks/useAIRequestToAPI.tsx
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/ai/helpers/model.helper.ts
  quadratic-shared/ai/models/AI_MODELS.ts
  quadratic-shared/package.json
  quadratic-shared/typesAndSchemasAI.ts
Labels: cla-signed, status: ready to merge

#3360 chore: add route for user email migration
  quadratic-api/src/auth/auth0.test.ts
  quadratic-api/src/middleware/getTeam.test.ts
  quadratic-api/src/middleware/user.test.ts
  quadratic-api/src/routes/internal/index.ts
  quadratic-api/src/routes/internal/user-email-migration.$take.GET.ts
  quadratic-api/src/routes/v0/education.POST.test.ts
  quadratic-api/src/routes/v0/files.$uuid.invites.POST.test.ts
  quadratic-api/src/routes/v0/files.$uuid.sharing.GET.test.ts
  quadratic-api/src/routes/v0/teams.$uuid.GET.test.ts
  quadratic-api/src/routes/v0/teams.$uuid.invites.POST.test.ts
Labels: cla-signed, status: ready to merge

#3363 fix: skip on missing email during migration
  Cargo.toml
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-api/src/auth/auth.ts
  quadratic-api/src/auth/auth0.ts
  quadratic-api/src/routes/internal/user-email-migration.$take.GET.ts
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: cla-signed, status: ready for code review

#3362 QA Aug 13th
  Cargo.toml
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-api/src/auth/auth.ts
  quadratic-api/src/auth/auth0.ts
  quadratic-api/src/routes/internal/user-email-migration.$take.GET.ts
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/package.json
Labels: cla-signed

#3367 fix: minor ai chat bugs
  quadratic-api/src/ai/helpers/modelRouter.helper.ts
  quadratic-client/src/app/ai/hooks/useAIRequestToAPI.tsx
  quadratic-client/src/app/ai/tools/aiToolsActions.ts
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystDebugChatInput.tsx
  quadratic-shared/ai/models/AI_MODELS.ts
Labels: cla-signed, status: ready to merge, QA

#3340 feat: potential connections
  .vscode/settings.json
  quadratic-api/prisma/migrations/20250813181554_add_context_to_feedback/migration.sql
  quadratic-api/prisma/schema.prisma
  quadratic-api/src/routes/v0/feedback.POST.ts
  quadratic-client/package.json
  quadratic-client/src/auth/auth0.ts
  quadratic-client/src/auth/ory.ts
  quadratic-client/src/index.tsx
  quadratic-client/src/routes/file.$uuid.tsx
  quadratic-client/src/routes/file.tsx
  quadratic-client/src/routes/onboarding.tsx
  quadratic-client/src/routes/teams.$teamUuid.files.create.tsx
  quadratic-client/src/shared/api/apiClient.ts
  quadratic-client/src/shared/api/fetchFromApi.ts
  quadratic-client/src/shared/api/xhrFromApi.ts
  quadratic-client/src/shared/components/connections/Connections.tsx
  quadratic-client/src/shared/components/connections/ConnectionsNew.tsx
  quadratic-client/src/shared/components/connections/ConnectionsPotential.tsx
  quadratic-client/src/shared/components/connections/connectionsByType.ts
  quadratic-client/src/shared/components/connections/logo-athena.svg
  quadratic-client/src/shared/components/connections/logo-cassandra.svg
  quadratic-client/src/shared/components/connections/logo-clickhouse.svg
  quadratic-client/src/shared/components/connections/logo-databricks.svg
  quadratic-client/src/shared/components/connections/logo-dynamodb.svg
  quadratic-client/src/shared/components/connections/logo-mongodb.svg
  quadratic-client/src/shared/components/connections/logo-oracle.svg
  quadratic-client/src/shared/components/connections/logo-redshift.svg
  quadratic-client/src/shared/components/connections/logo-s3.svg
  quadratic-client/src/shared/shadcn/ui/breadcrumb.tsx
  quadratic-shared/typesAndSchemas.ts
Labels: cla-signed, status: ready to merge, QA

#3365 QA Auth 13th - 2
  .vscode/settings.json
  Cargo.toml
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-api/prisma/migrations/20250813181554_add_context_to_feedback/migration.sql
  quadratic-api/prisma/schema.prisma
  quadratic-api/src/ai/helpers/modelRouter.helper.ts
  quadratic-api/src/auth/auth.ts
  quadratic-api/src/auth/auth0.ts
  quadratic-api/src/routes/internal/index.ts
  quadratic-api/src/routes/internal/user-email-migration.$take.GET.ts
  quadratic-api/src/routes/v0/feedback.POST.ts
  quadratic-api/src/stripe/stripe.ts
  quadratic-client/package.json
  quadratic-client/public/version.json
  quadratic-client/src/app/ai/hooks/useAIRequestToAPI.tsx
  quadratic-client/src/app/ai/tools/aiToolsActions.ts
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystDebugChatInput.tsx
  quadratic-client/src/auth/auth0.ts
  quadratic-client/src/auth/ory.ts
  quadratic-client/src/index.tsx
  quadratic-client/src/routes/file.$uuid.tsx
  quadratic-client/src/routes/file.tsx
  quadratic-client/src/routes/onboarding.tsx
  quadratic-client/src/routes/teams.$teamUuid.files.create.tsx
  quadratic-client/src/shared/api/apiClient.ts
  quadratic-client/src/shared/api/fetchFromApi.ts
  quadratic-client/src/shared/api/xhrFromApi.ts
  quadratic-client/src/shared/components/connections/Connections.tsx
  quadratic-client/src/shared/components/connections/ConnectionsNew.tsx
  quadratic-client/src/shared/components/connections/ConnectionsPotential.tsx
  quadratic-client/src/shared/components/connections/connectionsByType.ts
  quadratic-client/src/shared/components/connections/logo-athena.svg
  quadratic-client/src/shared/components/connections/logo-cassandra.svg
  quadratic-client/src/shared/components/connections/logo-clickhouse.svg
  quadratic-client/src/shared/components/connections/logo-databricks.svg
  quadratic-client/src/shared/components/connections/logo-dynamodb.svg
  quadratic-client/src/shared/components/connections/logo-mongodb.svg
  quadratic-client/src/shared/components/connections/logo-oracle.svg
  quadratic-client/src/shared/components/connections/logo-redshift.svg
  quadratic-client/src/shared/components/connections/logo-s3.svg
  quadratic-client/src/shared/shadcn/ui/breadcrumb.tsx
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/ai/models/AI_MODELS.ts
  quadratic-shared/package.json
  quadratic-shared/typesAndSchemas.ts
Labels: cla-signed

#3369 chore: user email - not null, unique identified and in jwt token
  docker/ory-auth/config/claims.jsonnet
  docker/ory-auth/config/kratos.yml
  package.json
  quadratic-api/jest.setup.js
  quadratic-api/prisma/migrations/20250814205913_user_email_not_null/migration.sql
  quadratic-api/prisma/schema.prisma
  quadratic-api/src/auth/auth.ts
  quadratic-api/src/auth/auth0.test.ts
  quadratic-api/src/auth/auth0.ts
  quadratic-api/src/auth/ory.ts
  quadratic-api/src/middleware/getFile.test.ts
  quadratic-api/src/middleware/getTeam.test.ts
  quadratic-api/src/middleware/user.test.ts
  quadratic-api/src/middleware/user.ts
  quadratic-api/src/routes/v0/education.POST.test.ts
  quadratic-api/src/routes/v0/education.POST.ts
  quadratic-api/src/routes/v0/files.$uuid.PATCH.test.ts
  quadratic-api/src/routes/v0/files.$uuid.invites.$inviteId.DELETE.test.ts
  quadratic-api/src/routes/v0/files.$uuid.invites.POST.test.ts
  quadratic-api/src/routes/v0/files.$uuid.invites.POST.ts
  quadratic-api/src/routes/v0/files.$uuid.sharing.GET.test.ts
  quadratic-api/src/routes/v0/files.$uuid.sharing.GET.ts
  quadratic-api/src/routes/v0/files.$uuid.sharing.PATCH.test.ts
  quadratic-api/src/routes/v0/files.GET.test.ts
  quadratic-api/src/routes/v0/files.POST.test.ts
  quadratic-api/src/routes/v0/files.test.ts
  quadratic-api/src/routes/v0/teams.$uuid.PATCH.test.ts
  quadratic-api/src/routes/v0/teams.$uuid.billing.checkout.session.GET.ts
  quadratic-api/src/routes/v0/teams.$uuid.invites.$inviteId.DELETE.test.ts
  quadratic-api/src/routes/v0/teams.$uuid.invites.POST.test.ts
  quadratic-api/src/routes/v0/teams.$uuid.invites.POST.ts
  quadratic-api/src/routes/v0/teams.$uuid.users.$userId.DELETE.test.ts
  quadratic-api/src/routes/v0/teams.$uuid.users.$userId.PATCH.test.ts
  quadratic-api/src/routes/v0/teams.GET.test.ts
  quadratic-api/src/tests/testDataGenerator.ts
  quadratic-api/src/types/Request.ts
  quadratic-api/src/utils/teams.test.ts
  quadratic-client/src/app/gridGL/pixiApp/urlParams/UrlParamsUser.ts
  quadratic-client/src/app/ui/menus/AIAnalyst/hooks/useSubmitAIAnalystPrompt.tsx
  quadratic-client/src/routes/file.$uuid.duplicate.tsx
  quadratic-connection/app.json
  quadratic-files/app.json
  quadratic-multiplayer/app.json
Labels: cla-signed, status: ready to merge, QA

#3385 fix: backup model in config
  quadratic-api/src/ai/handler/ai.handler.ts
  quadratic-shared/ai/models/AI_MODELS.ts
Labels: cla-signed, status: ready to merge, QA

#3389 fix: tool card text length
  quadratic-client/src/app/ai/toolCards/AddDateTimeValidation.tsx
  quadratic-client/src/app/ai/toolCards/AddListValidation.tsx
  quadratic-client/src/app/ai/toolCards/AddLogicalValidations.tsx
  quadratic-client/src/app/ai/toolCards/AddMessage.tsx
  quadratic-client/src/app/ai/toolCards/AddNumberValidation.tsx
  quadratic-client/src/app/ai/toolCards/AddTextValidation.tsx
  quadratic-client/src/app/ai/toolCards/ColorSheets.tsx
  quadratic-client/src/app/ai/toolCards/ConvertToTable.tsx
  quadratic-client/src/app/ai/toolCards/CreateNewSheet.tsx
  quadratic-client/src/app/ai/toolCards/DeleteCells.tsx
  quadratic-client/src/app/ai/toolCards/DeleteColumns.tsx
  quadratic-client/src/app/ai/toolCards/DeleteRows.tsx
  quadratic-client/src/app/ai/toolCards/DeleteSheet.tsx
  quadratic-client/src/app/ai/toolCards/DuplicateSheet.tsx
  quadratic-client/src/app/ai/toolCards/InsertColumns.tsx
  quadratic-client/src/app/ai/toolCards/InsertRows.tsx
  quadratic-client/src/app/ai/toolCards/MoveCells.tsx
  quadratic-client/src/app/ai/toolCards/MoveSheet.tsx
  quadratic-client/src/app/ai/toolCards/RemoveValidations.tsx
  quadratic-client/src/app/ai/toolCards/RenameSheet.tsx
  quadratic-client/src/app/ai/toolCards/RerunCode.tsx
  quadratic-client/src/app/ai/toolCards/ResizeColumns.tsx
  quadratic-client/src/app/ai/toolCards/ResizeRows.tsx
  quadratic-client/src/app/ai/toolCards/SetBorders.tsx
  quadratic-client/src/app/ai/toolCards/SetTextFormats.tsx
Labels: cla-signed, status: ready to merge, QA
