Repository quadratichq/quadratic, pull requests merged in 2025-01, with the labels that each got.

#2154 More Formulas: VAR, STDEV, PMT
  quadratic-client/src/app/ai/docs/FormulaDocs.ts
  quadratic-core/src/controller/formula.rs
  quadratic-core/src/formulas/functions/financial.rs
  quadratic-core/src/formulas/functions/mathematics.rs
  quadratic-core/src/formulas/functions/mod.rs
  quadratic-core/src/formulas/functions/statistics.rs
  quadratic-core/src/formulas/functions/trigonometry.rs
  quadratic-core/src/util.rs
Labels: cla-signed, status: ready to merge

#2166 Add `EDATE()` and `EOMONTH()` formula functions
  quadratic-core/src/formulas/functions/datetime.rs
  quadratic-core/src/values/convert.rs
Labels: cla-signed, status: ready to merge

#2167 feat: support duplicating example files from outside the app
  quadratic-client/src/app/gridGL/HTMLGrid/EmptyGridMessage.tsx
  quadratic-client/src/routes/examples.tsx
  quadratic-client/src/routes/files.create.tsx
  quadratic-client/src/shared/components/ShareDialog.tsx
  quadratic-client/src/shared/constants/routes.ts
Labels: cla-signed, status: ready for user test

#2175 Formulas properly stores ranges instead of individual cells
  Cargo.lock
  quadratic-core/src/formulas/ast.rs
  quadratic-core/src/formulas/ctx.rs
  quadratic-core/src/formulas/functions/lookup.rs
Labels: cla-signed, status: ready for code review, status: ready for user test

#2174 fix: copy-paste a code cell isn't changing relative reference if sheet name is included
  Cargo.lock
  quadratic-core/Cargo.toml
  quadratic-core/src/a1/a1_selection/a1_selection_mutate.rs
  quadratic-core/src/a1/a1_selection/mod.rs
  quadratic-core/src/controller/execution/execute_operation/execute_col_rows.rs
  quadratic-core/src/controller/operations/autocomplete.rs
  quadratic-core/src/controller/operations/clipboard.rs
  quadratic-core/src/controller/user_actions/auto_complete.rs
  quadratic-core/src/grid/code_cell.rs
  quadratic-core/src/pos.rs
Labels: cla-signed, status: ready to merge

#2160 fix: ai formula references using q.cells
  quadratic-client/src/app/ai/hooks/useCurrentSheetContextMessages.tsx
  quadratic-client/src/app/ai/hooks/useOtherSheetsContextMessages.tsx
  quadratic-client/src/app/ai/hooks/useSelectionContextMessages.tsx
  quadratic-client/src/app/ai/hooks/useVisibleContextMessages.tsx
Labels: cla-signed, status: ready for code review, status: ready for user test

#2179 feat: remove dependence on mui for spinner
  quadratic-client/src/app/gridGL/HTMLGrid/codeRunning/CodeRunning.tsx
  quadratic-client/src/app/ui/QuadraticSidebar.tsx
  quadratic-client/src/app/ui/menus/BottomBar/SyncState.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorBody.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/CodeEditorHeader.tsx
  quadratic-client/src/shared/components/Icons.tsx
  quadratic-client/src/shared/components/connections/ConnectionFormActions.tsx
Labels: cla-signed, status: ready for code review, status: ready for user test

#2168 Add `IFNA()` formula function
  quadratic-core/src/error_run.rs
  quadratic-core/src/formulas/functions/logic.rs
  quadratic-core/src/grid/file/v1_5/run_error.rs
  quadratic-core/src/grid/file/v1_7/run_error_schema.rs
Labels: cla-signed, status: ready to merge

#2185 fix: proxy calls are cached
  package-lock.json
  quadratic-connection/src/server.rs
Labels: cla-signed, status: ready for user test

#2190 Fix wasm-bindgen warnings
  Cargo.lock
  quadratic-core/Cargo.toml
Labels: cla-signed, status: ready to merge

#1975 feat: user selectable csv delimiter
  Cargo.lock
  quadratic-client/src/app/gridGL/HTMLGrid/GridFileInput.tsx
  quadratic-client/src/app/quadratic-core-types/index.d.ts
  quadratic-client/src/app/ui/QuadraticUI.tsx
  quadratic-client/src/app/ui/components/CSVImportSettings.tsx
  quadratic-client/src/app/ui/components/FileDragDropWrapper.tsx
  quadratic-client/src/app/ui/hooks/useFileImport.tsx
  quadratic-client/src/app/ui/hooks/useGetCSVImportSettings.tsx
  quadratic-client/src/app/web-workers/quadraticCore/coreClientMessages.ts
  quadratic-client/src/app/web-workers/quadraticCore/quadraticCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreClient.ts
  quadratic-client/src/dashboard/atoms/filesImportProgressAtom.ts
  quadratic-client/src/dashboard/atoms/filesImportSettingsAtom.ts
  quadratic-client/src/dashboard/components/FileDragDrop.tsx
  quadratic-client/src/dashboard/components/ImportProgressList.tsx
  quadratic-client/src/dashboard/components/NewFileButton.tsx
  quadratic-client/src/routes/_dashboard.tsx
  quadratic-client/src/shared/shadcn/ui/table.tsx
  quadratic-core/Cargo.toml
  quadratic-core/benches/grid_benchmark.rs
  quadratic-core/src/controller/operations/import.rs
  quadratic-core/src/controller/user_actions/import.rs
  quadratic-core/src/wasm_bindings/controller/import.rs
Labels: cla-signed

#2194 chore: remove stack comment
  .github/workflows/preview-build-deploy-images.yml
  .github/workflows/preview-create-stack.yml
  .github/workflows/preview-delete-stack.yml
  .github/workflows/qa-close.yml
  .github/workflows/qa-deploy.yml
Labels: cla-signed

#2195 Update qa-deploy.yml
  .github/workflows/qa-close.yml
  .github/workflows/qa-deploy.yml
Labels: cla-signed

#2202 fix: long running lint job on ci
  .github/workflows/ci.yml
Labels: cla-signed

#2176 Add `ROUND()`, `ROUNDUP()`, `ROUNDDOWN()`, and `TRUNC()` formula functions
  Cargo.lock
  quadratic-core/Cargo.toml
  quadratic-core/src/formulas/functions/mathematics.rs
  quadratic-core/src/formulas/tests.rs
  quadratic-core/src/util.rs
Labels: cla-signed, status: ready to merge

#2206 Add support for zstd compression
  quadratic-rust-shared/Cargo.toml
Labels: cla-signed

#2219 fix: files service
  quadratic-core/src/grid/file/shift_negative_offsets.rs
Labels: cla-signed

#2220 Main
  quadratic-core/src/grid/file/shift_negative_offsets.rs
Labels: cla-signed

#2223 chore: add files, rust-shared and rust-client tests on CI
  .github/workflows/ci.yml
  docker-compose.yml
  quadratic-core/package.json
  quadratic-files/package.json
  quadratic-rust-client/package.json
  quadratic-rust-shared/package.json
Labels: cla-signed

#2225 fix: try fail_fast=false on CI matrix strategy
  .github/workflows/ci.yml
Labels: cla-signed

#2214 fix: selection with shift + ctrl + arrows not working as expected
  quadratic-client/src/app/gridGL/interaction/keyboard/keyboardPosition.ts
Labels: cla-signed

#2215 fix: slow migration to 1.7.1
  quadratic-core/src/controller/active_transactions/pending_transaction.rs
  quadratic-core/src/controller/execution/execute_operation/execute_col_rows.rs
  quadratic-core/src/grid/file/shift_negative_offsets.rs
  quadratic-core/src/grid/sheet/col_row/column.rs
  quadratic-core/src/grid/sheet/col_row/row.rs
Labels: cla-signed, status: ready for code review, status: ready for user test, blocked

#2189 Add `SUMPRODUCT()` formula
  quadratic-core/src/formulas/functions/array.rs
  quadratic-core/src/formulas/functions/macros.rs
  quadratic-core/src/formulas/parser/rules/expression.rs
  quadratic-core/src/span.rs
  quadratic-core/src/values/array.rs
Labels: cla-signed, status: ready to merge, status: requested changes

#2192 fix: a1 bug, references overrunning their bounds
  .vscode/settings.json
  quadratic-core/src/controller/execution/run_code/run_formula.rs
  quadratic-core/src/formulas/ast.rs
  quadratic-core/src/formulas/criteria.rs
  quadratic-core/src/formulas/ctx.rs
  quadratic-core/src/formulas/functions/lookup.rs
  quadratic-core/src/formulas/functions/mathematics.rs
  quadratic-core/src/formulas/functions/statistics.rs
  quadratic-core/src/formulas/parser/mod.rs
  quadratic-core/src/formulas/tests.rs
Labels: cla-signed, status: ready to merge, status: requested changes

#2224 Add stats endpoint to the files service
  Cargo.lock
  package.json
  quadratic-files/src/file.rs
  quadratic-files/src/server.rs
  quadratic-files/src/state/stats.rs
  quadratic-files/src/test_util.rs
  quadratic-files/src/truncate.rs
  quadratic-rust-shared/src/sql/mysql_connection.rs
Labels: cla-signed, status: ready to merge, status: ready for user test

#2221 Remove logo from Plotly charts bar
  quadratic-kernels/python-wasm/quadratic_py/process_output.py
Labels: cla-signed, status: ready for user test

#2139 feat: persist active sheet in URL
  quadratic-client/src/app/ui/menus/SheetBar/SheetBar.tsx
  quadratic-client/src/shared/components/ShareDialog.tsx
Labels: cla-signed, status: ready for code review, status: requested changes, status: ready for user test

#2054 Open recent files from within a sheet
  quadratic-client/src/app/events/events.ts
  quadratic-client/src/app/ui/components/FileProvider.tsx
  quadratic-client/src/app/ui/menus/TopBar/TopBarMenus/FileMenubarMenu.tsx
  quadratic-client/src/routes/api.files.$uuid.ts
  quadratic-client/src/routes/file.$uuid.tsx
  quadratic-client/src/shared/components/Icons.tsx
  quadratic-client/src/shared/utils/updateRecentFiles.ts
Labels: cla-signed, status: ready for code review

#2203 revokeObjectUrl
  quadratic-client/src/app/helpers/downloadFileInBrowser.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascript.ts
Labels: cla-signed, status: ready for user test

#2212 Add zstd to core Cargo.toml
  .github/workflows/ci.yml
  Cargo.lock
  Dockerfile.dev
  infra/client/build-client-ci.sh
  package.json
  quadratic-client/Dockerfile
  quadratic-client/package.json
  quadratic-core/Cargo.toml
  quadratic-core/package.json
  quadratic-rust-client/package.json
  quadratic-rust-shared/Cargo.toml
Labels: cla-signed, status: ready for code review, status: ready for user test

#2233 fix: amplify build
  Cargo.lock
  infra/client/build-client-ci.sh
Labels: cla-signed

#2234 fix: amplify build, use sudo
  infra/client/build-client-ci.sh
Labels: cla-signed

#2235 fix: qa wolf - Code Chat AI Prompt Error
  quadratic-client/src/app/ui/menus/AIAnalyst/hooks/useSubmitAIAnalystPrompt.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/hooks/useSubmitAIAssistantPrompt.tsx
Labels: cla-signed, status: ready for code review, status: ready for user test

#2156 Option::unwrap in const is stable now use it
  quadratic-core/src/values/array_size.rs
Labels: cla-signed, status: requested changes

#2236 infra: analytics s3 bucket
  .env.docker
  docker-compose.yml
  docker/localstack/scripts/init-aws.sh
  quadratic-api/.env.example
  quadratic-api/.env.test
  quadratic-api/src/env-vars.ts
  quadratic-api/src/routes/v0/ai.chat.POST.ts
  quadratic-api/src/routes/v0/files.$uuid.thumbnail.POST.ts
  quadratic-api/src/storage/s3.ts
  quadratic-api/src/storage/storage.ts
  quadratic-api/src/utils/createFile.ts
Labels: cla-signed, status: ready for code review, status: ready for user test

#2242 Update readme.md
  README.md
Labels: cla-signed

#2246 Update python AI docs for tables
  quadratic-api/src/ai/docs/PythonDocs.ts
  quadratic-api/src/ai/helpers/context.helper.ts
Labels: cla-signed

#2251 fix: unsafe unwraps
  .github/workflows/preview-build-deploy-images.yml
  quadratic-connection/src/server.rs
  quadratic-files/src/server.rs
  quadratic-rust-shared/src/sql/mssql_connection.rs
  quadratic-shared/typesAndSchemasConnections.ts
Labels: cla-signed, status: ready for code review, status: ready for user test
