Repository quadratichq/quadratic, pull requests merged in 2025-02, with the labels that each got.

#2271 chore: track ai usage
  quadratic-api/prisma/migrations/20250211034001_optional_analytics/migration.sql
  quadratic-api/prisma/migrations/20250211191943_optional_analytics_and_token_usage_and_message_type/migration.sql
  quadratic-api/prisma/schema.prisma
  quadratic-api/src/ai/handler/anthropic.ts
  quadratic-api/src/ai/handler/bedrock.ts
  quadratic-api/src/ai/handler/openai.ts
  quadratic-api/src/ai/helpers/anthropic.helper.ts
  quadratic-api/src/ai/helpers/bedrock.helper.ts
  quadratic-api/src/ai/helpers/openai.helper.ts
  quadratic-api/src/routes/v0/ai.chat.POST.ts
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystMessages.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/hooks/useSubmitAIAnalystPrompt.tsx
  quadratic-shared/ai/helpers/message.helper.ts
  quadratic-shared/ai/models/AI_MODELS.ts
  quadratic-shared/typesAndSchemasAI.ts
Labels: cla-signed

#2293 feat: add 3.7 sonnet
  package-lock.json
  quadratic-api/package.json
  quadratic-api/src/ai/handler/anthropic.ts
  quadratic-api/src/ai/handler/bedrock.ts
  quadratic-api/src/ai/handler/openai.ts
  quadratic-api/src/ai/helpers/anthropic.helper.ts
  quadratic-api/src/ai/helpers/bedrock.helper.ts
  quadratic-api/src/ai/helpers/openai.helper.ts
  quadratic-api/src/routes/v0/ai.chat.POST.test.ts
  quadratic-api/src/routes/v0/ai.chat.POST.ts
  quadratic-client/src/app/ai/components/SelectAIModelMenu.tsx
  quadratic-client/src/app/ai/hooks/useAIModel.tsx
  quadratic-client/src/app/ai/hooks/useAIRequestToAPI.tsx
  quadratic-client/src/app/ai/hooks/useGetChatName.tsx
  quadratic-client/src/app/ai/offline/aiAnalystChats.test.ts
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystMessages.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/hooks/useSubmitAIAnalystPrompt.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/AIAssistant/AIAssistantMessages.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/hooks/useSubmitAIAssistantPrompt.tsx
  quadratic-client/src/app/ui/menus/SheetBar/SheetBarTab.tsx
  quadratic-client/src/app/ui/menus/Validations/Validation/useValidationData.ts
  quadratic-shared/ai/helpers/model.helper.ts
  quadratic-shared/ai/models/AI_MODELS.ts
  quadratic-shared/typesAndSchemasAI.ts
Labels: cla-signed

#2296 fix: ai model select
  Cargo.lock
  Cargo.toml
  VERSION
  package.json
  quadratic-api/package.json
  quadratic-client/package.json
  quadratic-client/src/app/ai/hooks/useAIModel.tsx
  quadratic-connection/Cargo.toml
  quadratic-core/Cargo.toml
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
  quadratic-rust-client/Cargo.toml
  quadratic-rust-shared/Cargo.toml
  quadratic-shared/ai/models/AI_MODELS.ts
  quadratic-shared/package.json
Labels: cla-signed

#2300 Hide hoverCell when the cell has the inline editor open
  quadratic-client/src/app/gridGL/HTMLGrid/hoverCell/HoverCell.tsx
Labels: cla-signed, status: ready for user test

#2299 fix doctests
  quadratic-client/Dockerfile
  quadratic-client/src/app/gridGL/HTMLGrid/hoverCell/HoverCell.tsx
  quadratic-core/src/formulas/parser/mod.rs
Labels: cla-signed

#2304 Accept single character column and table names
  quadratic-core/src/grid/data_table/mod.rs
Labels: status: ready for code review, status: ready for user test

#2302 Move code-run indicator to data cell if Table UI is showing
  quadratic-client/src/app/gridGL/HTMLGrid/codeRunning/CodeRunning.tsx
Labels: cla-signed, status: ready for user test

#2307 fix: correct context menu for JS charts
  quadratic-client/src/app/gridGL/HTMLGrid/contextMenus/GridContextMenu.tsx
Labels: cla-signed

#2311 Table columns properly show after culling
  quadratic-client/src/app/gridGL/cells/tables/Table.ts
Labels: status: ready for code review, status: ready for user test

#2310 AI docs small change
  quadratic-api/src/ai/docs/PythonDocs.ts
Labels: cla-signed

#2308 fix: get cells
  quadratic-client/src/app/quadratic-core-types/index.d.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/javascriptCoreMessages.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascriptAPI.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/generateJavascriptForRunner.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/generatedJavascriptForEditor.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/javascriptLibrary.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascriptCore.ts
  quadratic-client/src/app/web-workers/pythonWebWorker/pythonCoreMessages.ts
  quadratic-client/src/app/web-workers/pythonWebWorker/worker/python.ts
  quadratic-client/src/app/web-workers/pythonWebWorker/worker/pythonCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreJavascript.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/corePython.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/renderCore.ts
  quadratic-core/src/bin/export_types.rs
  quadratic-core/src/controller/execution/auto_resize_row_heights.rs
  quadratic-core/src/controller/execution/control_transaction.rs
  quadratic-core/src/controller/execution/execute_operation/execute_offsets.rs
  quadratic-core/src/controller/execution/receive_multiplayer.rs
  quadratic-core/src/controller/execution/run_code/get_cells.rs
  quadratic-core/src/controller/execution/run_code/run_javascript.rs
  quadratic-core/src/controller/execution/run_code/run_python.rs
  quadratic-core/src/grid/sheet/cell_array.rs
  quadratic-core/src/wasm_bindings/controller/code.rs
  quadratic-kernels/python-wasm/quadratic_py/quadratic_api/quadratic.py
  quadratic-kernels/python-wasm/tests/test.py
Labels: cla-signed, status: ready to merge, QA

#2301 Return ranges within a column as an array in JS, regardless of emptiness
  quadratic-client/src/app/quadratic-core-types/index.d.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/javascriptCoreMessages.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/javascriptAPI.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/generateJavascriptForRunner.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/generatedJavascriptForEditor.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascript/runner/javascriptLibrary.ts
  quadratic-client/src/app/web-workers/javascriptWebWorker/worker/javascriptCore.ts
  quadratic-client/src/app/web-workers/pythonWebWorker/pythonCoreMessages.ts
  quadratic-client/src/app/web-workers/pythonWebWorker/worker/python.ts
  quadratic-client/src/app/web-workers/pythonWebWorker/worker/pythonCore.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/core.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/coreJavascript.ts
  quadratic-client/src/app/web-workers/quadraticCore/worker/corePython.ts
  quadratic-client/src/app/web-workers/renderWebWorker/worker/renderCore.ts
  quadratic-core/src/a1/a1_selection/query.rs
  quadratic-core/src/a1/cell_ref_range/query.rs
  quadratic-core/src/a1/ref_range_bounds/query.rs
  quadratic-core/src/bin/export_types.rs
  quadratic-core/src/controller/execution/auto_resize_row_heights.rs
  quadratic-core/src/controller/execution/control_transaction.rs
  quadratic-core/src/controller/execution/execute_operation/execute_offsets.rs
  quadratic-core/src/controller/execution/receive_multiplayer.rs
  quadratic-core/src/controller/execution/run_code/get_cells.rs
  quadratic-core/src/controller/execution/run_code/run_javascript.rs
  quadratic-core/src/controller/execution/run_code/run_python.rs
  quadratic-core/src/grid/sheet/cell_array.rs
  quadratic-core/src/wasm_bindings/controller/code.rs
  quadratic-kernels/python-wasm/quadratic_py/quadratic_api/quadratic.py
  quadratic-kernels/python-wasm/tests/test.py
Labels: cla-signed, status: ready for user test

#2306 Minor UI Changes
  quadratic-client/src/app/gridGL/UI/gridHeadings/GridHeadings.ts
  quadratic-client/src/app/gridGL/cells/tables/Table.ts
  quadratic-client/src/app/ui/QuadraticSidebar.tsx
  quadratic-client/src/app/ui/components/AIUserMessageForm.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystHeader.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystMessages.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIAnalystUserMessageForm.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/AIThinkingBlock.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/toolCards/AddDataTable.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/toolCards/SetCellValues.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/toolCards/SetCodeCellValue.tsx
  quadratic-client/src/app/ui/menus/AIAnalyst/toolCards/ToolCard.tsx
  quadratic-client/src/app/ui/menus/CodeEditor/AIAssistant/AIAssistantMessages.tsx
  quadratic-client/src/shared/components/Icons.tsx
  quadratic-shared/typesAndSchemasAI.ts
Labels: cla-signed, status: ready for code review

#2312 Minor fixes to ensure visible
  quadratic-client/src/app/actions/selectionActionsSpec.ts
  quadratic-client/src/app/grid/sheet/SheetCursor.ts
  quadratic-client/src/app/gridGL/interaction/viewportHelper.ts
Labels: cla-signed, status: ready for user test

#2335 fix: validation selection error
  quadratic-client/src/app/grid/sheet/Sheet.ts
Labels: cla-signed

#2337 feat: add gpt 4.5 preview
  quadratic-shared/ai/models/AI_MODELS.ts
  quadratic-shared/typesAndSchemasAI.ts
Labels: cla-signed

#2338 Show column headers for connection upgrades
  quadratic-core/src/grid/file/v1_7_1/upgrade.rs
Labels: cla-signed

#2339 fix: table name update on duplicate sheet
  quadratic-core/src/a1/a1_context/table_map.rs
  quadratic-core/src/controller/execution/execute_operation/execute_data_table.rs
  quadratic-core/src/controller/execution/execute_operation/execute_sheets.rs
  quadratic-core/src/controller/execution/run_code/mod.rs
  quadratic-core/src/controller/operations/autocomplete.rs
  quadratic-core/src/controller/operations/clipboard.rs
  quadratic-core/src/controller/operations/data_table.rs
  quadratic-core/src/controller/operations/import.rs
  quadratic-core/src/grid/data_table/mod.rs
  quadratic-shared/ai/models/AI_MODELS.ts
Labels: cla-signed, status: ready for user test

#2345 QA: Feb 27 - Tables Followup Target Shipping Monday Afternoon
  .github/workflows/production-bump-version.yml
  quadratic-core/src/grid/sheet/a1_context.rs
Labels: cla-signed

#2348 Add space to default sheet name
  quadratic-api/src/data/current_blank.grid
  quadratic-core/src/a1/a1_context/mod.rs
  quadratic-core/src/a1/a1_selection/create.rs
  quadratic-core/src/a1/a1_selection/parse.rs
  quadratic-core/src/a1/a1_selection/query.rs
  quadratic-core/src/a1/a1_selection/select.rs
  quadratic-core/src/a1/cell_ref_range/create.rs
  quadratic-core/src/a1/cell_ref_range/to_table_ref.rs
  quadratic-core/src/a1/sheet_cell_ref_range.rs
  quadratic-core/src/a1/sheet_name.rs
  quadratic-core/src/controller/active_transactions/pending_transaction.rs
  quadratic-core/src/controller/execution/execute_operation/execute_sheets.rs
  quadratic-core/src/controller/execution/receive_multiplayer.rs
  quadratic-core/src/controller/execution/run_code/get_cells.rs
  quadratic-core/src/controller/execution/run_code/run_connection.rs
  quadratic-core/src/controller/formula.rs
  quadratic-core/src/controller/operations/clipboard.rs
  quadratic-core/src/controller/operations/code_cell.rs
  quadratic-core/src/controller/operations/sheets.rs
  quadratic-core/src/controller/sheets.rs
  quadratic-core/src/controller/user_actions/sheets.rs
  quadratic-core/src/formulas/legacy_cell_ref.rs
  quadratic-core/src/formulas/lexer.rs
  quadratic-core/src/formulas/parser/rules/atoms.rs
  quadratic-core/src/grid/code_cell.rs
  quadratic-core/src/grid/data_table/mod.rs
  quadratic-core/src/grid/file/migrate_code_cell_references.rs
  quadratic-core/src/grid/file/mod.rs
  quadratic-core/src/grid/selection.rs
  quadratic-core/src/grid/sheet.rs
  quadratic-core/src/grid/sheets.rs
  quadratic-core/src/util.rs
  quadratic-rust-shared/data/grid/current_blank.grid
Labels: cla-signed

#2358 Make dbgjs a feature flag
  quadratic-core/Cargo.toml
  quadratic-core/src/grid/sheet/a1_context.rs
  quadratic-core/src/util.rs
  quadratic-files/Cargo.toml
  quadratic-multiplayer/Cargo.toml
Labels: cla-signed, status: ready for code review
